### ISSUE TITLE
课程评论

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#100]
1. 在数据库增加评价实体，允许用户对课程进行评论；
2. 课程添加“评论区”，显示目前用户对课程的评论；

评论部分前端可以参考 http://demo.edusoho.com/course/1/reviews/ 。 评论需要可以打分，同时支持具体文字评论。每次评论后需要更新当前课程的平均评分（课程实体可以按照需求增加平均评分这一字段）。

@luozhx 看到了请在评论区进行回复！

**Comment by luozhx** [comment]
收到

**Comment by xuelangZF** [comment]
修复一些小的问题：

1. 没有登录用户应该也可以看到课程评论的
2. 用户没用评论过课程的话，就不要显示“重新评论”
3. Ajax 对评论的处理前，需要用户是登录的

提交前自己做测试要完整点！
@luozhx  请回复是否明白上面的三个问题

**Comment by luozhx** [comment]
收到，已修复

**Comment by xuelangZF** [comment]
简单测了一下，问题还是很多！

1.  重新评论时，**提交后会多次弹出提交成功的提示**！这里如果想允许重新评论的话，我建议是在当前用户评论的右侧加一个更新评论的按钮，然后点击后，会把他之前的评论放在一个编辑框，然后让其更新。而不是弹出一个空白的评论框。
2. 评论提交后不建议有一个提交成功的提示，直接在当前页面将其更新出来即可。
3. 关于权限，如果是没有登录用户或者没有假如该课程的用户，可以给一个“登录后加入课程才可以评价课程的”提示栏目。也就是说只有登录用户，并且已经加入后的用户才能进行评论。

权限控制的话，你可以看我之前 “加入课程” 和 “退出课程” 的逻辑处理部分，对权限的控制。

此外，还有一个大问题，你的 process_comment 函数，

```
@course.route('/process/comment/', methods=['POST'])
def process_comment():
```

没有权限控制，也就是说我随便发一个 post 请求（**你只是在网页前端不提供操作的接口，但是可以用 postman或者脚本来发起请求**），就可以进行相应的数据库操作了。

**Comment by luozhx** [comment]
第一点的话，我提交前测试时重新评论不会有多次弹出的情况，刚才更新的仓库后测试了一下也没有出现这种情况。另外如果将评论放在当前用户评论右侧的话，当评论数量比较多的话要找自己的评论可能比较困难，我觉得还是放在最前面会比较好一点。
第二三点的话我稍后修改

**Comment by xuelangZF** [comment]
重新评论放右边确实有问题，还是放前面好。

第一个 Bug 我没描述清楚。你可以这样复现，随便打开一个课程，点击课堂评价，然后在里面评价，再重新评价（这时候没有问题）。**下面点击课程试卷，紧接着点进课程评价，再重新评价，就会多次弹出评价成功的提示框。**

![image](https://cloud.githubusercontent.com/assets/2769831/20472261/278aa45a-aff3-11e6-9a9c-5d1d4f60dd38.png)

**Comment by luozhx** [comment]
权限控制的话我就在处理前直接像@student_in_course里面直接判断current_user是否在curr_course.users中可以吗？因为process函数里面没有cid这个参数所以不是很好直接用@student_in_course。

**Comment by xuelangZF** [comment]
可以啊

**Comment by xuelangZF** [comment]
Fixed on commit 39657cddea3a91cba214c9f22924f9bc12ac2df9
