### ISSUE TITLE
模板文件重构

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#111]
现在的模板文件重构的太过于细小了，并且好多小的模板在其他地方并没有多次使用。比如： `widget_paper_choice_options.html` ，只在 `widget_paper_question_detail` 中include 过一次，这样非常不方便理解。

我们把模板切分的目的是为了可以在其他地方方便地引用一个模板，不是说越小越好。

目前之所以让切分`所有的试题模块`，是为了可以在虚拟实验室模块中直接 include 一个子模板即可展示问题。但是模板切分过细的话，组合不同的模板时仍然需要写很多冗余代码。

以选择题为例，建议将下面内容（一整个选择题包含的元素，其实最好是把查看答案也放在里面，不过考虑到题库中查看答案已经放在其他地方，所以这里也可以先不管）作为一个 模板 文件：

![image](https://cloud.githubusercontent.com/assets/2769831/20553293/59309040-b18e-11e6-9c49-4cee78e75b9e.png)

这样我在虚拟实验室中引入时就能得到一个选择题的展示，而不是只得到部分内容：

![image](https://cloud.githubusercontent.com/assets/2769831/20553324/a2eb774a-b18e-11e6-8692-39eb205a6289.png)

# js 位置
此外，注意如果一个模板需要用到 js 文件，直接把 js 写进该模板中，不要放在引用该模板的父模板中。比如 practice_detail 文件中：

```
{% if type == 'choice' %}
    {% with choices=practices %}
        {% include 'problem/widget_choice_detail.html' %}
    {% endwith %}
{% elif type == 'fill' %}
    {% with fills=practices %}
        {% include 'problem/widget_fill_detail.html' %}
    {% endwith %}
{% elif type == 'judge' %}
    {% with judges=practices %}
        {% include 'problem/widget_judge_detail.html' %}
    {% endwith %}
{% elif type == 'essay' %}
    {% with essays=practices %}
        {% include 'problem/widget_essay_detail.html' %}
    {% endwith %}
{% endif %}
```

这些子模板中没有写需要的 js ，所以还需要在practice_detail 中判断类型然后引入。

```
    {% if type == 'choice' %}
        <script src="{{ url_for('static', filename='js/problem/choice_detail.js') }}"></script>
    {% elif type == 'fill' %}
        <script src="{{ url_for('static', filename='js/problem/fill_detail.js') }}"></script>
    {% elif type == 'judge' %}
        <script src="{{ url_for('static', filename='js/problem/judge_detail.js') }}"></script>
    {% elif type == 'essay' %}
        <script src="{{ url_for('static', filename='js/problem/essay_detail.js') }}"></script>
    {% endif %}
```

更糟糕的是，如果我使用 `problem/widget_judge_detail.html` ，我就需要指导它用到了哪些js，然后在我的父页面引用，这样非常不便于我使用。如果把js放进 `problem/widget_judge_detail.html`，我引用文件就能得到所有的js效果。

@wzl281158150

**Comment by xuelangZF** [comment]
最迟明天搞定，我在虚拟实验室模块需要用到。收到请回复

**Comment by wzl281158150** [comment]
之所以不包含整个题目元素是因为 试卷和在线练习的要求不一致，试卷区分选择题类型，不同的题在不同的块显示，在线练习选择题是混合的，所以只将选项作为了模版

**Comment by wzl281158150** [comment]
只include一次的模版是因为以后极有可能使用，所以就先写了，不然以后又要回过来修改

**Comment by xuelangZF** [comment]
@wzl281158150  OK，明白了。那些很短的代码其实没有必要写成模板了，以后其实遇到的可能性也不高。

**Comment by xuelangZF** [comment]
js 的问题，因为分离了 模板 和 js，所以这里比较麻烦，还需要想一个更好的方案！

**Comment by wzl281158150** [comment]
就将模版需要用到的js 引用放进模版中感觉挺好的

**Comment by wzl281158150** [comment]
题目的话 选择题分成 提干  选项  和答案  这样的话 以后不同的要求可以自己组合

**Comment by xuelangZF** [comment]
嗯嗯，如果模板需要 js 少的话，直接用 script 嵌进页面，如果多的话，就放在一个 js 文件中，不过要包含在当前模板中。

**Comment by wzl281158150** [comment]
我的意思是  把 js的文件引用直接放进去就好 js代码还是在文件中

**Comment by xuelangZF** [comment]
测了一下，依然有问题！

![2016-11-23 8 03 37](https://cloud.githubusercontent.com/assets/2769831/20561147/fb663e4a-b1b7-11e6-8dd7-9df55f31a825.png)

1. 提交题目时“确认提交”和“继续答题”按钮都失效
2. 每个题目下面都有两个冒号，你的模板文件不干净！

你自己再看看有没有其他的问题！我简单看了下就有这么明显的两个问题！
@wzl281158150

**Comment by xuelangZF** [comment]
Fixed on commit fec1d02befb5da47e77bf4d9c2c7f152a75067b5
