### ISSUE TITLE
Python 代码风格

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#113]
一些小的细节：

1. 注意变量的名字，不要使用内置类型的名字。比如 `question.type==3`
2. 注意代码风格要尽量满足 PEP8，特别是每行长度不能太长（最好不要超过 120）

只要是 Pycharm 中给出下划线或者提示的地方，都说明不符合Python的编码规范。因此强烈建议使用 Pycharm！！

@all

**Comment by xuelangZF** [comment]
**代码中变量名不要用一些内置的名字**

```
file = request.files['file']
file_type = get_file_type(file.mimetype)
filename = filename.encode("utf-8")
```

第一行的 file，这样很不安全，容易出错。如果使用 Pycharm 的话，编辑器其实会给提示的（灰色下滑线）。

@ym13349140

**Comment by ym13349140** [comment]
好的~

**Comment by xuelangZF** [comment]
代码中变量名不要用一些内置模块的名字：

```
cur_time = time.strftime("%Y%m%d%H%M%S", time.localtime()) + ".png"
path = os.path.join(path, cur_time)
```

@wzl281158150   已经修复。下次注意

**Comment by xuelangZF** [comment]
不要用内置模块的名字！  
最好不要和外部变量名字重复！

![image](https://cloud.githubusercontent.com/assets/2769831/21489014/3fc74420-cc21-11e6-9b03-937a20ab0606.png)

@milanlanlan

**Comment by milanlanlan** [comment]
好的！
