### ISSUE TITLE
虚拟实验室后台管理模块

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#117]
虚拟实验室模块基本已经考虑成型了，需要考虑后台如何管理 knowledge 和 challenge 了。

特别注意每个challenge 需要从 material 中选择资料，需要从 program 和 practice 中选择题目。

@luozhx 

可以开始了

**Comment by luozhx** [comment]
收到

**Comment by xuelangZF** [comment]
发现了一个问题，新建任务时，http://127.0.0.1:5000/admin/lab/2/create/ 

如果编辑完基本信息之后，无法保存，会提示需要**添加实验任务**的提示。此时，也无法添加实验任务。

总之，添加实验任务这块逻辑还有问题。

**Comment by luozhx** [comment]
我测试了一下没有问题，提示需要添加实验任务是因为没有选择。填完基本信息后不用点保存，直接切换到实验任务那一栏选择后就可以保存了。

**Comment by xuelangZF** [comment]
直接切换到实验任务一栏，选择后，点保存没反应的。后台信息提示： POST /admin/lab/2/create/ HTTP/1.1" 404   

你再试试？

**Comment by xuelangZF** [comment]
还有一个问题，这里顺序是供用户输入的，有一个很大的问题，如果输入重复的数字，或者不连续的怎么办？

一个建议：创建时不用提供任务的顺序，默认后创建的是下一个任务。然后在 http://127.0.0.1:5000/admin/lab/1/ 页面，支持管理员重新调整各个任务的相对顺序。

**Comment by luozhx** [comment]
直接切换到实验任务一栏的话，可能是因为基本信息不完整，所以无法正常保存，我一会看一下。

模态框那种形式我也写过，我觉得效果一般，这个可以改。

至于顺序的话我会判断不允许小于0，如果比当前长度大的话就放最后，其余情况就是插入到你输入的那个序号中，其余的往后移动。
这里还有一个问题是修改实验后，用户的进度很难处理，可能顺序变了，也可能做过的题被删除了，会出现做过的题目比总题目还多的情况

**Comment by xuelangZF** [comment]
嗯嗯，正式上线后，就不允许修改顺序了，这里说的修改是创建时修改的。

你现在的处理方式也可以，不过感觉每次输入有点麻烦。可以先创建任务，最后一次性调整完毕。（如果觉得实现麻烦的话，用目前的这个也可以）

**Comment by luozhx** [comment]
拖拽的话我查了一下可以用jquery sortable实现，我可以试一下。
另外材料和题目的添加需要改在模态框吗？

**Comment by xuelangZF** [comment]
改为 modal 吧，这样的话，就没用之前的问题了。并且必填的选项前面最好加 * 提示一下下。

**Comment by luozhx** [comment]
现在是title, content, question必填，material 选填
改成模态框的话，左边的导航栏要放点什么呢

**Comment by xuelangZF** [comment]
左边的话就不用放了吧。。

**Comment by luozhx** [comment]
行，那就右边那块弄大一点吧。。。

**Comment by xuelangZF** [comment]
ok

**Comment by xuelangZF** [comment]
虚拟实验室部分，每个实验室其实有一个名字和概述的，也需要在后台提供修改的入口。 
@luozhx

**Comment by luozhx** [comment]
在编辑里面可以修改title和content，这个就是名字和概述吧？

**Comment by xuelangZF** [comment]
是所属知识点knowledge的标题和内容，不是challenge的。

**Comment by luozhx** [comment]
明白
