### ISSUE TITLE
案例展示页面

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#125]
案例展示部分，我稍后会把两个文档分享。

给你发了两个文档，你看看有什么不懂的及时反馈给我。界面的话可以按照他给的来，或者你有好的想法可以及时让我知道：

![image](https://cloud.githubusercontent.com/assets/2769831/20670553/50d8de28-b5b4-11e6-999e-270daf222a55.png)

@wzl281158150

**Comment by ym13349140** [comment]
师兄，请问我具体要做的是什么呀？

**Comment by wzl281158150** [comment]
收到

**Comment by wzl281158150** [comment]
不是很明白，案例展示的作用，是有一个算法的案例，然后展示其信息，同时允许修改提交代码？

**Comment by xuelangZF** [comment]
案例展示主要是案例的描述，然后有的案例可能附带了几个版本的代码，目前我们能只需要高亮显示代码即可，不用做修改提交的实现。

**Comment by wzl281158150** [comment]
几个版本与图中  优化1 2 这些对应吗？  代码语言是否需要支持多种？

**Comment by xuelangZF** [comment]
对的，优化 1 2 其实就是指的不同程序版本。语言的话是要支持多种的

**Comment by xuelangZF** [comment]
case_1/version_1/  是用来放案例的代码的吧？

感觉用 case/1/version_1 好点吧，case 目录下面放所有案例的代码（不然直接在 static 中放很多 case_i ，结构不太好）。

还有你把 case 的内容发我一份，我放进目录看看效果哈。

话说，前端看起来不大好看，哎，这是一个大问题。

**Comment by wzl281158150** [comment]
师兄，文件是我随便建的，你在对应目录下创建.py   .c   .cpp文件即可。前端我尽力了😂

**Comment by xuelangZF** [comment]
界面你去网上找点不错的站点看看，你这个太粗旷啦，不敢给老师看啊！

**Comment by xuelangZF** [comment]
目录修改后，你合并下冲突，再提交一份吧

**Comment by xuelangZF** [comment]
对了，案例展示的首页其实应该是一个所有案例的列表展示，可以参考 “在线课程” 的首页展示样子。对每个案例放一个不错的图片，配一点简单的文字说明。点进去一个案例之后，才是案例的具体页面。

@wzl281158150

**Comment by xuelangZF** [comment]
案例的具体页面中，左侧是一个简单的目录导航，可以参考 http://www.htmleaf.com/jQuery/Menu-Navigation/201607063693.html  ，右侧部分是显示的内容。

**Comment by xuelangZF** [comment]
案例展示的首页其实应该是一个所有案例的列表展示，可以参考 “在线课程” 的首页展示样子。对每个案例放一个不错的图片，配一点简单的文字说明。点进去一个案例之后，才是案例的具体页面。

**Comment by xuelangZF** [comment]
现在的目录看着还是特别丑！

![image](https://cloud.githubusercontent.com/assets/2769831/20837288/6b268cc6-b8de-11e6-9fc4-cfd71671aae8.png)

下面的代码区也还是没去掉啊。

**Comment by xuelangZF** [comment]
看了最新版的界面了，一个字：丑！！你找人帮你搞个好看的吧。还有下面的运行结果 TODO 区域，先去掉吧。

此外

> 案例展示的首页其实应该是一个所有案例的列表展示，可以参考 “在线课程” 的首页展示样子。对每个案例放一个不错的图片，配一点简单的文字说明。点进去一个案例之后，才是案例的具体页面。
