### ISSUE TITLE
在线上版本 传 教育资源

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#136]
利用  http://a002.nscc-gz.cn:10165/admin/ 的后台管理，在线上版本上传课时资源。

@ym13349140  负责。

**Comment by ym13349140** [comment]
收到

**Comment by ym13349140** [comment]
师兄，那个教师账号和管理员账号跟本地版一样吗？怎么好像登录不了

**Comment by xuelangZF** [comment]
服务器好像出问题了，我看看先

**Comment by xuelangZF** [comment]
周日搞定吧，我要截图呢。  @ym13349140

**Comment by xuelangZF** [comment]
这下可以上传课时资料了，对了课程说明尽量用中文的。注意有些地方尽量用 Markdown 使格式好看点。

**Comment by ym13349140** [comment]
好的，要全部自己把那几个课程说明翻译成中文吗？

**Comment by xuelangZF** [comment]
课程标题用中文，课程说明的话，可以不翻译吧，不然工作量有点大。

**Comment by ym13349140** [comment]
师兄，那个超过1M的文件还是上传不了

**Comment by ym13349140** [comment]
还有那个预览效果和最终展示出来的好像有点区别，有些效果不知道为什么展示不出来。

**Comment by xuelangZF** [comment]
超过 1 M 的文件，应该是 Nginx 的问题，我明天看看。

**Comment by xuelangZF** [comment]
修复了上传文件大小限制的 Bug： https://github.com/xuelangZF/ehpc/issues/162

**Comment by xuelangZF** [comment]
文件上传的怎么样了？

**Comment by ym13349140** [comment]
上传完了。

**Comment by ym13349140** [comment]
![Uploading image.png…]()
这里课程描述那里的两个list没有正确显示，然后后面那三个 part也没有换行

**Comment by ym13349140** [comment]
![Uploading QQ图片20161209124652.png…]()
![Uploading QQ图片20161209124613.png…]()
