### ISSUE TITLE
模板文件中的规范

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#143]
# 避免在模板中用 style 指定太多的 CSS 。

项目中很多模板文件中包含了大量的 style 内置 CSS 类型：

```
<div class="col-md-9">
    <div style="height: 83%;position: fixed;width: 53%">
        <div id="case-text" class="panel" style="height: 100%;overflow: auto;width: 100%;margin: 5px 0;padding: 10px">
            <div class="panel-heading" style="border-bottom: solid 1px #F0F0F0">
                <span data-id="title" style="font-size: 25px"></span>
            </div>
            <div class="panel-body">
                <p id="show-description"></p>
            </div>
        </div>
        <div id="editor" style="height: 100%;overflow: auto;width: 100%;margin: 5px 0"></div>
    </div>
</div>
```

这种情况应该尽量避免，要用 class 或者 id ，然后将CSS类型写在 css 文件中去。不然，代码太难维护，太难读！！！

@wzl281158150 

已有的代码先这样了，后面写的时候如果再出现很多的 style，我就不 merge 了。

**Comment by wzl281158150** [comment]
收到，有些css想要使用现有的class 但是不能完全符合要求，所以才使用style对某个属性进行修改，    对于需要修改比较多属性的使用css比较适合

**Comment by xuelangZF** [comment]
你可以将不符合要求的标记为一个class，然后给这个class指定css。

**Comment by wzl281158150** [comment]
这样的话，可能一个width属性就要写一个class？   能不能 比如 新建一个class继承panel 然后修改属性    html使用的时候 直接  使用这个class  而不用panel ？

**Comment by wzl281158150** [comment]
我只能查到这种写法
.a,.b{
    height:20px;
    width:20px;
    margin:10px 20px;
}
.a{
    color:red;
}
.b{
    color:blue;
}
但这种写法的前提是 知道属性，这样的话 我需要 修改panel  在原来的panel那里写成 
.panel .我的类 {
      ..............一堆属性
}
.我的类{
     ...............与panel不一样的属性
}
这样会修改框架的css文件，感觉不是很好

**Comment by wzl281158150** [comment]
如果直接写
.我的类{
     ....属性
}
然后class="panel 我的类"  这样子如果只有一个属性，可以直接专门为其写一个class吗？

**Comment by xuelangZF** [comment]
> 新建一个class继承panel 然后修改属性, html使用的时候 直接  使用这个class  而不用panel ？

实现你的这种目标其实不难，可以这样做：

```
<div class="panel">
    <div class="my_style"> 
    ...
     </div>
</div>
```

这样，在 my_style 中的内容就继承了 panel 的属性，同时也可以用 my_style 指定自己的属性。

**Comment by xuelangZF** [comment]
> Inheritance is the process by which some CSS properties applied to one tag are passed on to nested tags. For example, a <p> tag is always nested inside of the <body> tag, so properties applied to the <body> tag get inherited by the <p> tag. Say you created a type selector style (page 41) for the <body> tag that sets the color property to a dark red. Tags that are descendants of the <body> tag—that is, the ones inside the <body> tag—will inherit that color property. That means that any text in those tags—<h1>, <h2>, <p>, or whatever—will appear in that same dark red color.

> Inheritance works through multiple generations as well. If a tag like the <em> or <strong> tag appears inside of a <p> tag, then the <em> and the <strong> tags also inherit properties from any style applied to the <body> tag.

**Comment by wzl281158150** [comment]
这样其实跟class="panel mystyle"是一样的如果mystyle在文件中位置靠后则其优先级高   主要是这样写如果我只改一个属性的话，会出现很多class只有一个属性，要这样子写吗？

**Comment by xuelangZF** [comment]
明白你的意思啦，关键是为什么会有那么多“零散的”属性值呢？

我们之前写的基本不会出现这种情况啊。

**Comment by wzl281158150** [comment]
因为   许多东西对不齐或者不好看  我想微调一下，不然我心里不舒服……

**Comment by xuelangZF** [comment]
GET！这种情况的出现，感觉还是因为你的基础 css 属性没有设置好。因为只要设置好基础的 css class，引用的好的话，根本不会出现这种对不齐的情况啊。可否给一个具体的小例子来看看

**Comment by wzl281158150** [comment]
比如我在一个div内还有两个div有一个用的panel   可能padding left是5    另个用的其他class   padding left为0  这样启示文字就对不齐了

**Comment by wzl281158150** [comment]
起始文字

**Comment by xuelangZF** [comment]
你说的就是这种吧：

[](https://jsfiddle.net/ozw6u1kg/)

**Comment by wzl281158150** [comment]
对所以  我才用的style   当然有些 属性比较多的的确不合适

**Comment by xuelangZF** [comment]
前端样式部分可以参考 https://github.com/xuelangZF/ehpc/issues/157 中的方法。
