### ISSUE TITLE
数据库关系文档更新

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#148]
补充Wiki中关于 [Flask sqlalchemy 数据库操作文档](https://github.com/xuelangZF/ehpc/wiki/flask-sqlalchemy-%E6%95%B0%E6%8D%AE%E5%BA%93%E6%93%8D%E4%BD%9C%E6%96%87%E6%A1%A3) 的文档，包括：

* 1对1
* 1对多
* 多对多
* 多对多，加附加字段

注意要有简单的示例， 清晰的排版（用 Markdown）。

@luozhx    收到请回复一下

**Comment by luozhx** [comment]
收到

**Comment by xuelangZF** [comment]
更新后在 https://github.com/xuelangZF/ehpc/issues/102 上面记录，让其他人知道。

**Comment by xuelangZF** [comment]
却少对一些参数的讲解，下面代码中：

```
lessons = db.relationship('Lesson', backref='course', lazy='dynamic')
questions = db.relationship('Question', backref=db.backref('papers', lazy='dynamic', cascade="delete, delete-orphan"))
```

比如：

1. relationship 中的第一个字符串参数是什么意思？
2. backref 又是什么用？
3. lazy 可以有哪些值？
4. cascade 做什么用的？

可以参考 《Flask Web 开发》这本书。  @luozhx

**Comment by xuelangZF** [comment]
文档更新的不错，有疑问可以再讨论。
