### ISSUE TITLE
案例展示前端页面

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#149]
案例展示部分目前的问题：

1.  index 页面预览图都是写死的！（在数据库添加相应字段，每个案例保存一个预览图不可以吗？）
2. 案例描述部分，要显示 Markdown 渲染后的结果，不然根本没法看。
3. style 的问题，重构页面时，记得不要在模板中滥用 style 。

![2016-12-05 11 05 35](https://cloud.githubusercontent.com/assets/2769831/20872592/c720479e-bada-11e6-9f00-64a97bc1436c.png)

@wzl281158150

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
merge 完 wzl281158150 的提交后后，就提示有冲突了，你解决下冲突再pull 一个吧。

@ym13349140

**Comment by xuelangZF** [comment]
案例展示部分中，描述的内容，不要限定高度，让其作为整个页面滚动比较好。（目前整个页面是不能滚动的，只是滚动案例描述区域）。

不知道我描述的明白不？

@wzl281158150

**Comment by wzl281158150** [comment]
是说，右侧高度由内容长度确定？

**Comment by xuelangZF** [comment]
对啊，就是这个意思

**Comment by xuelangZF** [comment]
这部分做的怎么样了？

**Comment by xuelangZF** [comment]
Fixed on commit 92da0a8f573a0d1f9f8b05837668037ea97c075c
