### ISSUE TITLE
Markdown 编辑器支持拖拽上传图片

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#150]
我们目前的 Markdown 使用了 https://github.com/NextStepWebs/simplemde-markdown-editor ，默认是不支持拖拽图片上传的。然而很多时候，我们确实需要上传本地的图片在 Markdown 编辑框，Github 的编辑框就有这个功能（下面就是拖拽的）。

![1741029-e5035d2c74ba60c3](https://cloud.githubusercontent.com/assets/2769831/20880124/a875262a-bb11-11e6-843f-9998c877d32b.PNG)

**基本原理**：编辑框监听uploadFile 事件，然后js将本地文件上传到服务器上的一个指定目录，获取图片链接，之后用新的链接更新编辑器里面内容。

目前没有现成的做法，不过 simplemde 有一个 issue： https://github.com/NextStepWebs/simplemde-markdown-editor/issues/328 里面列出了相关的内容，可以参考。

该功能实现有点难度。 @wzl281158150   来完成吧。（保证代码可读性，可重用性，因为我们很多编辑框都要支持，所以尽量使改动起来容易点）

**Comment by wzl281158150** [comment]
收到

**Comment by wzl281158150** [comment]
# **markdown拖拽上传图片实现**

以templates/admin/course/edit.html 为例
该文件中已声明edt:
`var edt = new SimpleMDE({
                element: $("#course_about")[0],
                autosave: true,
                showIcons: ["code", "table"],
                tabSize: 4,
                spellChecker: false
            });`

然后我们只需为其添加drop事件:
`edt.codemirror.on('drop', function (editor, e) {
                var fileList = e.dataTransfer.files;
                if (fileList.length > 1){
                    alert('一次只能上传一张图片');
                }
                if(fileList[0].type.indexOf('image') === -1){
                    alert("不是图片！");
                    return false;
                }
                var img = new FormData();
                img.append('img', fileList[0]);
                img.append('func', 'drop-img');
                $.ajax({
                    type: "post",
                    url: "{{ url_for('admin.course_edit', course_id=course.id) }}",
                    data: img,
                    processData : false,
                    contentType : false,
                    success: function (data) {
                        if (data["status"] == "success") {
                            edt.value(edt.value() + "![](" + data['uri'] + ")");
                        }
                        else {
                            alert("上传图片失败");
                        }
                    }
                });
            });`

其中，e为event类型，使用e.dataTransfer.files[0]可获取拖入的文件，首先限制上传图片的数量以及类型，接着以FormData的形式发送文件（图片）。

在后台：
`if request.form['func'] is not None and request.form['func'] == 'drop-img':
            path = os.path.join(current_app.config['UPLOAD_FOLDER'], 'drop-img-test', 'drop-img-test.png')
            status = upload_img(request.files['img'], 200, 400, path)
            if status[0]:
                return jsonify(status='success', uri=os.path.join('/static/upload/drop-img-test', 'drop-img-test.png'))
            else:
                return jsonify(status="fail")`
使用已有的upload_img函数将图片存入指定文件夹参数为（图片, 设置高, 设置宽, 保存路径），成功后，返回图片地址给前端，前端以markdown图片对应语法插入即可

**Comment by wzl281158150** [comment]
# **markdown编辑框拖拽上传图片实现**

以templates/admin/course/edit.html 为例
该文件中已声明edt:
```javascript
var edt = new SimpleMDE({
                element: $("#course_about")[0],
                autosave: true,
                showIcons: ["code", "table"],
                tabSize: 4,
                spellChecker: false
            });
```

然后我们只需为其添加drop事件，其中，e为event类型，e.dataTransfer.files为拖入的文件列表，此处我们一次拖入一张图片，故使用e.dataTransfer.files[0]即可可获取拖入的文件，首先限制上传图片的数量以及类型，接着以FormData的形式发送文件（图片）。
```javascript
edt.codemirror.on('drop', function (editor, e) {
                var fileList = e.dataTransfer.files;
                if (fileList.length > 1){
                    alert('一次只能上传一张图片');
                }
                if(fileList[0].type.indexOf('image') === -1){
                    alert("不是图片！");
                    return false;
                }
                var img = new FormData();
                img.append('img', fileList[0]);
                img.append('func', 'drop-img');
                $.ajax({
                    type: "post",
                    url: "{{ url_for('admin.course_edit', course_id=course.id) }}",
                    data: img,
                    processData : false,
                    contentType : false,
                    success: function (data) {
                        if (data["status"] == "success") {
                            edt.value(edt.value() + "![](" + data['uri'] + ")");
                        }
                        else {
                            alert("上传图片失败");
                        }
                    }
                });
            });
```

在后台，使用已有的upload_img函数将图片存入指定文件夹参数为（图片, 设置高, 设置宽, 保存路径），成功后，返回图片地址给前端，前端以markdown图片对应语法插入即可。
```python
if request.form['func'] is not None and request.form['func'] == 'drop-img':
      path = os.path.join(current_app.config['UPLOAD_FOLDER'], 'drop-img-test', 
                                     'drop-img-test.png')
      status = upload_img(request.files['img'], 200, 400, path)
      if status[0]:
          return jsonify(status='success', uri=os.path.join('/static/upload/drop-img-test', 
                                'drop-imgtest.png'))
      else:
          return jsonify(status="fail")
```
markdown图片语法为：
`![图片替代文字](图片地址)`
@xuelangZF

**Comment by wzl281158150** [comment]
```javascript
alert('一次只能上传一张图片');
```
后应有return false;语句

**Comment by wzl281158150** [comment]
具体可绑定的事件可参考markdown文档的Event handling部分

**Comment by xuelangZF** [comment]
```
alert('一次只能上传一张图片');
```

后应有return false;语句

什么意思？

这里讨论是可以多次编辑的。

**Comment by xuelangZF** [comment]
先在案例描述部分的编辑框实现这个拖拽上传吧，搞定给一个 pull request

**Comment by wzl281158150** [comment]
alert('一次只能上传一张图片');就是，同时拖入太多图片的时候的提示，后面忘记return会导致上传继续进行
案例描述部分，后台才有编辑框吧？

**Comment by xuelangZF** [comment]
对的，等案例后台部分搞定之后，你再添加吧。

**Comment by xuelangZF** [comment]
目前，每次拖拽生成的链接都是在编辑框的最后，能不能将生成的链接放在拖拽到的光标的位置呢？

@wzl281158150  感觉有点难度，你看下可否实现吧。

**Comment by wzl281158150** [comment]
好的

**Comment by xuelangZF** [comment]
此外，你考虑下如何将这个功能尽量模块化，这样其他有 markdown 编辑框的地方都能够以**最小的改动**扩展这个功能。

比如：

1. 后台这里进行一些封装，其他 markdown 编辑框处理的后台可以简单的处理图片；
2. 前端可以将 drop事件 对应的处理语句，写成一个函数（参数是后台处理uri），这样不同的编辑框添加监听事件即可。

@wzl281158150

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
Fixed on commit 92da0a8f573a0d1f9f8b05837668037ea97c075c
