### ISSUE TITLE
静态资源避免缓存的文档

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#155]
我们项目中的 static/ 文件夹下存放的是一些资源文件，由于 HTTP 的缓存策略，这些文件一旦加载到客户端，短时间内再次发起请求会导致  304，如下例子：

```
127.0.0.1 - - [06/Dec/2016 16:29:03] "GET /static/upload/group_logo/4.jpg HTTP/1.1" 304 -
127.0.0.1 - - [06/Dec/2016 16:29:03] "GET /static/upload/group_logo/3.jpg HTTP/1.1" 304 -
127.0.0.1 - - [06/Dec/2016 16:29:03] "GET /static/upload/group_logo/5.jpg HTTP/1.1" 304 -
127.0.0.1 - - [06/Dec/2016 16:29:03] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 -
```

有时候我们更新了一个静态资源，想要客户端看到更新后的结果，如何做呢？

其实如果看一些网站的源码的话，会发现很多静态资源 URI 后面其实会跟一个 `?version=2.0` 的字段。这样每次更新完一个版本，更新查询字段中版本后，就会返回新的文件。

不过这并不适用于某些场景，比如用户更新头像后，希望立马看到新的头像等。这时候一般的做法是： 

[Is there a way to force browsers to refresh/download images?](http://stackoverflow.com/questions/1431512/is-there-a-way-to-force-browsers-to-refresh-download-images)  

麻烦 @luozhx  更新文档：[静态资源避免缓存](https://github.com/xuelangZF/ehpc/wiki/%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E9%81%BF%E5%85%8D%E7%BC%93%E5%AD%98)，大概说明下缓存机制的原理，并且详细说明项目中那些需要更新后立即显示的uri该如何处理。（头像上传已经实现了，可以参考其中的代码）

明白不？

关于缓存机制，《HTTP 权威指南》第7章写的非常清楚，可以读一下。

**Comment by luozhx** [comment]
收到
