### ISSUE TITLE
前端样式速成指导

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#157]
前端 CSS 样式自己写起来很麻烦，但是好在有太多现成的 CSS 文件我们可以拿来用。

比如说，现在你有一个文字描述区域，是markdown 渲染后台数据库数据的结果，现在你想让这个区域内的文字样式好看点。那么问题来了，怎么写 CSS 呢？

一个方法是去找 Github 自身对markdown样式的CSS文件，这个不难找到。不过还有一个更好的方法，从我们站点自身下手，其实我们话题内容就支持漂亮显示 markdown 渲染后的结果，那么话题内容用到了哪些CSS 呢？查源码！

![image](https://cloud.githubusercontent.com/assets/2769831/20924102/b7af078a-bbea-11e6-8a93-07cdfaeaef71.png)

可以看到用了 `class="markdown-body" ` 来指定CSS样式的，在 main.css 文件里面，有该class下面各个元素的具体样式（没错，就是用的 Github 的 Markdown 样式）。

那么完全可以在用 markdown 渲染的区域加上一个 `<div class="markdown-body"> `，这样所有样式都有了。当然，这样方便的class在main.css 中还有很多的。

使用诀窍就是在项目中找到和你想要的展示结果差不多的区域，然后查看它的css 实现，然后用它的class来写自己的代码。

@wzl281158150 没错，你现在可以更改案例展示中案例描述部分的样式了。

**Comment by wzl281158150** [comment]
收到
