### ISSUE TITLE
上传多文件组件的优化

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#159]
目前后台中上传文件（ https://github.com/xuelangZF/ehpc/issues/92 ）是用的 Plupload 插件， ym13349140  采用了一种取巧的做法，点击上传文件，然后弹出了一个框，在里面进行选文件，上传文件的操作。不过还是感觉这样不太”正规“，既然做了这个功能，我们就尽量把他做好点。

目前大平台（seafile 或者 百度云盘）的做法都是点击上传后，会直接弹出文件选择框，选择多个文件后，会有 modal 显示上传进度，这样操作方便很多。Plupload 也给了一个类似的例子，在 http://jsfiddle.net/gh/get/jquery/1.9.1/jayarjo/plupload-demos/tree/master/2.x/core/bundled 可以看到，只不过进度显示的有点粗糙，ui 没那么好。

@luozhx  和 @ym13349140 你们两个试一下，看能不能按照这种方式实现。

如果实在不行的话，我觉得可以将目前  ym13349140 做法中的那个现成的框放到一个 modal 中，每次上传完关闭这个modal。 七牛云是这样做的，效果也还不错。

**Comment by ym13349140** [comment]
收到

**Comment by luozhx** [comment]
收到

**Comment by xuelangZF** [comment]
进度怎么样了啊？

**Comment by luozhx** [comment]
我这边可能没这么快，我还在研究jQuery-File-Upload 插件

**Comment by xuelangZF** [comment]
好的，继续哈！

**Comment by xuelangZF** [comment]
课时管理中刚点上传文件，就会在右下角出现那个上传文件状态的栏目。

<img width="617" alt="2016-12-14 8 43 56" src="https://cloud.githubusercontent.com/assets/2769831/21165364/e2803002-c1d9-11e6-8701-810e1e19f4b4.png">

应该是选中文件后，点“打开”，开始上传后才出现的。

**Comment by luozhx** [comment]
已经修改

**Comment by xuelangZF** [comment]
提交 a0f046d93a41f5bbf8d836061e1cd5654ff1b0e3 修复。
