### ISSUE TITLE
管理后台：编辑案例信息后不能提交

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#161]
编辑案例信息后，并不能提交，form 表单的提交处理还是有问题。我修复了一点，但是没修复完。@ym13349140 修复。

保证提交成功后，返回到案例管理的首页。提交失败时，给出适当的提示。

**Comment by ym13349140** [comment]
师兄，我看到你那边你修改前的case.js文件好像跟我这边的不一样，我这边是可以提交成功和显示信息的，好像是后面的那次提交把我之前的修改给删除了，我再重新交一次吧

**Comment by xuelangZF** [comment]
嗯，你把 case.js 修复一下。

**Comment by xuelangZF** [comment]
Fixed on commit 63653ebbe6b4a24d1b3d7f5a219f4895baaa3e60
