### ISSUE TITLE
jQuery 优化建议

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#165]
jQuery 开发时，几个优化的建议

1. 使用合适的选择器

    > 尽量使用 ID 选择器
    > 尽量给选择器指定上下文

2. 缓存对象

    可以使用链式操作的话使用链式，或者使用变量缓存。 永远不要让相同的选择器在代码里出现多次。

3. 事件代理

    假设有 100 个 td 元素，如果你绑定 100 个事件，那么将带来很大的负面性能影响。代替这种效率很差的多元素事件监听的方法就是：向它们的父节点绑定一次事件，然后通过 event.target 获取到点击的当前元素。

《锋利的 jQuery》 第 11 章有更加详细齐全的说明，强烈建议读一下。然后，重构之前的代码。

下面是一些不错的文章，提到了一些中肯的建议：

[编写更好的jQuery代码的建议](http://blog.jobbole.com/52770/)   
[给JavaScript初学者的24条最佳实践](http://blog.jobbole.com/53199/)  

@ym13349140 @wzl281158150 @luozhx

**Comment by wzl281158150** [comment]
收到
