### ISSUE TITLE
并行程序参数配置

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#166]
并行程序和超算那边对接，商量用户可以配置的参数。

在线编程代码提交页旁边提供`参数配置`选项，弹出 modal，供用户选择参数。 （注意参数以下拉框形式给出，这样可以避免对参数合法验证等繁琐问题）

@milanlanlan

**Comment by xuelangZF** [comment]
这里语言的选择，放在原来的位置，不要放进 `参数配置`  里面，因为编辑框需要根据选择的程序语言来决定高亮方案。

其他的参数，不要直接放在题目页面中。我们会有一系列默认的参数，如果用户不选择参数的话，就用这套参数来编译程序。如果要自定义参数的话，才通过页面的 “参数配置” 按钮进入到配置的 modal 页面，进行相应的配置。

再次强调下，`参数配置` 按钮可以放在 `提交代码` 按钮旁边。

你的提交前端页面太简陋了，我就 revert 了。你尽快写好一个可用的提交吧。

**Comment by milanlanlan** [comment]
如果跳转的话，一个页面只有三个参数会不会显得有点空泛。
另外我想问后台功能没问题了吗？我的本意是先解决api的问题，再慢慢写前端

**Comment by xuelangZF** [comment]
首先不会跳转的，直接弹出 modal 选参数，其次，你确定最后只需要 3 个 参数吗？

后台功能我还没来得及仔细测试，不过刚才肯定没有连接上超算。

**Comment by milanlanlan** [comment]
没有连接上超算是什么情况？返回的是什么结果呢？我觉得功能应该先解决吧，前端不是什么大问题。你觉得呢

**Comment by xuelangZF** [comment]
嗯，主要功能肯定是要先解决的。刚才随便提交了一个小程序，然后前端是返回无法提交稍后重试，后台也没有反馈信息。

你后台设计时，应该在控制台打印一些log信息，这样我们可以快速定位问题。现在你可以自己连接上我给你的账户，去测试下程序。

至于前端，显然也没有你想的那么容易，还是要好好去写的。

**Comment by milanlanlan** [comment]
我测试的时候是直接`python code_process.py`，也有提示信息，不过可能提交之前注释掉了，而且我测试了demo也会显示正常结果。或者麻烦师兄试一下`python code process.py`?
不过由于超算那边还有问题，有时返回的是预料之外的结果，可能他那边还在调试吧。

**Comment by milanlanlan** [comment]
我再看看吧，之后再提交一个版本。

**Comment by xuelangZF** [comment]
我运行了下，结果如下：

```shell
jump to async
jump to async
Request fail.
jump to async
Request fail.
AAA
(ehpc) netlab513@ubuntu:~/ehpc/eHPC/problem$ python code_process.py
jump to async
jump to async
jump to async
Compile success.
AAA
```

**Comment by xuelangZF** [comment]
目前可以运行并行程序了吗？能否给我一个简单的并行程序来测试下呢？

**Comment by milanlanlan** [comment]
request fail和运行结果变成字符串确实是出现过的问题，可能再运行又会变成正常结果，我试过同一段代码得到了三个不同的结果，我还是再跟那边沟通下看是什么问题，下次提交连同mpicc的demo程序一起提交吧

**Comment by xuelangZF** [comment]
好的

**Comment by xuelangZF** [comment]
这里代码编辑框是支持高亮的，在 main.js 里面会监听 id=language的change 事件：

```js
$("#language").on('change', function () {
    var e = document.getElementById("language");
    var code_mode = e.options[e.selectedIndex].value;
    var editor = ace.edit("editor");
    editor.getSession().setMode(code_mode);
});
```

所以我们模板中 select 中才会有 id 属性。select 中提供的是可用的编程语言，我不清楚你为什么要把它改成 `mpicc`。就算 mpicc 也是一种语言，你直接加一个 option 就可以了，为啥要删除其他语言，单独再加一个呢？

```python
-                    <select class="form-control" id="language">
 -                        <option value="ace/mode/c_cpp">C</option>
 -                        <option value="ace/mode/c_cpp">C++</option>
 -                        <option value="ace/mode/python">Python</option>
 -                        <option value="ace/mode/fortran">Fortran</option>
 -                    </select>
 +					<div class="row">
 +						<label class="col-md-3" for="language">语言</label>
 +						<select class="col-md-4" name="language" id="language">
 +							<option value="mpicc">mpicc</option>
 +						</select>
 +					</div>
```

@milanlanlan

**Comment by xuelangZF** [comment]
语言这块，不要删，目前只用保证选 C++ 没错就行，其他出错先不管吧。另外，既然 mpicc 不是语言，就不要在语言选项里面加 mpicc 。

**Comment by xuelangZF** [comment]
至于提交完一个C并行（后面可能有fortan，python等）的代码，如何并行编译，可以通过提供并行参数来配置。

前端的那个语言选项只是用来高亮代码，和提供编辑框的，它本身不参与编译、运行参数。所有的参数需要在modal 里面选定，比如选定编译器 mpicc，核数等。

**Comment by xuelangZF** [comment]
你本地有跑过吗？我这里是这种效果的：

![2016-12-23 3 39 05](https://cloud.githubusercontent.com/assets/2769831/21449233/0879ac40-c926-11e6-81e6-c70aa25ecdaf.png)

这是因为 你的` div 标签`没有正确的 `闭合`。如果你用 pycharm 的话，代码格式化很容易找出没有闭合的标签，这样就不会出现这样明显的错误。

BTW， program_detail.html 继承了 base.html，里面很多 js 和 css 已经引用了，不需要在下面继续引用。

```
 -    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
 +	<link rel="stylesheet" href="https://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
 +	<script src="https://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
 +	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
```

前端这块你多请教下 @ym13349140 和 @wzl281158150  @luozhx  他们，感觉缺的知识挺多。

**Comment by milanlanlan** [comment]
好的

**Comment by xuelangZF** [comment]
已经修复了上面的问题，真心希望你下次不要这么仓促地提交。

**Comment by xuelangZF** [comment]
请问后台你本地测试过吗？

我运行了本地的 test ，结果如下：

```shell
$ python eHPC/problem/code_process.py
Traceback (most recent call last):
  File "eHPC/problem/code_process.py", line 216, in <module>
    if not mc.login():
  File "eHPC/problem/code_process.py", line 126, in login
    tmpdata = self.open(login_url, data=self.login_data, login=False)
  File "eHPC/problem/code_process.py", line 70, in open
    rdata_reg = re.search( '\{.+\}', rdata)
NameError: global name 're' is not defined
```

你的 code_process 没有引入 re 模块，根本就没法跑！这样的代码你就提交了？

PS，我加了  re 模块，然后又是这样的：

```shell
python eHPC/problem/code_process.py
jump to async
async retry
async retry
async retry
async retry
async retry
Error: async connection time out.
upload fail.
jump to async
async retry
async retry
async retry
async retry
async retry
Error: async connection time out.
Traceback (most recent call last):
  File "eHPC/problem/code_process.py", line 221, in <module>
    compile_out = mc.ehpc_compile( path, input_filename, output_filename, "mpicc")
  File "eHPC/problem/code_process.py", line 188, in ehpc_compile
    compile_output = self.run_command(commands)
  File "eHPC/problem/code_process.py", line 168, in run_command
    return tmpdata["output"]["error"]
TypeError: string indices must be integers
```

不知道是怎么回事？  @milanlanlan  请认真对待每次 pull request。不是第一次出现这种问题了，你要反思下。

**Comment by milanlanlan** [comment]
我跑过然后截图给你了啊，我看看为什么会出现这个问题

**Comment by milanlanlan** [comment]
我大概明白了，在你revert之后我重新pull把我的修改覆盖掉了，re模块和前端页面其实之前我已经改过了。我重新看看哪里被覆盖了吧。

**Comment by xuelangZF** [comment]
你的 submit 里面其实也是有问题的：

<img width="845" alt="2016-12-23 5 17 47" src="https://cloud.githubusercontent.com/assets/2769831/21450644/c0a72524-c933-11e6-8a85-46c6784a3b78.png">

此外，你 Ajax 提交代码时，要**同时提交配置的参数**，然后才能再后台获取：

```python
	task_number = request.form['task_number']
	#task_number = "4"
	cpu_number_per_task = request.form['cpu_number_per_task']
	#cpu_number_per_task = "1"
	node_number = request.form['node_number']
```

这块你可以在本地就测试的，你用浏览器检查工具，查看 post 请求中是否正确地携带了那些字段。目前你的 post 请求是不成功的：

<img width="822" alt="2016-12-23 5 20 31" src="https://cloud.githubusercontent.com/assets/2769831/21450708/2cc09290-c934-11e6-8b51-d68960ffa5dd.png">

**Comment by xuelangZF** [comment]
Ajax 操作我们有文档： https://github.com/xuelangZF/ehpc/wiki/Ajax-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3  。

**Comment by milanlanlan** [comment]
```
$("input[name=compiler]").val($("#compiler").find("option:selected").text());
$("input[name=task_number]").val($("#task_number").find("option:selected").text());
$("input[name=cpu_number_per_task]").val($("#cpu_number_per_task").find("option:selected").text());
$("input[name=node_number]").val($("#node_number").find("option:selected").text());
```
不是这样配置的吗？我是用compiler代替了原来的language参数

**Comment by milanlanlan** [comment]
我看看文档吧

**Comment by xuelangZF** [comment]
给你说了你的 submit 视图函数有问题！你为什么就看不见呢？pycharm 那么明显的`红色下划线高亮`，你就忽视了？

<img width="435" alt="2016-12-24 9 56 00" src="https://cloud.githubusercontent.com/assets/2769831/21464664/31d91e9c-c9bf-11e6-909a-f150a05471c3.png">

虽然是很小的问题。

希望你真的能看进去我写的内容，前面我写的你都没有给我正面反馈，我不知道你有没有认真去看。

PS：换位思考下，如果别人给你提交的代码如果连语法都过不去，你怎么想？  这么个小功能，咱俩在这里讨论了这么多，沟通的成本已经不小了。

@milanlanlan

**Comment by xuelangZF** [comment]
还有我不知道你有没有用 pycharm，麻烦下次提交前，用你的编辑器将代码中Tab 切换为 4个空格。这样可以保持在不同编辑器打开，缩进都是对的。

还有，模板文件请保证 正确的缩进！

**Comment by xuelangZF** [comment]
> 我这边不能完整测试，也没用pycharm，所以这个功能一直出问题，之前result没出问题，因为没改动我想当然这里不会出问题了，确实没注意到，编辑器我用的是vim，缩进确实是4个空格

- 不能完整测试－－>你可以只把试题那个模块在服务器跑起来，这样你的部分就能测试了。
- 也没用pycharm －－> 你可以用啊，没人不让你用吧
- 缩进确实是4个空格－－> vim 可以配置将 Tab 转换为 4个空格，但你的肯定没有转换，因为我这里pycharm显示你的还是 Tab。

> 以前这些错误我都是靠着测试debug的，现在有点不习惯！

首先一些明显的语法错误，并不用靠 debug 的吧，编辑器语法高亮就能告诉。其次，好多功能逻辑，也不需要debug 就要想好，下面的代码：

```python
   if not is_success:
        print "login fail."

    is_success = client.upload(path, input_filename, source_code)
    if not is_success:
        print "upload fail."
```

既然都**认证失败了，还要上传**？ 功能逻辑考虑清楚了吗？你的代码还没到 debug 那一步呢！

> 我自己这边跑不通流程我也没想出太好的办法，还有就是git我不是很熟练，这个我努力

跑不通流程，我给了你服务器帐户，自己把你那一部分环境搭起来不就行了？
