### ISSUE TITLE
Form 表单 Ajax 提交， Ajax 动态显示内容。

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#167]
阅读相关代码，参考 《锋利的 jQuery》，《JavaScript DOM编程艺术》提供 [Ajax 相关文档](https://github.com/xuelangZF/ehpc/wiki/Ajax-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)，主要包括：

1. 什么是 Ajax？
2. jQuery Ajax 接口介绍
3. 表单传 Ajax 数据： Ajax 动态提交表单的一般流程；
4. Ajax 动态显示内容

@SYSU-Zouzhp

**Comment by SYSU-Zouzhp** [comment]
ok~

**Comment by xuelangZF** [comment]
还没开始写吗？ @SYSU-Zouzhp

**Comment by SYSU-Zouzhp** [comment]
@xuelangZF  明天上午应该可以写完

**Comment by xuelangZF** [comment]
好的，为啥不直接在 Wiki 上写啊。话说，明天上午不是开会吗

**Comment by xuelangZF** [comment]
建议：文档中引用外部资源时，最好使用一手资料。比如 jQuery.ajax() ，就给出 官方文档 的链接： http://api.jquery.com/jquery.ajax/ 。

**二手**资料永远不要作为参考资料。

**Comment by xuelangZF** [comment]
$.ajax 中 data 参数作为给后台传递数据的入口，相当重要，表单中的数据除了用 serialize() 全部传给后台，还可以用其他方式吗？

如何传递一些不在表单中的数据，比如 js 生成的一些数据？

**Comment by SYSU-Zouzhp** [comment]
收到
