### ISSUE TITLE
Markdown 前端渲染，拖拽上传图片。

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#168]
**前端渲染 Markdown**

目前我们的 Markdown 文本是在后台用 Python misaka 渲染后给前台。但是发现渲染效果不是很好，和我们后台 Markdown 编辑框自带的 markdown 解析效果不一致。所以考虑使用 simplemde-markdown-editor 来在前端渲染 Markdown 文件，这样保持一致。

**拖拽上传图片**

进一步对拖拽上传进行封装，这样能够最小的改动，使以前 Markdown 编辑框全部支持拖拽上传。

一个建议：

模板文件中提供一个 `id=markdown-edit-area` 的钩子，并且将文件上传的后台处理链接放进 `data-post-to` 属性（data-post-to 可以有默认值），然后只用引用 `markdown_upload_img.js` 文件即可。在该文件内，使用下面的代码 

```
var simplemde = ...;
var post_to = ...;
simplemde.codemirror.on('drop', function (editor, e) {
        upload_img(editor, e, post_to);
    });
```

这样做以后，我们只需要在原来模板文件中的 Markdown 编辑框元素中添加  id=markdown-edit-area 和 data-post-to 即可。

不知道我讲的明白吗？欢迎讨论。

**Comment by wzl281158150** [comment]
收到，明白了

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/pull/169 建议：
 
`eHPC/static/case/.gitignore`   其实是为了保证我们的仓库中只保留有 `eHPC/static/case` 这个文件夹，不跟踪里面的文件。避免每次对 这个文件夹下内容进行更改，所以不要删除这个。

还有你需要让**站点的所有 markdown 编辑框全部支持图片拖拽**的，因为你对这个比较清楚，所以效率会高一点。如果每个人改自己模块的话，会慢很多。

**Comment by wzl281158150** [comment]
师兄，请问是所有的markdown都要支持吗？ 好像有一些不需要上传图片的功能。

**Comment by xuelangZF** [comment]
哪些不需要传图片？

**Comment by wzl281158150** [comment]
例如问答题答题框等

**Comment by xuelangZF** [comment]
问答题答题框其实也可能需要的。
都加上吧，这些不太需要的，后台可以搞一个统一的接口，来存储这些编辑框传的图片。

**Comment by wzl281158150** [comment]
好的

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/pull/173 问题：

```
status, uri = receive_img(path, '/static/upload/markdown/images', request.files['img'], 0.33, 0.33) 
```

这里图片上传路径写死了，需要改为写进配置文件。（图片缩放的话，可以先判断一下图片大小，如果太大的话则按比例将宽度控制在一定大小，否则直接保存）

还有 `eHPC/static/case/.gitignore` 其实是为了保证我们的仓库中只保留有 eHPC/static/case 这个文件夹，不跟踪里面的代码版本文件。避免每次对 这个文件夹下内容进行更改，所以**不要删除这个**。

**Comment by xuelangZF** [comment]
eHPC/static/case/.gitignore 其实是为了保证我们的仓库中只保留有 eHPC/static/case 这个文件夹，不跟踪里面的代码版本文件。避免每次对 这个文件夹下内容进行更改，所以不要删除这个。

修改所有问题后，和当前master保持同步，然后再 pull request 。 @wzl281158150

**Comment by wzl281158150** [comment]
收到
