### ISSUE TITLE
后台：实验室部分，添加材料和任务时modal闪退。

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#175]
http://127.0.0.1:5000/admin/lab/1/create/ 在后台，添加某一个任务时，材料和题目的 modal 闪退。

@luozhx

**Comment by luozhx** [comment]
bootstrap.min.js 重复引用导致闪退，已经修复

**Comment by xuelangZF** [comment]
提交 a0f046d93a41f5bbf8d836061e1cd5654ff1b0e3 修复了此问题。
