### ISSUE TITLE
讨论贴：如何管理拖拽上传的图片

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#178]
Markdown 编辑框目前支持拖拽上传图片，目前只要拖拽图片到编辑框，就会将图片存储在服务器的指定目录。

存在的问题：

1. 如果拖拽图片后，又删除了生成的图片引用 `![](...)`，此时后台的图片并没有被删除
2. 如果重新编辑 Markdown，可能不再使用之前引用的图片。

这两种情况，本质都是前端不再需要某些图片，但是后台并不知道，因此存储了多余的图片。

Github 目前貌似并没有理会这个问题。想不到有什么好的方法来解决这个问题。

**Comment by wzl281158150** [comment]
可以在发送   markdown内容的时候再发送一份到指定视图函数，判断是否删除的图片引用，如果删除则删除对应图片

**Comment by wzl281158150** [comment]
当然判断时需要原内容做比较，看删除了那些引用

**Comment by xuelangZF** [comment]
只这样其实还不是很完美，因为有可能有多个Markdown编辑框中引用了同一个图片。

难不成需要加一个 *引用计数*，统计有多少地方引用了这张图片，每次删除一次引用，就减少计数。

这样复杂度会高出不少，不太值。

**Comment by wzl281158150** [comment]
一般不会有这个情况，因为很少会自己输入图片地址和名字来引用

**Comment by xuelangZF** [comment]
嗯嗯，这倒是，毕竟很难找图片的地址和名字的。
