### ISSUE TITLE
更新 Markdown 编辑器 文档

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#184]
Markdown 编辑器文档相关内容，包括拖拽上传图片的具体操作。

@wzl281158150

**Comment by wzl281158150** [comment]
师兄，改好了
https://github.com/xuelangZF/ehpc/pull/160

**Comment by xuelangZF** [comment]
放到 Wiki 中： https://github.com/xuelangZF/ehpc/wiki/Markdown-%E7%BC%96%E8%BE%91%E5%99%A8

**Comment by SYSU-Zouzhp** [comment]
收到

**Comment by xuelangZF** [comment]
@SYSU-Zouzhp  今天搞得定吗

**Comment by xuelangZF** [comment]
@SYSU-Zouzhp  

考虑下面的几个问题：

1. markdown_upload_img 如何知道当前页面哪个地方是 Markdown 编辑框？（ text-area 需要指定什么 id 吗）
2. 数据库后台存放的 markdown 原文（比如 topic），但是在前端页面显示的缺失markdown 渲染后的内容。这是怎么完成的？（ @wzl281158150  实现的，搞不明白可以问他）

思考清楚这两个问题后，再更新文档。

此外，麻烦根据当前的 model.py 更新我们的数据库 E-R 设计图。

**Comment by SYSU-Zouzhp** [comment]
OK~

**Comment by SYSU-Zouzhp** [comment]
已经按要求完成重新更新文档~

**Comment by xuelangZF** [comment]
清晰明了，言简意赅！很不错！
