### ISSUE TITLE
前端代码风格

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#185]
# 不要到处用 style。

学会用 css class 来指定属性，并且将整个页面划分区域，每个区域用 css class 来指定样式。

避免下面这种情况的出现（上传进度的显示）。

**material.html**

```html
<div id="upload-status" style="display: none;width: 600px;top: auto;bottom: 0px;left: auto;right: 30px; visibility: visible;z-index: 42;position: absolute;overflow: hidden;">
...
```

**case_code_material.html**

```
<div id="upload-status" style="display: none;width: 600px;top: auto;bottom: 0px;left: auto;right: 30px; visibility: visible;z-index: 42;position: absolute;overflow: hidden;">
```

重复的 CSS style 。代码显的臃肿。

正确的做法直接在 css 文件中指定这个进度框的样式，以后需要进度框的地方，直接应用样式。

@luozhx 

https://github.com/xuelangZF/ehpc/issues/143  中已经讨论过这个问题！

**Comment by luozhx** [comment]
明白
