### ISSUE TITLE
dropzone 过滤不符合要求的文件类型

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#186]
目前用 Dropzone 上传文件时，是在后台用 flask 判断接收到的文件的类型。Flask 底层 [werkzeug 使用python 的 mimetypes 模块来做类型检测](https://github.com/pallets/werkzeug/blob/02f5784afce7779450f8f6be7c083dab5670ca68/werkzeug/datastructures.py)，核心代码如下：

```
if filename and content_type is None:
    content_type = mimetypes.guess_type(filename)[0] or 'application/octet-stream'
    value = FileStorage(file, filename, name, content_type)
```

但是感觉这里面有问题。比如对于 `demo.cpp` 文件来说，直接用 mimetypes 来检测的话，是 

```shell
$ mimetypes.guess_type('a.cpp')[0]
'text/x-c'
```

但是我在上传 cpp 文件到我们的站点时候，发现 flask 解析出来的类型是  `application/octet-stream`. @ym13349140 的后台上传解析出来的估计是 `text/x-c++src`。

所以这种方法不可靠。对于代码或者课时资源的提交，改为在前端用 dropzone 进行过滤（刚好 dropzone 也有这个参数）。后台不再过滤文件类型，避免错误的判断类型（注意修改后台相关函数，去掉类型检测的部分，已经配置文件中的允许的文件类型）。

@luozhx Your job!

**Comment by luozhx** [comment]
text/x-c++src是我在测试上传时添加的，我测试了c，cpp和py，都和原来不一样。

**Comment by xuelangZF** [comment]
所以在前端检测吧，后台的mimetype 怪怪的。

**Comment by xuelangZF** [comment]
提交 96dd6ac32781e94406b6246e2979ea92c6fabdf3 解决问题
