### ISSUE TITLE
前端渲染 Markdown

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#187]
目前我们的 Markdown 文本是在后台用 Python misaka 渲染后给前台。但是发现渲染效果不是很好，和我们后台 Markdown 编辑框自带的 markdown 解析效果不一致。

所以考虑使用 simplemde-markdown-editor 在前端渲染 Markdown 文件，这样可以保持预览的效果和最后显示的效果保持一致。

请考虑一种合适的方法，方便改动所有需要 markdown render的页面。

@wzl281158150  差一点忘了这个任务了。

**Comment by wzl281158150** [comment]
师兄你是说不用markdown过滤器？

**Comment by xuelangZF** [comment]
对，不用 markdown filter，然后前端用 simplemde-markdown-editor  中的 js 代码来 render  markdown  语句。

**Comment by xuelangZF** [comment]
Commit 257e49c47e0dfb8d89f968a732b45aa99658b711 完成
