### ISSUE TITLE
Markdown 编辑框支持 Latex 编辑公式

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#188]
考虑如何在编辑框中支持用 Latex 编辑公式。

许多Markdown 编辑器都是支持的，比如 Mweb。

mathjax 是一个 js 渲染Latex 的标准库，应该可以集成进 simpleMDE

**Comment by xuelangZF** [comment]
@wzl281158150  考虑在 Markdwon 中支持 Latex 数学公式。

比如：  
```
$\theta$
```

$\theta$

**Comment by wzl281158150** [comment]
收到.

**Comment by xuelangZF** [comment]
Flask Jinja 避免render方法： http://jinja.pocoo.org/docs/dev/templates/#escaping

```
{% raw %}
    <ul>
    {% for item in seq %}
        <li>{{ item }}</li>
    {% endfor %}
    </ul>
{% endraw %}
```

最好是可以在 Markdown 编辑器预览中看到公式编辑效果。

**Comment by xuelangZF** [comment]
怎么样了，今晚前能不能pull 一份

**Comment by xuelangZF** [comment]
求pull request，我看看 Latex 的效果如何。  @wzl281158150

**Comment by xuelangZF** [comment]
提交 ceaf43224f958dd4f5c177b2d1a35a82abaf6189  初步完成。

**Comment by xuelangZF** [comment]
有的前端页面markdown 渲染时，没有渲染 Latex 啊。

![image](https://cloud.githubusercontent.com/assets/2769831/21756764/73857860-d660-11e6-90ff-62a5a96d7a5a.png)

**Comment by xuelangZF** [comment]
@ym13349140  在获取课程作业时，是通过 ajax 发送 post 请求，可能你改的渲染的地方不对。

![image](https://cloud.githubusercontent.com/assets/2769831/21757056/41edc83a-d664-11e6-8155-cc877ffdce0b.png)

**Comment by xuelangZF** [comment]
提交 cd8186a80a15fba689869ba9c12a80eb8f1ac910 完成
