### ISSUE TITLE
虚拟实验室如何快速引用题库中的题目

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#195]
目前虚拟实验室在引用题库题目时，弹出的 modal 不便于筛选题目：

![2016-12-18 9 06 56](https://cloud.githubusercontent.com/assets/2769831/21293652/085db9a4-c566-11e6-8d5b-315ae1f14f9c.png)

第一列序号根本没有意义，因为不知道你需要的题目所在的序号。

目前考虑可以将题目的分类加到列表中去，这样可以按照分类快速的筛选。（在往题库添加题目的时候，就可以用分类来区分不同虚拟实验室的题目。）

不知道还有什么好的方案来快速找到需要的题目没？

@wzl281158150  @luozhx

**Comment by luozhx** [comment]
可以加一个题目类型

**Comment by xuelangZF** [comment]
题目类型我们有的，只要在 modal 里面显示，就会好很多的。

**Comment by xuelangZF** [comment]
@ym13349140  修复这个问题。

**Comment by xuelangZF** [comment]
题库中，目前题目有一个 “知识点” 的属性（classify 实体），将其看作是 “分类”。

每次创建题目时候，允许使用 “**复选下拉框**” 选择题目所属的分类，（目前的多选框不太合适）

![a](https://cloud.githubusercontent.com/assets/2769831/21298654/bcf3c2f6-c5ce-11e6-8f6f-e3befe8cc3e8.png)

此外，还要支持管理员对题目分类进行管理（新建分类，删除分类，重命名分类的名字）。

@wzl281158150  完成

**Comment by wzl281158150** [comment]
使用下拉框的话，题目只能属于一类   而数据库中的样例题目之前的选择题部分，题目都至少为2类

**Comment by xuelangZF** [comment]
下拉框可以选择多个的。

**Comment by xuelangZF** [comment]
设计问题：

1.  **题目分类**的管理放在 教师权限中，和题目管理放在一个页面；
2.  虚拟实验室引用题目时，弹出 modal 中可以根据**题目分类**来筛选题目。不是根据题目类型来选择。

明显的程序问题：

1. 虚拟实验室编辑时 Markdown 编辑框没有了

![2016-12-22 2 28 55](https://cloud.githubusercontent.com/assets/2769831/21417094/0c140c34-c853-11e6-820c-c0d64718f77b.png)

2. 虚拟实验室中小任务选择题目时，弹出的modal 根本无法选择题目：

![2016-12-22 2 30 00](https://cloud.githubusercontent.com/assets/2769831/21417112/368e76ac-c853-11e6-9b26-b53aa16d9cfd.png)

**Comment by xuelangZF** [comment]
Pull request 已经 revert！

**Comment by wzl281158150** [comment]
师兄，我这边的版本都是正常的，是不是你那边版本有问题

**Comment by wzl281158150** [comment]
![qq 20161222162836](https://cloud.githubusercontent.com/assets/22830541/21419616/b123c8a8-c863-11e6-9e6f-8b5b3ddf3a85.png)

**Comment by wzl281158150** [comment]
其次是，由于一道题目有多种分类，在此处不适合使用分类来筛选，放在系统管理页面中是为了不让一位老师拥有所有的知识点管理权限

**Comment by xuelangZF** [comment]
那应该是我 merge 冲突的时候，把代码打乱了，导致 modal 的问题。你在本地解决下冲突吧。

管理题库的分类本来就不是系统管理员的任务，难道老师后台添加一个题目，没有新的分类还需要联系管理员再开一个分类？逻辑上讲，题库管理和题目的分类管理本来就应该是在一起的。不知道你为什么觉得让一个老师管理所有的知识点不合适？

还有，为什么题目有多种分类，就不适合用分类来筛选呢？不明白你的依据。

（PS：如果对任务中的实现细节有疑问的话，最好是在动手做之前和我商量下。这样直接按照自己的理解来做的话，可能会做无用功的。）

@wzl281158150

**Comment by wzl281158150** [comment]
一道题目有多种分类，要把所有的分类都插进第一列吗？...

**Comment by wzl281158150** [comment]
如果第一个老师创建一个分类，被第二个老师删除怎么办?.....

**Comment by xuelangZF** [comment]
第一列用 `，`号隔开所有的分类，这样做没有什么问题的吧。

如果考虑这种 “误操作的” 话，那如果一个老师的题目，课件被另一个老师删除怎么办？我们目前关于后台教师权限管理这块做的确实很有问题，任意一个教师账户都能操作所有资源。后期这块可能要有大的改动，现在就先这样吧。

**Comment by wzl281158150** [comment]
......行吧，就按师兄你说的来吧。。

**Comment by xuelangZF** [comment]
不是，你要有什么意见可以说啊

**Comment by wzl281158150** [comment]
我先写吧，看看效果再说

**Comment by xuelangZF** [comment]
好啊，遇到问题来讨论就行。

**Comment by wzl281158150** [comment]
改好了，师兄......

**Comment by wzl281158150** [comment]
pull request已提交

**Comment by xuelangZF** [comment]
OK，我觉得这样可以了，小任务中添加题目时，可以通过 “分类” 快速筛选出相关的题目了。
