### ISSUE TITLE
一些细节问题

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#196]
1. 注意页面上栏目的命名，力求做到让人一眼就看明白。

![2016-12-18 9 11 40](https://cloud.githubusercontent.com/assets/2769831/21293670/9aec673e-c566-11e6-8974-ebbc57dc2156.png)

这里题目的 “名称” 字段是什么？  很容易让人误解，如果改为 “题干” 则清晰明了很多。

2. 页面的 title，注意我们的每个页面都是有一个 `<title>` 标签的，base 模板中指定了:

```
<title>
    {% block title %}{% if title %}{{ title }}{% endif %}-{{ _('eHPC') }}{% endblock %}
</title>
```

所以每个模板都要有一个合适的 title 参数传递进去，这样浏览器标签页的上面就可以显示出对应的 title ，而不是像下面这样，显示不完整的 title：

![2016-12-18 9 14 33](https://cloud.githubusercontent.com/assets/2769831/21293695/0b291aa6-c567-11e6-8538-98ed680b115a.png)

@milanlanlan  @ym13349140 @wzl281158150 @luozhx  请注意这个问题。

**Comment by xuelangZF** [comment]
3. 不要引入不需要的资源。模板文件中，标签不要有多余的 class。

**Comment by xuelangZF** [comment]
4. 内容过长时，用 `...` 截断内容。

![注意截断内容](https://cloud.githubusercontent.com/assets/2769831/21298910/424ab796-c5d1-11e6-89ab-b4254eca2ca6.png)

这里没必要把问题的所有题干都显示出来，显示出一部分即可。

**Comment by ym13349140** [comment]
收到

**Comment by xuelangZF** [comment]
4. 补充说明。

http://127.0.0.1:5000/admin/lab/ 中，“编辑信息” ，简介内容会被错误的截断。  
对于截断的更好的做法其实不是在后台判断保存多少长度，因为这样的话不同屏幕大小显示不同，并且可能填充不了整个宽度。更好的做法是用 css，设定相应元素的 `text-overflow=ellipsis` 即可。  
同时，对于那些被截断的部分，最好是用 [tooltips](https://getbootstrap.com/javascript/#tooltips) 做一个悬浮显示。  

不好意思，之前暗示你用 truncate 这个做法。（今天忽然想起来可以用 text-overflow 来做的）

或者你可以用更好的方法。

@ym13349140

**Comment by ym13349140** [comment]
收到~

**Comment by xuelangZF** [comment]
提交 6eb3b52ac5cb972ea6c0d7a39f3460ffcae373b1 完成。
