### ISSUE TITLE
问答题目判题方案讨论

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#197]
对于客观问答题目来说，一种可行的判题方法是 “同学互改”。

系统为每名同学随机发放 3 份答案，收到答案的同学需要为之评分。这样，每个同学的问答题目都会有三个同学的评分，取平均分即为该题目的最终得分。

@luozhx

**Comment by luozhx** [comment]
我觉得可以用fuzzywuzzy库进行模糊识别，然后给出一个参考分数

**Comment by xuelangZF** [comment]
给出参考分数的话，还是需要有人去判定这个评分是否准确的。   coursera 上一些主观题目就是这种互评给分的。这个可以征求下老师的意见。
