### ISSUE TITLE
微信扫码加入课程 功能

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#208]
老师：

> 引入之前提到过的 “私有课程”，分享课程二维码之后，需要学生通过微信扫码加入课程，然后才能浏览课程的内容。然后老师还可以通过微信给学生推送信息。

对分易目前就是老师开课后，学生扫码加入课程，然后才能看到课程内的相关资源。

@wzl281158150  了解下 对分易 目前的做法。

**Comment by ym13349140** [comment]
收到~

**Comment by xuelangZF** [comment]
目前什么进度？有没有一个原型可以看下！

**Comment by wzl281158150** [comment]
已经可以与微信号绑定，同时可以生成课程二维码，现在需要pull 新的加入课程的部分

**Comment by xuelangZF** [comment]
嗯嗯，GET

**Comment by xuelangZF** [comment]
现在 我是重定向 到course.join来加入课程 但是这个视图函数返回的是一个json  我需要发送get请求到这个函数  同时返回的页面是我自己创建的提示页面这个该怎么做？

Google 关键字： flask send get request

第一条命中：  
http://stackoverflow.com/questions/15463004/how-can-i-send-a-get-request-from-my-flask-app-to-another-site

**Comment by xuelangZF** [comment]
提交 7e5a67f6d26e4c1b692c660cce63851936bb9919 初步完成
