### ISSUE TITLE
非公开课 “加入课程” 逻辑更改

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#209]
目前我们的 “加入课程” 形同虚设，其实没什么用。

现在要做的改动是，学生点“加入课程” 后，需要老师一个 “批准” 的过程，只有经过老师批准后，才能看到课程的资源。

具体怎么实现， @luozhx  想一下，有疑问的话明天组会时可以问下老师。

**Comment by luozhx** [comment]
直接用一张表将申请存下来就行，教师登录后可以查看他的课程的申请情况，可以选择是否通过。数据库那边可以保留这条记录，改一下状态，也可以直接删除

**Comment by xuelangZF** [comment]
嗯，不过申请课程时可能还需要提供一些其他信息，比如学号、姓名之类的东西。

还有就是课程要有一个开放时间，在指定时间内开放注册，过时后就会锁定。

**Comment by xuelangZF** [comment]
嗯嗯，学号什么的放到注册时确实好。

指定开放时间也需要有一个审批的，只是说过了那个时间课程就彻底对外关闭了。

**Comment by luozhx** [comment]
那就只能在指定时间段内申请加入课程。
另外申请记录是要保存在数据库还是申请结束后就删除记录？

**Comment by xuelangZF** [comment]
申请记录的话保存在数据库吧。

**Comment by luozhx** [comment]
那么是要先实现整个逻辑还是连用户信息那边也一起修改？

**Comment by xuelangZF** [comment]
先实现整个逻辑吧，用户信息那边先等等。

**Comment by luozhx** [comment]
明白

**Comment by luozhx** [comment]
课程现在是需要分为3种，一种是公开不需要老师同意，另外一种是公开但是需要老师同意，最后一种是不公开需要老师同意吗？
如果是这样的话我打算在课程里面加上一个字段表示课程的种类，一个字段表示申请的截至时间，然后申请就是用户和课程之间带额外信息的多对多关系来实现。

**Comment by xuelangZF** [comment]
两种就行了，一种是公开不需要老师同意，另一种是不公开需要老师同意。

这里的公开是指可以看到课程资源的。

**Comment by luozhx** [comment]
行，那我就在课程里面加一个布尔字段标识一下，然后开放时间就直接用当前时间和数据库里面存的截止时间比较来判断。

**Comment by xuelangZF** [comment]
可以。

**Comment by luozhx** [comment]
另外现在教师和管理员账号不能加入课程，我觉得应该可以加入吧，直接@login_required可能比较好

**Comment by xuelangZF** [comment]
嗯嗯，可以，这块之前犹豫了下，没来得及改。

**Comment by xuelangZF** [comment]
非公开课原型实现完！提交 7a304a3b9e7215e5b2a1802b4b6ae004d329c736
