### ISSUE TITLE
作业提交管理功能

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#213]
目前每门课程都有试卷，除了试卷，我们还需要有一个作业模块。最核心的功能如下：

后台教师可以进行以下操作：

1. 相应课程下面发布作业；
2. 查看课程中学生提交的作业；

学生的操作：

1. 查看老师发布的作业；
2. 提交作业到系统中去。

需要进一步明确的问题：

* 作业以何种形式提交（PDF，DOC，还是项目源代码）
* 作业如果是源代码，需要在天河上执行吗？

@ym13349140 考虑清楚，有疑问的话可以讨论。

**Comment by ym13349140** [comment]
师兄，作业的数据库我暂时设置了这几个字段，你看看还有什么需要添加的吗？
![qq 20161224163911](https://cloud.githubusercontent.com/assets/17507937/21466101/a7594c90-c9f7-11e6-90ef-9df0ae8b1704.png)

**Comment by xuelangZF** [comment]
可以，没问题！

**Comment by xuelangZF** [comment]
创建试卷有问题的吧，我这边点保存后，没响应，js 报错如下：

![image](https://cloud.githubusercontent.com/assets/2769831/21501792/dde93e74-cc85-11e6-8e28-73b1f975e422.png)

**Comment by xuelangZF** [comment]
还有浏览作业和提交作业也是要有权限判断的，必须加入当前课程后才能浏览和提交。

**Comment by ym13349140** [comment]
好的~

**Comment by ym13349140** [comment]
创建作业失败的问题已经找到错误，是drop_img_simplemde定义的位置出了问题，现已解决。权限问题之前没有考虑到，我再加进去。

**Comment by ym13349140** [comment]
师兄，那个课程评论那里发现一点bug，星星变成竖着的了，不知道是不是只有我这边是这样。
![image](https://cloud.githubusercontent.com/assets/17507937/21518880/3ed4a040-cd24-11e6-9b7a-3b50999c69fc.png)

**Comment by xuelangZF** [comment]
我这里也是，😢

**Comment by xuelangZF** [comment]
新的代码 markdown 的使用还是有问题的，全屏模式会出错，如下：

![image](https://cloud.githubusercontent.com/assets/2769831/21524336/50d89324-cd50-11e6-92bd-5fd674d07c2d.png)

**Comment by xuelangZF** [comment]
关于`在线作业`这个功能我觉得没有必要，可以先删掉。

题库页面 http://a002.nscc-gz.cn:10165/problems/ 中有个 `竞赛平台`，它其实就是用来放置一些带有时间或者权限限制的作业（或者竞赛的）。后面我问下老师再决定具体要哪些功能。

**Comment by ym13349140** [comment]
好的~在线提交部分已删除，然后全屏问题是CSS设置了模态框宽度引起的，因为bootstrap默认的模态框的宽度放不下markdown编辑框，会把markdown编辑框的菜单栏分成两行，所以我当时就手动设置了此模态框的宽度，不过好像会造成全屏问题，我现在将bootstrap.css中的模态框的默认宽度稍微加宽一点就没问题了，其他地方的模态框测试过也没问题，只是变宽了一点而已。课程作业部分还有什么功能需要添加的吗？

**Comment by ym13349140** [comment]
还有一个关于作业提交的，是直接设置所以作业超过deadline就不能提交，还是说可以由老师自己决定，超过了截止日期的作业还能不能提交？

**Comment by xuelangZF** [comment]
直接限定死超过 deadline 不能提交吧。不过老师可以随时改 deadline 嘛，这样可以延迟deadline，于是又可以提及了。

**Comment by xuelangZF** [comment]
目前貌似想不到有什么功能了，开会时再问问老师吧。

**Comment by ym13349140** [comment]
好的~

**Comment by xuelangZF** [comment]
modal 中markdown 编辑框全屏问题你的解决方案有以下不足：

1. 直接修改了第三方的 bootstrap.min.css，这是需要极力**避免**的。因为你不知道它内部实现是什么样的，不知道这样的修改会不会带来**副作用**。这样做很可能会导致奇怪的Bug，并且通常很难调试。所以，回滚你对该文件的更改！
2. 修改后，其实效果也不是很好，只是在 modal 中全屏而已，看着很别扭。并且和其他 markdown 编辑框的全屏效果不一致！

正确的解决姿势参考这里：  https://github.com/NextStepWebs/simplemde-markdown-editor/issues/263  

PS： 这种问题一般首先去项目的 Issue 中找。

这个问题，我通过 Google 关键字 `simplemde modal full screen` ，得到的第一条就是上面的链接，里面有不错的解决方法。 

麻烦取消对 bootstrap 的更改，按照上面链接里的方法进行更改。  @ym13349140

**Comment by xuelangZF** [comment]
此外，关于时间的输入，你可以参考 luozhx 用的一个 bootstrap 时间插件，它的输入更加方便。

![image](https://cloud.githubusercontent.com/assets/2769831/21537640/5e1570b4-cdcf-11e6-8efd-3bdd19a480aa.png)

还有记得取消 modal 里面关于作业是否在线的选项以及相关代码。

**Comment by ym13349140** [comment]
好的

**Comment by ym13349140** [comment]
师兄，有一个问题，不知道是不是bootstrap时间插件内置的，时间设置的年份好像每次都初始化为1899年，不知道有没有办法改成当前年份，不然每次都要翻好几页设置年份。
![image](https://cloud.githubusercontent.com/assets/17507937/21538543/29867ab4-cdd9-11e6-9945-ddc148319643.png)

**Comment by xuelangZF** [comment]
不会啊，我这里 每次是当前时间啊：

![2016-12-29 3 20 56](https://cloud.githubusercontent.com/assets/2769831/21538688/70c5165a-cdda-11e6-87fc-b6f8728d71d4.png)

你问下 luozhx ，看是不是需要传参数啊

**Comment by ym13349140** [comment]
好~

**Comment by xuelangZF** [comment]
提交 5d75f66a75c7c6bea3fafd1f9f9af7685ff238e2 完成
