### ISSUE TITLE
课程评论样式 Bug

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#219]
课程评论中 `星星` 变竖着了？

@luozhx

**Comment by luozhx** [comment]
我测试了一下星星也变竖着了，不知道哪里出问题了
我写完加入课程逻辑后看看吧

**Comment by xuelangZF** [comment]
嗯嗯，你搞好后尽快修复哈

**Comment by luozhx** [comment]
是markdown-body和插件的样式冲突了，已修复

**Comment by xuelangZF** [comment]
提交 7a304a3b9e7215e5b2a1802b4b6ae004d329c736 修复。
