### ISSUE TITLE
非公开课程的细节完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#221]
目前已经完成了非公开课的权限申请管理，接下来需要完善几个细节！

1. 在站点首页以及课程首页中的课程列表中，对于**非公开课**加上一个醒目的标志，比如类似下面这种：

![2016-12-29 9 54 19](https://cloud.githubusercontent.com/assets/2769831/21535215/dc064908-cdac-11e6-9436-aa29dd5d2c13.png)

2. 非公开课，在成功加入前，只能够看到课程概览，**课时列表，课堂试卷，课程作业，课堂评价**等栏目不能展开（颜色用灰度表示，无鼠标点击效果）。并且在课程的详情页面 http://127.0.0.1:5000/course/1 中，要给出课程开放申请的截止时间！

![image](https://cloud.githubusercontent.com/assets/2769831/21535262/6b65ffee-cdad-11e6-81a8-f74b49bda34b.png)

3. 非公开课在提交加入申请后，“加入课程” 这个按钮变为 “加入审批中”，并不能点击。

目前先完善这么几个细节。  @luozhx

**Comment by xuelangZF** [comment]
考虑同学 test 加入了课程，老师审批通过，然后又退出了课程，再次加入，这时候后台如何处理？

![image](https://cloud.githubusercontent.com/assets/2769831/21538827/f938d174-cddb-11e6-8fd5-93782f1777f9.png)

目前好像是会有两个记录。

还有，最好是加入老师“踢出”课程的功能吧，避免误操作同意了不是学生的用户。

**Comment by luozhx** [comment]
现在的逻辑就是有两个记录，没有什么问题吧？
踢出课程的功能可以添加。

**Comment by xuelangZF** [comment]
有两条记录感觉怪怪的，不过先这样吧，不用改了。

**Comment by xuelangZF** [comment]
不错，看了你的更改，非常棒！

**Comment by xuelangZF** [comment]
之前在设计时，教师帐户是不允许加入课程的。现在来看不太合理，老师帐户最好也是可以加入课程的，因为有的课程是其他老师开的。（所以加入课程、退出课程的逻辑部分，只用保证 login_required 即可，不在需要 student_login 。）

![image](https://cloud.githubusercontent.com/assets/2769831/21543795/87487e38-ce04-11e6-99f9-01082858f9f4.png)

@luozhx  更改相关的实现逻辑。

**Comment by luozhx** [comment]
已更改

**Comment by xuelangZF** [comment]
eHPC/templates/course/widget_course_base.html 还有问题：

![image](https://cloud.githubusercontent.com/assets/2769831/21544395/5fd0e5ca-ce09-11e6-8d47-0989e2527259.png)

else 语句从未执行过。if 中应该是 `current_user.is..`。 

还有，给 ‘请登录再加入课程’  按钮添加跳转链接，点击后跳转到登录页面，登录完成之后自动跳转到课程的页面。

提示： next 参数的使用！

**Comment by xuelangZF** [comment]
提交 059c0b788803833fe65830dc0eadf772f7cbdf4f 完成
