### ISSUE TITLE
提交表单验证

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#236]
之前我们的表单字断大部分都是添加了 required 来保证提交时该字段不会被忘记，但是有着以下的问题：

1. Ajax 提交表单数据时，required 没有作用。
2. 有时候不止要判断是否为空，还要判断是否符合要求，比如长度，格式的要求。

成熟的做法是用 js 在前端进行验证，这方面有成熟的库，做的非常棒。

Parsley.js 是一个特别棒的库，github 中比较火，并且一直维护中，值得拥有。还有示例代码：http://parsleyjs.org/doc/examples.html 和丰富的文档： http://parsleyjs.org/doc/index.html 。

鉴于我们之前的表单挺多的，现在打算首先将我们站点用到的表单数据分类，看看都是需要哪些验证：

* 邮箱地址?
* 长度？
* 文件大小？

然后在 parsley.js 里面找到相应的添加钩子的方法，最后统一为所有表单添加。

特别注意弄清楚下面两个问题：

1. 多文件上传时，用的 dropzone ，里面已经对文件类型和大小进行了限制，会不会和 parsley 冲突。
2. Markdown 编辑框中，由于 simplemde 需要 text_area 字段，所以这里的验证如何去做？

@ym13349140  负责搞明白上面的问题

**Comment by ym13349140** [comment]
收到！

**Comment by ym13349140** [comment]
师兄，我们有些表单是用的ajax提交到后台的，parsley.js也是只能验证直接提交的表单，所以我现在先把能用parsley.js的用了，然后那些用ajax提交的就只能用JS来做校验了

**Comment by xuelangZF** [comment]
好的，那先验证直接提交的表单吧，最好是找一个方便、快捷的方法。

**Comment by ym13349140** [comment]
我想问一下那个试题创建那边的逻辑，我看到选择题是设置的至少需要选择一个知识点才可以创建题目，然后其他类型题是不用设置知识点也可以创建的，这里需要统一吗？知识点是不是每道题都是必须的？ @xuelangZF @luozhx

**Comment by ym13349140** [comment]
我想问一下那个试题创建那边的逻辑，我看到选择题是设置的至少需要选择一个知识点才可以创建题目，然后其他类型题是不用设置知识点也可以创建的，这里需要统一吗？知识点是不是每道题都是必须的？ @xuelangZF

**Comment by xuelangZF** [comment]
你统一一下吧，全部需要知识点。

**Comment by ym13349140** [comment]
好~

**Comment by xuelangZF** [comment]
Ajax 提交也是可以用 parsely.js 来验证的，这里有一篇博客： https://geekalicious.pt/blog/en/javascript/submit-ajax-form-and-custom-validations-with-parsley-js

**Comment by ym13349140** [comment]
了解~他这个其实跟直接用JS验证一样，就是在提交之前先判断是否符合要求，只是这个是直接调用parsley里面的函数来判断。那我根据实际情况来看怎么验证比较方便吧，因为parsley.js输出的提示信息是统一的，有些地方我感觉输出特定的提示信息比较清晰。有个别地方的ajax提交是没有form，只有input元素，这种情况的话parsley也是没办法用的，我就还是用了JS判断了。

**Comment by ym13349140** [comment]
师兄，这里的任务标题和内容栏默认值都是空，创建任务的时候没有标题和任务内容也是可以创建任务的吗？这里需要改成非空吗？
![image](https://cloud.githubusercontent.com/assets/17507937/21796423/b5c26f56-d743-11e6-80e5-460a7cc4faf1.png)

**Comment by xuelangZF** [comment]
改为非空的，默认值改为 "" 吧。

**Comment by xuelangZF** [comment]
其实可以对部分代码进行抽象，比如 

![image](https://cloud.githubusercontent.com/assets/2769831/21841608/e614340c-d81d-11e6-8868-74aa281278d3.png)

这里，完全可以写一个函数，通过参数传递 `请选择正确答案` 等反馈信息。

希望代码尽量保持精简。

**Comment by xuelangZF** [comment]
使用 parsley.js 使，引用 CDN 的资源吧。 可以用这个 CDN： http://www.bootcdn.cn/parsley.js/ 

不用把文件放本地。

**Comment by ym13349140** [comment]
好的~

**Comment by ym13349140** [comment]
师兄，直接引用parsley.js的话提示信息是只能显示英文的好像，就让他显示英文提示吗？

**Comment by xuelangZF** [comment]
CDN 上没有中文的配置文件吗？ 看下原因，感觉应该是可以显示中文的。

**Comment by ym13349140** [comment]
中文的话需要引用扩展的语言包重构提示信息的那个函数，CDN上好像没有配置文件，而且它那个中文包是跟它那个完整的压缩包配套的，引入的是整个Parsley目录下的文件，我试了将中文包里的引用改成单独的parsley.js文件，但是好像是没有用的。
![image](https://cloud.githubusercontent.com/assets/17507937/21845240/cd52b128-d82c-11e6-84cf-26ab4b1a3012.png)

**Comment by ym13349140** [comment]
然后刚刚我发现之前添加一个src文件夹，就是包含语言包的那个文件夹，但是我发现这个文件夹好像是多余的，我们并没有用到里面的文件，所以是可以删除的，只用增加parsley.js一个文件。

**Comment by xuelangZF** [comment]
意思是只用一个 parsley.js 文件就可以搞定了？

**Comment by ym13349140** [comment]
本来parsley.js就是集成了那个压缩包里所需的基本功能的文件的，所以基本的表单验证只用这一个文件就可以完成，我之前以为会用到一些扩展的功能，所以添加了src文件夹，但是貌似我们用不到那些，所以只需要一个parsley.js文件就可以了，然后直接把中文包的翻译文件复制进去就可以显示中文。

**Comment by xuelangZF** [comment]
ok，那就在本地引入吧。

**Comment by ym13349140** [comment]
好，那我把那些扩展文件删了，然后把那个显示非法信息的代码封装成函数来调用再提交

**Comment by xuelangZF** [comment]
再看看其他有没有可以封装的地方，尽量不要重复代码

**Comment by ym13349140** [comment]
好！

**Comment by xuelangZF** [comment]
有的改动会不会有副作用啊，比如下面的js文件：

![image](https://cloud.githubusercontent.com/assets/2769831/21878039/5e3d7e64-d8ca-11e6-92ac-89a4b568730d.png)

simplemde 是用来支持markdown编辑框的，你直接删掉不会出问题吗？

还有这里的文件： https://github.com/xuelangZF/ehpc/pull/281/files#diff-3efbd75675c78cf5f16a4633e342cf34 ，删掉了 edt1，edt2，edt3。

**Comment by ym13349140** [comment]
没有删除markdown编辑框，只是删了那个之前自定义的validateForm()函数，那几个edt一开始我写表单验证的时候读取edt的值有些问题，所以我都移到相应的html文件里去了，我把他们移回去在提交吧，顺便pull最新的代码。

**Comment by xuelangZF** [comment]
哦哦，可以，辛苦

**Comment by xuelangZF** [comment]
提交 733b0ec969cd47b78f4ff2e8a2222915616c8531 初步完成
