### ISSUE TITLE
JS和JQuery函数的位置问题

### ISSUE THREAD

**Issue by ym13349140** [xuelangZF/ehpc#238]
刚刚在统计表单信息的时候发现一个bug，案例创建时添加了tag无法删除，最后发现是`eHPC/static/js/admin/case/case.js`中，我之前写在`$(document).ready(function () {})`外面的del_tag()函数被移到了$(document).ready(function () {}) 里面，同样的问题validateForm()函数也存在。

这两个函数都是用原生的JS定义的函数，放到JQuery里面去会失效，网页会报错找不到函数，如下：
![image](https://cloud.githubusercontent.com/assets/17507937/21561849/7ebe27aa-cead-11e6-9491-a82a6c2b4aba.png)

下面这两个函数都得放到$(document).ready(function () {}) 外面去:

![image](https://cloud.githubusercontent.com/assets/17507937/21561864/bbddc384-cead-11e6-9b15-6649a9b090fd.png)

大家下次写JS函数的时候可能需要注意一下定义的位置。

**Comment by xuelangZF** [comment]
jquery 的 $(function() {} ) 里面的内容，表示文档加载完毕才会执行。

上面 @ym13349140  提到的两个函数，其实是在加载文档前就需要执行到的，所以不能放在里面。

**Comment by ym13349140** [comment]
对~刚刚也发现解释有误，所以关闭了issue，不好意思，差点弄错了~

**Comment by xuelangZF** [comment]
没事，错了也不用关闭，下面还可以讨论，还可以重新编辑。主要是提出来，大家知道就好。:+1:

**Comment by ym13349140** [comment]
好的~
