### ISSUE TITLE
删除时给出警告信息？

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#241]
在删除一些重要资源时，比如整个课程，应该给出警告提示 modal，包含类似下面的内容：

“会删除课程相关的所有内容，包括课时资源，课程题库，课程作业等，是否确认删除”

然后等老师点 `确认` 后，才真正去删除内容。删除成功其实不用返回删除成功的 alert，毕竟页面上这个内容已经不在了。（避免 alert，或者可以在课程表格的头部加上一个 info 条表示删除成功。）

@luozhx 来完成。

**Comment by luozhx** [comment]
那我就把所有删除成功的alert去掉吧
另外除了整个课程之外，还有地方需要加警告？

**Comment by xuelangZF** [comment]
不止删除成功的 alert 去掉，还要添加删除确定。

所有的删除都加上确定的提示吧，包括教师管理和管理员管理中

**Comment by luozhx** [comment]
好

**Comment by xuelangZF** [comment]
案例管理：http://127.0.0.1:5000/admin/cases/  无法删除案例。#Bug

**Comment by luozhx** [comment]
少include了那个模块框，所以无法删除

**Comment by xuelangZF** [comment]
提交 6d427905c811ba19ccece6cbb38f5f1e6aeec709 已解决
