### ISSUE TITLE
并行程序编译、运行文档以及进一步功能

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#242]
# 文档

@milanlanlan 整理了 [超算接口说明文档](https://github.com/xuelangZF/ehpc/wiki/%E8%B6%85%E7%AE%97%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3) ，但是太过粗糙。需要重新补充内容，我已经在wiki中用删除线标出了需要补充的地方。麻烦和超算那边沟通，搞清楚后，尽快补充完整。

补充时注意几点：

1. Markdown 格式的使用！花十分钟看下 Markdown 手册，尽量让文档看起来舒服点。
2. 一些因为并行计算而有点特殊的概念，比如核数、路径等要详细说明。
3. 删除线中的内容，要重点补充。

# 下一步功能

和超算沟通，问他们看能不能提供接口，返回作业执行过程中的 IO通信，文件读取等指标。

PS：和超算的往来邮件，记得抄送给我。

@milanlanlan

**Comment by milanlanlan** [comment]
收到，此外，没有往来邮件，交流都在 [https://github.com/JiangLiNSCC/eHPC/issues/7](https://github.com/JiangLiNSCC/eHPC/issues/7) 中

**Comment by xuelangZF** [comment]
👌 我看了下你们的 issue ，好多讨论啊。

**Comment by xuelangZF** [comment]
看了你改后的 Wiki，感觉还是有问题的。就 `文件管理` 的接口来说，你补充了 GET 请求，说是：

> GET 请求 ： 用于获取目录内容；

我试了下（之前就试过，所以我才用下划线表示这里不明不白），结果如下：

![image](https://cloud.githubusercontent.com/assets/2769831/21580238/412628aa-d021-11e6-8f02-be0c7945653c.png)  
![image](https://cloud.githubusercontent.com/assets/2769831/21580243/87ff90d6-d021-11e6-9084-3bcb46961dcb.png)

返回的是 201，按照文档中说法，表示已经加入了队列，可以异步获取，我接着用 aync 试着获取，还是没有获取目录。是我哪里理解错了吗？

不知道你在云主机上有没有亲自测试一下呢？

**Comment by milanlanlan** [comment]
返回201之后保存output里的id，然后再用异步请求去获取，这个流程我以前测试过是没问题的。
不过这个错误出现过很多次，我也反映过很多次了，是因为超算那边出了问题，估计是又改了接口，我再测试看看他改了什么。

**Comment by milanlanlan** [comment]
其实以前所有api我都测试过的，不过超算那边不断修改有时候还没有通知我，我有点跟不上变化

**Comment by xuelangZF** [comment]
强烈建议你学习下 request 库，然后写一个测试 API 的class，部署一个测试的脚本，这样每次跑一遍就知道哪个接口出了问题。

**Comment by milanlanlan** [comment]
好的，我之前好像看过超算那边的代码也有测试脚本，我去看看能不能参考过来。
另外，今天我下午和晚上都测试了一下，好像超算那边又连不上了，所以测试不了api，所以可能之后我把新的代码和注释一起提交吧。

**Comment by xuelangZF** [comment]
@milanlanlan  异步获取这里，接口你写错了！！！！

应该是 `http://IPAddress:port/api/aysnc/<async-id>`  ，**async** 。文档中写错，可以理解，笔误嘛。可上面我专门质疑这个接口，还没有发现这里的错误，我不知道是为什么了。

希望不要有这种错误了，太耗费精力、时间！

**Comment by milanlanlan** [comment]
收到！

**Comment by lijiang2014** [comment]
之前的错误有一部分的原因是 worker 在运行完毕后 没有恢复到 root 身份，进而进程一直卡住 导致 API 前期可用，大量调用后 就不可用了。 现在此错误已修复。

**Comment by lijiang2014** [comment]
现在你们使用的是 api command 来进行编译和运行。 推荐使用 api command 来进行编译 ， 使用 api job 来进行运行 ， 但还是可能会存在安全和性能问题 ： 
×1.0 如果有恶意程序，通过代码扫描删除所有文件，可能会导致严重的故障
x2.0 如何运行资源而又尽量避免浪费。

**Comment by lijiang2014** [comment]
关于刚刚讨论的 参数设置问题，建议如下 ：
对于大部分的案例，只给用户的单个请求提供单节点的资源。 
根据选用的编译器（C/C++/Fortran）和并行编程模型（MPI/OMP/MPI+OMP） 来生成不同的编译命令和作业脚本。
并行参数，可以根据所选的编程模型 提供 线程数 c（对应  srun -c 参数） 和 进程数 n （对应 -n） 来进行 脚本的生成 （对于但节点作业，需要  c * n < 24 ）

**Comment by lijiang2014** [comment]
对于大部分的简单的程序 ， 采用系统默认的编译环境即可 ：
GCC 4.4.7  :  C  , C++  , Fortran  ,  支持 OMP 。 
ICC 14.0.2 :  C , C++ , Fortan , 支持 OMP 。
默认的 mpicc 为 ICC 版本的 ，支持 OMP 。 

module 的加载是临时生效，不同会话间不会相互影响（只对但前的 command / JOB 请求生效） ， 需要使用时拼接到对应的命令或作业脚本即可。
