### ISSUE TITLE
虚拟实验室引用问答题时的编辑框

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#245]
![2016-12-31 11 37 16](https://cloud.githubusercontent.com/assets/2769831/21575655/efe079aa-cf4e-11e6-8a55-5f69354ac2fa.png)

@wzl281158150  尽快修复

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
提交 dc76984a18ea1c1c37fa063d50719865d931358c 已解决。

> 未引用simplemde的css文件，引入后回复正常。
