### ISSUE TITLE
CSRF 攻击的预防

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#249]
# 什么是 CSRF 攻击

CSRF（Cross-site request forgery），中文名称：跨站请求伪造，也被称为：one click attack/session riding，缩写为：CSRF/XSRF。

那么CSRF到底能够干嘛呢？你可以这样简单的理解：攻击者可以盗用你的登陆信息，以你的身份模拟发送各种请求。攻击者只要借助少许的社会工程学的诡计，例如通过QQ等聊天软件发送的链接(有些还伪装成短域名，用户无法分辨)，攻击者就能迫使Web应用的用户去执行攻击者预设的操作。例如，当用户登录网络银行去查看其存款余额，在他没有退出时，就点击了一个QQ好友发来的链接，那么该用户银行帐户中的资金就有可能被转移到攻击者指定的帐户中。

所以遇到CSRF攻击时，将对终端用户的数据和操作指令构成严重的威胁；当受攻击的终端用户具有管理员帐户的时候，CSRF攻击将危及整个Web应用程序。

![image](https://cloud.githubusercontent.com/assets/2769831/21632893/8430d17a-d285-11e6-841a-cf2af8f69168.png)

# 预防 CSRF 攻击

1. 提交验证码 
    在表单中增加一个随机的数字或字母验证码，通过强制用户和应用进行交互，来有效地遏制CSRF攻击。

2. Referer Check 
    检查如果是非正常页面过来的请求，则极有可能是CSRF攻击。

3. token验证

    在 HTTP 请求中以参数的形式加入一个随机产生的 token，并在服务器端建立一个拦截器来验证这个 token，如果请求中没有 token 或者 token 内容不正确，则认为可能是 CSRF 攻击而拒绝该请求。
token需要足够随机敏感的操作应该使用POST，而不是GET，以form表单的形式提交，可以避免token泄露。

# 具体操作

Flask 中的 CSRF 预防攻击可以参考 [CSRF Protection](http://flask.pocoo.org/snippets/3/)。

@luozhx   更新我们所有的 post 表单，使其可以预防CSRF攻击。

# 更多阅读

[CSRF Wiki](https://en.wikipedia.org/wiki/Cross-site_request_forgery)    
[Flask Series: Security](https://damyanon.net/flask-series-security/)

**Comment by luozhx** [comment]
我试了一下在所有的post表单里面加上_csrf_token之后发现还是有一些问题。
大部分表单是可以正常工作，但是有些页面如果有两个POST的话那么就不能正常工作了。
例如更改课程封面，首先第一个POST请求是将图片上传，第二个POST是确认保存。但是将图片上传之后，点击保存会返回403错误。因为在这个页面中这两个POST的token是一样的，这样第二个POST后台好像是判断为不合法。
另外我们的post表单数量太多，而且发送的方式类型都很有多不同，很难保证发送到后台后效果一样。
有的表单是发图片，有的是发送json，有的是发送普通的文本。JSON类型似乎就无法用统一的方法读取到token。
还有一个问题是有些JS代码和HTML文件分开，传递token非常麻烦，而且有些JS文件还会被多个HTML引用，关系非常混乱，token的位置很难确定。

**Comment by xuelangZF** [comment]
这部分确实不好搞，这个链接：http://flask.pocoo.org/snippets/3/ 不一定能应付所有情况，我们一起看看怎么解决上面你提出的这些问题吧。

**Comment by xuelangZF** [comment]
不用看 Flask-WTF 的代码了！

文档中有说：https://flask-wtf.readthedocs.io/en/stable/csrf.html   ，这个文档讲的很清楚！！

**Comment by luozhx** [comment]
flask_wtf我昨晚也看了下，不过项目里没装，所以我就直接用[CSRF Protection](http://flask.pocoo.org/snippets/3/)这个实现。现在就直接改用Flask-WTF来实现是吧？

**Comment by xuelangZF** [comment]
flask_wtf 来做吧，它的很成熟，并且改的内容也不多。

模板页面不用再写 FlaskForm 类，甚至你目前写的都不用大改，也是加下面的内容：

```
<form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>
```

Ajax 请求时，改起来好像也很容易，

```
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
</script>
```

**Comment by xuelangZF** [comment]
```
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
</script>
```

这段代码最好是放在一个 js 文件中，模板中引入这个 js 来避免 csrf 攻击。每个模板中都加入这段代码，略显麻烦。

**Comment by luozhx** [comment]
这样的话这部分还是无法渲染的 `var csrf_token = "{{ csrf_token() }}";`
还是要通过一个`</script>`标签来传递，其实差不多麻烦吧

**Comment by xuelangZF** [comment]
> 这部分还是无法渲染的 var csrf_token = "{{ csrf_token() }}";

不一定要通过这种方式获得 csrf_token 啊，form 表单中 `value="{{ csrf_token() }}"` ，可以在 js 中获取这个 value 啊。不一定非要通过模板来传递吧！这种通过钩子挺好的啊。

**Comment by luozhx** [comment]
`{{ csrf_token() }}`这部分只有写在html页面内才能被渲染吧。
然后如果将`$.ajaxSetup`部分写成一个js文件，那么就只能在html内写
```html
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
</script>
```
这样才能得到token，这样写的话也就少了这部分而已
```javascript
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
```
而且其实基本上大部分页面都会有POST表单，那么为每一个页面都设置`  $.ajaxSetup`我觉得也挺合理的
因为每个页面都需要防止CSRF攻击，这样的话即使后期在没有POST的页面内增加POST请求之后，也不需要增加这段代码了。

**Comment by xuelangZF** [comment]
我明白你的意思，我的意思你可能还不太明白。

`{{ csrf_token() }} 这部分是在html 内才能被渲染，但是 `<input>`表单中的 value 值其实也是它，这样我们可以在 js 中获取这个值。

可以用 js 获取页面元素的 value 值吧！

**Comment by xuelangZF** [comment]
可以将这段 js 代码放进 main.js ，这样其他文件不用单独引用了，因为在 base.html 中有 main.js 的。

**Comment by xuelangZF** [comment]
另外，你最好多测试几个 post 请求，看看有没有问题。（可以用 postman 去发请求）

**Comment by xuelangZF** [comment]
还有，当session 中字段验证不通过时，能统一返回一个 403 页面。

**Comment by luozhx** [comment]
但是有些地方没有表单，只有AJAX，这样页面内就没有token了。
另外admin/base.html好像没有引用main.js
当session 中字段验证不通过时，现在默认是返回400错误。

**Comment by xuelangZF** [comment]
没有 ajax 的话，就不用下面的那段代码。因此如果获取 `<input>` 表单项失败的话，就不注册段代码呗。

没有引入的话，就引入一下吧，以后可以把一些共有的代码都放里面。

返回 403 是因为我之前写了 403 模板页面，400 的没有模板页面。

**Comment by luozhx** [comment]
获取 <input> 表单项失败也不能不注册吧。
AJAX还是要发的啊。

**Comment by xuelangZF** [comment]
哦，确实是，我的错。那看来写进 base 模板中去，一劳永逸得了。👍 👍 👍

**Comment by luozhx** [comment]
OK

**Comment by luozhx** [comment]
还有一个问题，现在普通POST表单里面的token是在base页面用JS添加，还是直接手动添加` <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>`呢

**Comment by xuelangZF** [comment]
用 js 添加吧。

**Comment by luozhx** [comment]
不会，我试过了
默认会为每一个都添加的

**Comment by xuelangZF** [comment]
奇怪的Bug，虚拟实验室部分提交问题答案部分也是用的 ajax 请求，我在虚拟实验室的 base 模板页面（lab/lab_base.html ）中添加了 ajaxSetup ，但是ajax请求头部中并没有 csrf_token。所以无法提交问题答案。

这里不知道为什么？

（这里的 ajax 是在单独的 js 文件中发起的请求）找了一下，基本没有类似的问题，下面这个有点类似：

http://stackoverflow.com/questions/20887584/global-ajaxsetup-call-doesnt-affect-ajax-calls-in-separate-functions

**Comment by luozhx** [comment]
我看了下lab/practice.js，里面的ajax会把beforeSend给覆盖掉，去掉之后就好了。
应该可以把模态框的触发可以改成使用按钮触发，也可以将设置token放里面。
我觉得改成按钮触发比较好，这样比较统一
```javascript
 $.ajax({
            url: address,
            type: "post",
            data: {
                user_sol: user_sol,
                question_type: question_type,
                question_id: $('div[data-name=question]').eq(0).data('id')
            },
            beforeSend: function () {
                $('#loading-gif').modal();
            },
            success: function (data) {
                if (data['status'] == 'success') {
                    $('#pass').modal();
                }
                else if (data['status'] == 'fail') {
                    $('#fail').modal();
                }
            }
        });
```

**Comment by xuelangZF** [comment]
改成按钮触发吧。

我去，我看了半天 lab/practice.js 中的 ajax 请求，都没有注意到这里也有 `beforeSend` ，😭 😭。只好把 lab 模块取消了 csrf 保护。

那麻烦你再把这块加上去把，把我刚提交中的 `取消 CSRF 保护` 删除，然后再提交一份吧。

**Comment by luozhx** [comment]
好

**Comment by xuelangZF** [comment]
提交 e3930c4ced6217536e7a6401ff544314ed83a35f 完成
