### ISSUE TITLE
拖拽上传图片进度显示

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#250]
目前我们拖拽上传图片时，如果图片太大，传的时间太长的话，前台也不会给出任何反馈。

所以最好是，如果上传时间超过两秒，则加一个 modal 显示正在上传中（显示上传进度最好）。

或者是 @wzl281158150 有什么更好的方法？ 你来做这块吧。

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
提交 c8789e61eaa99ca4ec6144658de560a679380b7d 完成
