### ISSUE TITLE
更改前端代码请小心

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#252]
更改旧代码前要彻底明白旧代码中的每一部分是做什么的？和其他部分有什么关联？

如果代码的一部分在其他地方有耦合，改动时就会牵一发而动一身，这时候需要特别小心，必须把关联的部分都更改，不然很可能导致拆东墙补西墙了。

比如，提交 6d427905c811ba19ccece6cbb38f5f1e6aeec709 中对 [eHPC/static/js/admin/course/homework.js](https://github.com/xuelangZF/ehpc/commit/6d427905c811ba19ccece6cbb38f5f1e6aeec709#diff-46d903a932e62e9533a85b26f15520ca) 的改动，导致了后台无法正常地添加，编辑作业。

所以，每一次改动时，要特别小心，不能只关注于把当前功能完成了，很可能造成对其他部分功能的影响。

@luozhx  来修复。

不知道有什么好的方法来避免这种问题没有。

**Comment by luozhx** [comment]
因为很多通过`<script>`传递URL的地方其实可以直接用`location.href`代替，所以我在增加删除警告的同时改了一下写法，不过在这里我只修改了删除的操作，所以导致其他操作无法正常进行，现已修复。

**Comment by xuelangZF** [comment]
我把你这个修改单独作为一次 commit 了，这样清晰点。你把 CSRF 这个再改下，然后只用提交 CSRF 的吧。
