### ISSUE TITLE
题库页面样式大调整

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#257]
题目展示页面还需要好好改下，目前有下面问题。

1. 题目描述部分没有 markdown 渲染。（题目的描述部分，后台输入其实支持 markdown，前端也需要渲染）

![2017-01-08 12 06 23](https://cloud.githubusercontent.com/assets/2769831/21747225/e5b940cc-d59a-11e6-9fdb-1fe888c855a5.png)

2. 判断题目和填空题目，题目描述部分，左面有多余的空白，看上去很不整齐。

![2017-01-08 12 18 05](https://cloud.githubusercontent.com/assets/2769831/21747274/9d4b82f8-d59c-11e6-8bb8-0620cc149804.png)

3. 题型选择这里，需要显示每个题型下面题目数量，如果该题型下面没有题目，就不要显示。

![image](https://cloud.githubusercontent.com/assets/2769831/21747283/e0fe53a4-d59c-11e6-8383-8a2c10605c30.png)

@wzl281158150  完成。都是些细节问题，没有太大难度，希望做好点。

**Comment by wzl281158150** [comment]
师兄这个可能还要晚一点，我还在弄 latex

**Comment by xuelangZF** [comment]
ok, 先把 latex 搞定吧 。

**Comment by wzl281158150** [comment]
师兄   latex已经弄好了。我看见你的填空题中有代码填空，如果有这样的空那么整个这个题库页面要重写

**Comment by xuelangZF** [comment]
填空题目是个坑，主要有两个问题：

1. 数据库怎样存储。
2. 后台如何方便地输入填空题目。

现在的方法其实有很大的缺陷啊。

**Comment by wzl281158150** [comment]
Mathjax这个也是坑，太难用了.....

**Comment by wzl281158150** [comment]
师兄，这个东西其实是和markdown非常冲突的，不管先渲染哪个最后都有问题

**Comment by xuelangZF** [comment]
有什么问题呢？

**Comment by wzl281158150** [comment]
先 markdown   mathjax会把 markdown里的代码给污染  先mathjax    markdown会把mathjax弄好的样式破坏

**Comment by xuelangZF** [comment]
😭 😭 那先放一放这个 Latex 的 feature 吧。

**Comment by xuelangZF** [comment]
提交 b07e74f16cbd2cef1bce7a721e468352abfac237 完成
