### ISSUE TITLE
教师管理页面入口地址

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#258]
更改教师帐户的入口地址，登录地址  http://a002.nscc-gz.cn:10165/user/signin/ 这里，可以进行老师和学生两种帐户的登录：

* 老师登录进去后，是老师的管理首页面；
* 学生登录进去后，是next 跳转页面或者站点首页。

@luozhx  负责。

**Comment by luozhx** [comment]
老师登陆的话只有next=/的时候才到管理首页吧，其他地方登陆应该和学生是一样的？

**Comment by xuelangZF** [comment]
嗯嗯

**Comment by luozhx** [comment]
那管理员需要跳转吗

**Comment by xuelangZF** [comment]
管理员不用跳转了吧，直接首页。

**Comment by xuelangZF** [comment]
后台那里只能进行系统管理员的登录，取消教师的入口。

**Comment by luozhx** [comment]
好

**Comment by xuelangZF** [comment]
对了，你说要不要把教师角色和学生角色彻底分开，教师角色只允许后台管理，不能进行加入课程等系列操作？

**Comment by luozhx** [comment]
没什么必要吧，这样的话教师如果想要加入课程的话就需要两个账号了。
现在这样挺好的，教师账号就是比学生账号可以多一个教师管理界面。

**Comment by xuelangZF** [comment]
ok，那就这样吧

**Comment by xuelangZF** [comment]
对了，还有一些细节问题，比如账户的下拉菜单那里，教师账户应该和学生的不一样，至少应该添加一个后台管理的入口（因为万一登录教师账户，再浏览站点前台的话，很难再找到后台管理的路径了）。

![image](https://cloud.githubusercontent.com/assets/2769831/21756812/13bcd65c-d661-11e6-8dd4-e8a4e9034132.png)

或者还有其他一些细节地方我没想到的。

**Comment by luozhx** [comment]
还有一个问题是如果直接在浏览器打开`http://127.0.0.1:5000/admin/course/1/homework/`这个链接的话，会直接跳转到后台登陆界面，但是后台只能登陆管理员，教师账号登陆不进去。

**Comment by xuelangZF** [comment]
对，这里的跳转也需要改一下入口地址。

**Comment by luozhx** [comment]
现在我在这里增加了一个入口，我觉得在首页登陆后就不需要跳转到后台管理了吧。
实际用起来我觉得非常不方便。
![image](https://cloud.githubusercontent.com/assets/22886929/21771068/ef92751a-d6c0-11e6-9a36-868f8392ac4c.png)

**Comment by xuelangZF** [comment]
嗯嗯，教师管理的入口放这里还是不太明显，把它抽出来放到图标的左边，配上一个按钮为 “教师管理”，同理，在管理页面的退出按钮前，加上一个按钮为”切换为学生“。

**Comment by xuelangZF** [comment]
提交 ae4e68fee54c847bf0bd54e773a9f34739204c2c 完成
