### ISSUE TITLE
文档任务

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#260]
文档写作任务：

1. CSRF 文档介绍； @xuelangZF
2. 补充 Ajax setting 中的 before_send 介绍到 [Ajax 使用文档](https://github.com/xuelangZF/ehpc/wiki/Ajax-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)。 @Zouzhp3  
3. 更新上传进度条的显示，到 [Markdown 编辑器](https://github.com/xuelangZF/ehpc/wiki/Markdown-%E7%BC%96%E8%BE%91%E5%99%A8)  @Zouzhp3
4. 更新 [超算接口说明文档](https://github.com/xuelangZF/ehpc/wiki/%E8%B6%85%E7%AE%97%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3) , 添加具体的 API 使用截图。 @Zouzhp3 
5. 更新 [表单验证文档](https://github.com/xuelangZF/ehpc/wiki/%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81%E6%96%87%E6%A1%A3)  @Zouzhp3 

具体参考： https://github.com/xuelangZF/ehpc/issues/228

**Comment by Zouzhp3** [comment]
收到

**Comment by xuelangZF** [comment]
6. 更新Latex公式支持的文档，到 [Markdown 编辑器](https://github.com/xuelangZF/ehpc/wiki/Markdown-%E7%BC%96%E8%BE%91%E5%99%A8)  @Zouzhp3

**Comment by xuelangZF** [comment]
更新文档，遇到问题请先跟踪相应的 issue。

还有疑问的话，可以询问功能负责人。

**Comment by xuelangZF** [comment]
@Zouzhp3  文档更新的怎么样了

**Comment by Zouzhp3** [comment]
ajax 文档已经更新完，现在还在写 markdown 编辑器里的上传进度条和 Latex 公式

**Comment by xuelangZF** [comment]
👌

**Comment by xuelangZF** [comment]
4、5更新的怎么样了

**Comment by Zouzhp3** [comment]
今天还在写部署 openstack 的文档，打算明天更新完 4，后天更新完 5

**Comment by xuelangZF** [comment]
5 你需要和 @ym13349140  好好沟通，尽量写的完整些

**Comment by Zouzhp3** [comment]
OK

**Comment by Zouzhp3** [comment]
发现在wiki里无法拖拽上传图片。是否要开一个存储图片的文件夹，然后上传并引用位置？

**Comment by xuelangZF** [comment]
教你一个hack 的方法：在issue中拖拽图片，上传完后，记录下图片链接（issue中可以删除图片了），然后在wiki中引用。

**Comment by xuelangZF** [comment]
表单验证那块前面介绍特别好，不过对于 parsely.js 的使用介绍的有点少，可以参考 https://github.com/xuelangZF/ehpc/issues/293  和 https://github.com/xuelangZF/ehpc/issues/292 来补充。

**Comment by Zouzhp3** [comment]
OK~

**Comment by xuelangZF** [comment]
@wzl281158150  更新 https://github.com/xuelangZF/ehpc/wiki/Markdown-%E7%BC%96%E8%BE%91%E5%99%A8 文档。

**Comment by wzl281158150** [comment]
我好像没有修改文档的权限

**Comment by xuelangZF** [comment]
我给你权限，你看下，目前版本不够新。

**Comment by xuelangZF** [comment]
@Zouzhp3 @wzl281158150 @milanlanlan @ym13349140 @luozhx  每个人都去读下 wiki，特别是自己负责的部分，一定要使 wiki 清晰易懂，确实起到作用（而不是写完之后就放到那里不再改动）。

**Comment by xuelangZF** [comment]
更新了 [静态资源避免缓存](https://github.com/xuelangZF/ehpc/wiki/%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E9%81%BF%E5%85%8D%E7%BC%93%E5%AD%98) ，增加了对所有静态资源的强制更新实现。
