### ISSUE TITLE
超算接口的并发性能测试

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#261]
测试超算 API 的并发性能，比如：

* 一次性发起 100 个 HTTP请求来编译运行程序，看平均要多久的响应时间。

要提交**测试代码**

并给我发邮件：测试的结果，结果最好以图表的形势直观显示。

@milanlanlan

**Comment by milanlanlan** [comment]
好的，现在由于之前说的参数问题没有最终确定，所以我也不知道如何下手比较好，可能需要先等讨论完并完成主要功能再进行压力测试！

**Comment by xuelangZF** [comment]
不用等参数最终确定就可以压力测试吧，可以并发传 100 个demo程序上去，看超算那边会不会卡死。

**Comment by milanlanlan** [comment]
好的

**Comment by xuelangZF** [comment]
有没有一个简单的压力测试呢

**Comment by milanlanlan** [comment]
由于超算又改了接口，现在我还没有实现新的功能接口，所以也没办法进行压力测试

**Comment by xuelangZF** [comment]
如果只是改接口 API 的话，咱们这边的对接应该不难啊，只是改几个 URL 而已。难道又做了其他的一些更改吗？

压力测试没必要等实现新的功能接口才能进行，可以用一些压测工具直接去试 API 的啊。

**Comment by milanlanlan** [comment]
接口的返回结果进行了修改，运行代码部分要从命令拼接改成脚本执行，所以需要重构，具体可以查看刚才的文档和提出的问题

**Comment by xuelangZF** [comment]
这部分重构完了吗？
