### ISSUE TITLE
Web 开发中的测试

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#262]
阅读 《Flask Web开发》，参考里面的测试方法，编写简单的测试用例。（可以参考我们之前出现 Bug 的地方，先对这些部分写测试）

@luozhx

**Comment by xuelangZF** [comment]
测试先往后面放，又有高优先级任务了。

**Comment by luozhx** [comment]
现在只能测试简单的GET请求和POST请求，登陆状态获取有点问题，设置了cookies还是不行。
另外通过测试的标准也很难确定，现在我暂时打算用HTTP状态码进行判断。

**Comment by xuelangZF** [comment]
OK，Web 测试标准确实难确定，你再看看吧

**Comment by luozhx** [comment]
先写了一个简单的框架，你先看看这样写行不行。
以后每个模块的测试往里面放就可以了，不过这个工作量非常大。。

**Comment by xuelangZF** [comment]
改进的地方：

1. 每次可以复制我们仓库里的数据库，在 mysql 新建一个数据库用于测试。
2. 在项目根目录建一个：tests 文件夹，里面放置各个模块的测试文件。
3. 部署 github hooks，使得每次提交时能够自动测试；

你先按上面的要求对一个小的模块做一个完整的测试，整理下测试需要注意的地方，后面看情况再找人来做测试。

@luozhx

**Comment by luozhx** [comment]
好
