### ISSUE TITLE
个人账户信息 Bug

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#268]
在设置个人账户信息的时候出现了一个横向的滚动条，往右拉的时候nav菜单栏和底部栏出现空缺：

![](https://cloud.githubusercontent.com/assets/17507937/21757659/129bc4c0-d66d-11e6-9152-b42d483f84e0.png)

屏幕宽度适配问题！

@Zouzhp3  修复！

**Comment by xuelangZF** [comment]
@ym13349140  什么浏览器？我chrome 没有这个问题

**Comment by ym13349140** [comment]
我用的就是chrome，可能是屏幕大小不一样造成的

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/issues/243 主要用来引用其他 bug issue，总结类似的 bug。

发现 Bug 的话，直接开 issue 就行。

**Comment by ym13349140** [comment]
OK~

**Comment by xuelangZF** [comment]
是的，屏幕宽度变的话，就会出现这个问题了。

**Comment by Zouzhp3** [comment]
收到

**Comment by Zouzhp3** [comment]
已经完成修复。
bug原因：提交按钮的div容器所使用的col-md-offset属性的值过大，导致该容器向右溢出了面板框。

**Comment by xuelangZF** [comment]
提交 f4200ffd930fb75aff2ff1a42a44631ed8a4a519 解决
