### ISSUE TITLE
系统允许多个教师帐户

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#274]
现在我们的站点，不区分教师帐户，任意一个老师都能够看到其他所有老师的课程。

改进：每个老师只能看到自己管理的课程，只能对自己管理的课程进行一系列操作。

可能需要更改数据库，具体 @luozhx  来看下，尽快完成。

**Comment by luozhx** [comment]
除了课程之外，试题，实验，知识点需要区分不同老师吗？

**Comment by xuelangZF** [comment]
你问住我了，😭 。 你觉得区分好还是不区分好啊。

**Comment by luozhx** [comment]
我觉得除了知识点都要分吧。

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/issues/195#issuecomment-268729007  这里我和 @wzl281158150  讨论过。

我感觉知识点让管理员管不太合适，因为这个属于具体知识内容，不是站点的管理。不过老师单独管理属于自己的知识点也不行，因为不同老师的知识点可能重复。

一种折衷方法，每个老师可以管理所有的知识点，可以随意添加知识点，编辑知识点，但是不能随便删除知识点（只有当当前知识点没有内容时，才可以删除）。

这样可以吗

**Comment by luozhx** [comment]
可以，就先按这样写吧

**Comment by xuelangZF** [comment]
👌

**Comment by xuelangZF** [comment]
我新建了一个教师帐户，成功创建了一个课程，但是在后台管理界面并没有看到。

![image](https://cloud.githubusercontent.com/assets/2769831/21879061/3d5ecf52-d8d1-11e6-8ea3-75d6d925b908.png)

看了下数据库，创建的课程并没有指定 user_id。

![image](https://cloud.githubusercontent.com/assets/2769831/21879109/74623606-d8d1-11e6-817c-34634f0d7be7.png)

#Bug

**Comment by xuelangZF** [comment]
此外，编程题目也需要支持多个老师。

**Comment by xuelangZF** [comment]
提交 ae4e68fee54c847bf0bd54e773a9f34739204c2c 完成。
