### ISSUE TITLE
禁止在代码中写入敏感信息

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#275]
@milanlanlan  不要在代码中写入敏感信息，超算的帐  ％％ 户 ，密 ％％ 码都被你泄露了。

![image](https://cloud.githubusercontent.com/assets/2769831/21792245/5398b9e0-d723-11e6-9578-dea57372ccd1.png)

写进系统环境变量，然后用配置文件去读环境变量，类似下面

```
SECRET_KEY = os.environ.get('SECRET_KEY')
```

测试的邮箱帐户、密码写进去就算了，这里的帐户、密码请尽快删掉（最好能够删除版本库中的旧版本的帐户、密码），并将新的帐户、密码写进环境变量，然后在配置文件读。

**Comment by milanlanlan** [comment]
收到！

**Comment by xuelangZF** [comment]
做的怎么样了，没什么难度吧，还没好吗？

**Comment by milanlanlan** [comment]
因为要使用新的api，所以要和超算沟通就比较久了，这是今天问的问题
https://github.com/JiangLiNSCC/eHPC/issues/23

**Comment by milanlanlan** [comment]
此外还有一份文档，如果需要的话我也可以上传

**Comment by xuelangZF** [comment]
什么文档，传来看下吧

**Comment by milanlanlan** [comment]
不知道为什么ZIP文件粘贴不上来，里面有很多文件，我转发到你的邮箱吧

**Comment by xuelangZF** [comment]
嗯，发我邮箱吧。

**Comment by milanlanlan** [comment]
已经发了

**Comment by xuelangZF** [comment]
你把读取帐户、密码的操作放到 **配置文件** `config.py` 中去，这样好处：

* 逻辑比较清楚，在一个地方搞定所有的配置；

另外，把那些环境变量配置的 export 语句，发我邮件一份，我用来部署服务器。

**Comment by xuelangZF** [comment]
**把读取帐户、密码的操作放到 配置文件 config.py 中去**

没看到吗？
