### ISSUE TITLE
关于Google服务的使用

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#28]
搜索建议用 Google， 英文关键词，这样命中率比较高。
本地自己的简单测试可以用 postman（一款chrome插件）。

上面两个都需要绕行 G F W。

推荐方法：
1. 买一个 VPS （可以选择 DigitalOcean，使用我的邀请码注册可以获得 10$。一年300多吧，可以几个人合买 ）
   https://m.do.co/c/8b876daa1875
2. 在 VPS 上搭建 SS 服务器（几行python 命令）
3. 本地 SS 客户端配置（帐号，密码，配置文件）。客户端强烈推荐 surge。

（项目进展期间，可以先使用我的 vps 帐号。）

@all

**Comment by SYSU-Zouzhp** [comment]
我补充推荐一个傻瓜版的修改本地host上google的教程，不需要任何客户端以及费用。
亲测可行

[https://laod.cn/hosts/2016-google-hosts.html](url)
