### ISSUE TITLE
慎用 document.write

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#283]
如果在 一个 js 中引入另一个需要的js文件或者语句，目前做法是利用 document.write ，如下：
 
```
var import_mathjax = '<script type="text/x-mathjax-config">\
                      MathJax.Hub.Config({\
                          skipStartupTypeset: true\
                      })\
                      </script>\
                      <script type="text/javascript" src="https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>';

document.write(import_mathjax);
```

这样不是很好，会出现下面的问题（警告信息），有时候会加载不出来。 @wzl281158150  找找看有没有更好的做法。

![image](https://cloud.githubusercontent.com/assets/2769831/21878860/e8a91a36-d8cf-11e6-9d28-190b6df2bf26.png)

**Comment by wzl281158150** [comment]
还有一种方法就是用js代码生成 script 标签....

**Comment by xuelangZF** [comment]
比较好的做法是哪种？它们有什么区别没有啊

**Comment by wzl281158150** [comment]
并没有说好坏，其实原理应该都是一样的，就是往html写入 script标签

**Comment by xuelangZF** [comment]
嗯，但是document.write 时，我这边半天没有加载。下面警告信息看着很不爽啊，这里有人问过：

http://stackoverflow.com/questions/39610829/a-parser-blocking-cross-origin-script-is-invoked-via-document-write-how-to-ci

**Comment by wzl281158150** [comment]
如果我不写这个的话，那么使用者需要自己在 html中  引用

**Comment by xuelangZF** [comment]
看下  Google 的这篇文章： [Intervening against document.write()](https://developers.google.com/web/updates/2016/08/removing-document-write) 怎么说

**Comment by wzl281158150** [comment]
好，我研究一下

**Comment by wzl281158150** [comment]
![image](https://cloud.githubusercontent.com/assets/22830541/21883575/d2bdd638-d8ea-11e6-867c-08d18dcd6bd8.png)
好像加一个 async就行了

**Comment by xuelangZF** [comment]
👌，简单在下面写一下解释吧。

**Comment by wzl281158150** [comment]
好的

**Comment by wzl281158150** [comment]
使用document.write，浏览器在解释html代码时，会强制性的等待对应资源下载完成。由于用户可能出现网络问题，这会导致整个浏览器处于停滞状态

**Comment by xuelangZF** [comment]
提交 2b687670a7d0c7097f29efab835a8b64c147efc1 修复
