### ISSUE TITLE
编程部分页面设计更改

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#285]
参数设置部分：不用 modal 的，直接在编辑框下面进行设置。

结果反馈直接分为两个栏目，不用tab的方式。直接就显示编译和运行结果。

@milanlanlan

**Comment by milanlanlan** [comment]
请问是直接删去另一个栏目，然后如果编译成功就显示运行结果，失败就显示编译信息吗？

**Comment by xuelangZF** [comment]
我也觉得这样好点，不过老师意思是所有程序结果都是分左右两栏目，左边显示编译结果，右边是运行结果。（编译成功也显示左边的编译信息。）

**Comment by milanlanlan** [comment]
这次提交我是重新clone和fork的，不知道为什么会显示所有文件都被修改过，然后在diff里显示not changed，实际上我修改的文件只有/static/ace.js、 /template/problem/program_detail.html、 /problem/views.py以及/problem/code_process.py四个文件而已。我在web控制台观察到前端参数的传递没有问题，然后对code_process.py也测试过没有问题。

**Comment by xuelangZF** [comment]
你重新开个目录，把仓库拉下来，然后把这四个文件改下提交？

不明白你的 git 为什么这个奇怪，不过你不要把本地的奇怪现象带到公共仓库吧。

**Comment by milanlanlan** [comment]
收到！

**Comment by xuelangZF** [comment]
提交 45d9449a18ef9227e772591c5b886321df722d93 初步完成
