### ISSUE TITLE
更新时间选择插件

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#286]
使用最新版本的 bootstrap-datetimepicker ，好处是选时间更方便。

我已经切换了cdn源，需要更改相关的代码。

@luozhx

**Comment by luozhx** [comment]
![image](https://cloud.githubusercontent.com/assets/22886929/21884900/4114a2ec-d8f0-11e6-9971-7d112f7c493f.png)
哪里切换了？

**Comment by xuelangZF** [comment]
还没提交。。。😳

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/21885020/d99ac0fa-d8f0-11e6-8806-c2e561fbfb40.png)

**Comment by luozhx** [comment]
我之前用的是smalot-bootstrap-datetimepicker不是bootstrap-datetimepicker，CDN改一下就行了

**Comment by xuelangZF** [comment]
我其实看的是这个： http://eonasdan.github.io/bootstrap-datetimepicker/  ，感觉用着更舒服点。

**Comment by luozhx** [comment]
差不多吧，要换也可以

**Comment by xuelangZF** [comment]
现在用的那个，我感觉不是很方便。你如果感觉差不多的话，就先不改吧。这不是大问题。
