### ISSUE TITLE
表单验证提示信息的风格统一

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#292]
表单提示信息的位置有点混乱，如下：

![image](https://cloud.githubusercontent.com/assets/2769831/21915369/7c3f4564-d974-11e6-846d-59524bef7aca.png)

最好统一改为在下面显示，并且开头不要有缩进，不然看着怪怪的。

@ym13349140

**Comment by ym13349140** [comment]
这个有缩进的是parsley.js插件自带的风格，不太好改，在下面统一显示的那些是我自己用JS实现的验证

**Comment by ym13349140** [comment]
他默认验证方式就是在所有的有问题的表单元素下方增加了一个<li></li>元素用于显示提示信息

**Comment by xuelangZF** [comment]
最后一个怎么在上面显示的提示信息？

**Comment by xuelangZF** [comment]
缩进那里，可以改的，我们自定义 CSS 来覆盖它的就行了啊：

![image](https://cloud.githubusercontent.com/assets/2769831/21918655/93ee9218-d98e-11e6-85f9-183850dafe8c.png)

**Comment by xuelangZF** [comment]
关于提示信息的位置，Google 搜 `parsley js info position` 第一条是 Stackoverflow：

[Change the position of parsley-errors-list in parsleyjs](http://stackoverflow.com/questions/30122028/change-the-position-of-parsley-errors-list-in-parsleyjs)

里面有说怎么自定义位置的。

**Comment by ym13349140** [comment]
最后一个因为它是在原本的那个textarea元素下面添加的，textarea没有显示出来，所以提示信息就占了原本那个textarea的位置。

**Comment by xuelangZF** [comment]
最后一个是因为 simplemde 在 textarea 的后面插入了编辑框，而parsely 也是在后面插入，但是比simplemde 的位置偏前了一点。

![image](https://cloud.githubusercontent.com/assets/2769831/21918872/b38ee404-d990-11e6-9cd7-e08438b8c688.png)

所以会先显示 errorlist。不过可以自定义显示的位置的。

**Comment by ym13349140** [comment]
好，我看一下

**Comment by xuelangZF** [comment]
还有选择标签的地方：

![image](https://cloud.githubusercontent.com/assets/2769831/21919154/1ff98a5c-d993-11e6-9e9a-384e422b717f.png)

也存在错乱

**Comment by ym13349140** [comment]
嗯嗯，这里我之前有发现，我待会一起改了

**Comment by xuelangZF** [comment]
提交 6d02aba616dc98a462f53dc6c37035fee3334e6b 完成。
