### ISSUE TITLE
表单验证有混乱

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#293]
题目管理中的表单验证很有问题，简单题目写了答案，还是提示该字段必填。

![image](https://cloud.githubusercontent.com/assets/2769831/21919291/2271e5bc-d994-11e6-8a96-8ee80d03cbf5.png)

还有题干有时候没写，也是可以成功提交。

**Comment by ym13349140** [comment]
这个问题我写的时候也发现了，写了答案提示信息还显示是因为parsley监测的是textarea元素的变化，但其实我们是在markdown编辑框里编辑了信息，而markdown编辑框的信息只有在提交的时候才会赋值给textarea元素或者直接提交到后台，所以parsley监测不到编辑框内容的变化，它只会在再次点击了提交按钮的时候它才会再次判断textarea值是否为空。

**Comment by ym13349140** [comment]
那个题干没写还能提交的是哪种题呀，我看一下，有可能是漏写了。

**Comment by xuelangZF** [comment]
填空题目，对于一个题目，如果第一次通过`编辑`进去，删除现有的内容，然后点保存，就能保存下来。

![image](https://cloud.githubusercontent.com/assets/2769831/21919419/4024738a-d995-11e6-8600-2fb16a71d18f.png)

**Comment by ym13349140** [comment]
好像是，我看一下是哪里的问题修复一下吧。

**Comment by xuelangZF** [comment]
👌

**Comment by ym13349140** [comment]
找到问题了，应该所有的题目编辑部分都有这个问题，是edt定义位置的关系，在引入的JS文件中定义的edt好像parsley检测不到它的变化，我之前写的时候应该就是出现了这个问题，所以才把所有的edt定义直接放到了html文件中，然后上次忘了这回事结果又把edt给挪回JS文件中去了。

**Comment by xuelangZF** [comment]
提交 6d02aba616dc98a462f53dc6c37035fee3334e6b 完成。
