### ISSUE TITLE
完善微信公众号

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#295]
微信公众号，推送图文信息的编辑后台。

二维码扫码加入课程的逻辑更改，具体流程稍后给出。

@wzl281158150

**Comment by wzl281158150** [comment]
## 关于后台老师主动推送消息问题
实现想法：
通过调用微信提供的【群发接口】api进行【定制的】【主动的】群发，由于后数据中有用户绑定的微信号openid，故提取所有的openid调用api发送群发消息即可。
问题：
该接口限制较大，首先订阅号无该接口使用权限，只有【认证后的服务号】拥有权限，同时服务号群发次数有限制，根据[该博客的解释](http://www.cnblogs.com/txw1958/p/weixin-mp-mass-send.html)，每个用户每个月只能收到4次群发消息，同时后台调用微信接口次数也有限制，难以满足定制需求。

以目前状态个人订阅号：

1. 只能通过微信公众平台网页端封装好的工具，来手动推送【平台消息】给予所有用户，该消息一般为平台更新的消息，每【天】只有1次（若是服务号，则每个【月】4次）。

2. 当用户主动发送消息给公共号时公众号自动回复内容，必须在5秒内回复，否则微信不会转发给用户，该接口无次数限制。（已用该权限实现：用户发送【绑定】二字，后台判断当前微信号是否绑定ehpc帐号来回复不同内容，内容中会提供【绑定】或者【解绑】的连接给用户，我们可以使用这个接口，当用户需要获取自身ehpc帐号消息的时候，给用户发送其需要的信息）

可能的解决方式：

1. 通过研发定制的app（难度较大）
2. 通过短信通知的方式（额外增加成本）

**Comment by xuelangZF** [comment]
👌，明白了

**Comment by xuelangZF** [comment]
二维码扫码加入课程的逻辑：

> 在学生看到的课程界面中，点加入课程时，会弹出二维码，然后同学微信扫码，在微信中填写一个表单（手机号码等信息，服务器会保存这些信息）后才能加入课程。

我还没明白为什么这样，先不急着动手吧。
