### ISSUE TITLE
Nginx 设置静态资源版本，避免缓存

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#296]
静态资源更新后，浏览器可能因为缓存的原因不能及时更新。

为了解决这个问题，一般做法是在请求静态资源的URL加入 `?v=1.0` 的版本号信息。我们可以用 Nginx 为所有服务器上的静态资源请求链接加上版本号信息，从而强制客户浏览器更新静态资源。

@Zouzhp3

**Comment by Zouzhp3** [comment]
收到

**Comment by xuelangZF** [comment]
进展怎么样了？这个应该很快搞得定了，我有新任务要分配给你了。

**Comment by Zouzhp3** [comment]
调研到了解决方案，就是利用Nginx的重写URL机制。不过目前还在虚机上装Nginx试一下。

**Comment by xuelangZF** [comment]
嗯嗯，nginx 配置文件中重写 URL，加入版本信息就行了。搞定的话告诉我，我给你服务器权限。

**Comment by xuelangZF** [comment]
今天搞定吗？   @Zouzhp3

**Comment by Zouzhp3** [comment]
师兄，给我服务器权限吧

**Comment by Zouzhp3** [comment]
另外最近网站一登录就报Internal Server Error

**Comment by xuelangZF** [comment]
数据库的问题，我现在修改

**Comment by xuelangZF** [comment]
提交 e73208803bd8f2148e66dbd000546eb2bd903970 解决了静态资源的缓存问题
