### ISSUE TITLE
登录用户首页的定制化

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#297]
目前站点首页 `/` 是站点内容的展示，和没有登录时的内容是一样的。

现在需要为登录用户的首页进行定制化，包括：

- 只显示当前正在进行的课程；
- 显示最近参与的话题讨论；
- 显示最近做过的题目；
- 显示最近进行的小试验任务；

并且这些入口最好能够直接链接到上次完成的地方，可以通过这些链接直接继续之前的学习。

@wzl281158150

**Comment by wzl281158150** [comment]
师兄是不是弄错了.....

**Comment by xuelangZF** [comment]
已修改

**Comment by xuelangZF** [comment]
首先 登录用户首页不要显示轮播图，然后下面的在线课程，试题中心 之类的就不要显示了。

建议另外写一个 template 页面，专门用来放定制化的主页，不要在  `eHPC/templates/main/index.html` 里面改了，这两个完全分开。

**Comment by wzl281158150** [comment]
这样的话，新用户的首页会是空的，我是想新用户看到的应该是未登录一样的页面才这样写的

**Comment by xuelangZF** [comment]
你这里的新用户其实就是指没有在站点进行任何活动的用户。

```
{% if user_courses or user_topics or user_question or user_program or user_challenges %}
```

对于这种用户，定制化首页可以像其他用户一样，列出每项的标题，只是内容显示“还没有开始学习。。” 之类的内容即可。

**Comment by wzl281158150** [comment]
其实我就是觉得只显示标题不好才就算对于有记录的用户只显示他有记录那个类别的标题，比如他没加入任何课程，那么就不显示  已加入的课程这一项

**Comment by xuelangZF** [comment]
或者，如果还没有加入的话，就推荐一门课给他？没有做题，就给他题目的入口地址？就是做一个简单的引导。

此外，就算新用户显示初始的首页的话，我觉得也要把定制化首页单独放到一个html中去，然后在 view 中判断返回哪个template。（因为逻辑上这两个页面没关系，需要控制层判断返回哪个页面的）

**Comment by wzl281158150** [comment]
分文件可以，不过做引导给入口，其实就跟未登录页面的一样啊…   我可以改成对于一条几率都没有的用户认为是新用户，显示的页面是正常首页，但凡有一条记录的用户，显示定制页面，师兄你看怎么样

**Comment by xuelangZF** [comment]
可以，就这样吧

**Comment by xuelangZF** [comment]
提交 c8d86cadf34e59a7852c363cf1e9e0d44672c4cc 初步完成
