### ISSUE TITLE
教师的后台管理前端页面进行美化

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#298]
目前后台管理都是简单的列表的样子，看上去有点丑。

需要为每项管理改为更加好看的图表形式。比如课程管理时，把老师管理的的课程用小框的的形式列出来，类似学生端的页面：

![image](https://cloud.githubusercontent.com/assets/2769831/21927632/6d2478ae-d9c1-11e6-886e-5c7e961ecce3.png)

不过在图标下面给出操作（删除、编辑、二维码）的入口。

其他部分，包括题库、虚拟实验室、知识点部分也是这样的思路，不过不一定用图，也可以用一些Tag的页面元素。

并且在管理的首页，http://127.0.0.1:5000/admin/teacher/ ， 给出老师管理的内容概要（目前是空白页面）。

@luozhx

**Comment by xuelangZF** [comment]
开始做了吗

**Comment by ym13349140** [comment]
我这边前两天网络一直有问题，今天刚连上，今天已经开始写了。

**Comment by xuelangZF** [comment]
进展如何？ @ym13349140

**Comment by xuelangZF** [comment]
@luozhx 来做这个吧。

**Comment by xuelangZF** [comment]
提交 539e6af265ba592bbc97ba4f74e55b31268ec951 初步完成
