### ISSUE TITLE
document.write async 引起的加载问题

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#299]
https://github.com/xuelangZF/ehpc/issues/283#issuecomment-272124679 中关于async的引入，导致了 http://a002.nscc-gz.cn:10165/group/topic/12/ 页面出错。

这是因为异步加载 MathJax 时，没有加载成功就会执行到 latex_support 的语句中：

```
 MathJax.Hub.Queue(["Typeset", MathJax.Hub, 'latex-render-area']);
```

这时候不知道 MathJax 在哪里定义，因此会导致 JS 错误。

@wzl281158150  修复。

**Comment by wzl281158150** [comment]
只需将custom_simplemde.js文件中的 async 删除即可

**Comment by xuelangZF** [comment]
我知道这样可以啊，但是这样也是有问题的（ #283 说过）。

我们要找一个更好的方法，而不是应付。

**Comment by xuelangZF** [comment]
感觉这个应该是前端模块化打包的一个问题，可以看看 [requirejs](http://requirejs.org/docs/start.html) 或者是 webpack。

**Comment by wzl281158150** [comment]
刚刚我以为是另一个问题，不是这个，那个问题是：对于本地文件使用async是错误的

**Comment by xuelangZF** [comment]
还没有找到修复方法吗？

**Comment by xuelangZF** [comment]
你提交一个 pull request，解决下这个问题。 @wzl281158150   
暂时先按照咱们当时微信上的方法吧。

**Comment by xuelangZF** [comment]
JavaScript 程序执行的时间线：

1. Web 浏览器创建 Document 对象，并且开始解析 Web 页面，解析 HTML 元素和它们的文本内容后添加 Element 对象和 Text 节点到文档中。在这个阶段 document.readystate 属性的值是「loading」
2. 当 HTML 解析器遇到没有 async 和 defer 属性的 script 元素时，它把这些元素添加到文档中，然后执行内或外部脚本。这些脚本会同步执行，并且在脚本下载和执行时解析器会暂停。这样脚本就可以用 document.write() 来把文本插入到输入流中。解析器恢复时这些文本会成为文档的一部分。同步脚本经常简单定义函数和注册后面使用的注册事件处理程序，但它们可以遍历和操作文档树，因为在它们执行时已经存在了。这样，同步脚本可以看到它自己的 script 元素和它们之前的文档内容
3. 当解析器遇到设置了 async 属性的 script 元素时，它开始下载脚本文本，并继续解析文档。脚本会在它下载完成后尽快执行，但是解析器没有停下来等它下载。异步脚本禁止使用 document.write() 方法。它们可以看到自己的 script 元素和它之前的所有文档元素，并且可能或干脆不可能访问其它的文档内容
4. 当文档完成解析，document.readyState 属性变成「interactive」
5. 所有有 defer 属性的脚本，会按它们在文档里出现的顺序执行。异步脚本可能也会在这个时间执行。延迟脚本能访问完整的文档树，禁止使用 document.write() 方法
6. 浏览器在 Document 对象上触发 DOMContentLoaded 事件。这标志着程序执行 从同步脚本执行阶段转换到了异步事件驱动阶段。但要注意，这时可能还胡异步脚本没有执行完成
7. 这时，文档已经完全解析完成，但是浏览器可能还在等待其它内容载入，如图片。当所有这些内容完成时，并且所有异步脚本完成载入和执行，document.readyState 属性改变为「complete」，Web 浏览器触发 window 对象上的 load 事件
8. 从此刻起，会调用异步事件，以异步响应用户输入事件、网络事件、计时器过期等

使用document.write，浏览器在解释html代码时，会强制性的等待对应资源下载完成。由于用户可能出现网络问题，这会导致整个浏览器处于停滞状态，chrome浏览器会报警告。如果直接写在页面，浏览器同样是阻塞的，但是浏览器不会警告，但是这样需要在每个页面添加js引用。

《JavaScript 权威指南： Web 浏览器中的 JavaScript》   
[读书笔记 13 - Web 浏览器中的 JavaScript](https://keelii.github.io/2016/07/14/javascript-definitive-guide-note-11/)
