### ISSUE TITLE
配置文件中最好把敏感数据去掉

### ISSUE THREAD

**Issue by hellorocky** [xuelangZF/ehpc#3]
账号密码....

**Comment by xuelangZF** [comment]
对，有 @milanlanlan  邮箱的帐号密码。

**Comment by xuelangZF** [comment]
我的写在环境变量的可以行，不知道 @milanlanlan  有木有解决这个问题。

**Comment by milanlanlan** [comment]
那个邮箱我是随便注册的，当时为了方便调试直接硬编码进去了，完成之后删掉那部分并且恢复注释部分就可以了。

**Comment by xuelangZF** [comment]
哦哦，那没事，以为是你自己用的邮箱呢
