### ISSUE TITLE
尝试引入前端模块化工具：webpack

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#300]
所有小伙伴请先阅读 基于 [Webpack 的前端资源构建方案](https://lifei.github.io/2015/12/20/webpack/)，对 [webpack](https://webpack.js.org/) 有一个大致的了解。Webpack 的好处：

* 支持静态文件名 hash 化，支持 hash 后的文件名及路径注入到后端模版文件中；此特性可以发布所有静态文件到一个统一的目录，由 nginx 直接接入，消除静态文件的版本概念，使得静态资源的上线更加方便、安全，无需回滚。
* 先进的依赖处理机制；( 类似 #299 这种问题)
* 支持静态文件自动合并，能够很好的处理公共库和组件文件的合并；多页面应用更好的复用公共组件，利用 HTTP 协议缓存机制。

然后 @ym13349140  请深入学习下 webpack，看下我们的项目引入 webpack 的相关问题：

* 工作量是否很大？
* 是否有足够的好处？
* 其他人学习成本大吗？

@Zouzhp3 @wzl281158150 @luozhx 

（给本条issue点👍或者👎，来投票是否使用webpack）

**Comment by xuelangZF** [comment]
@ym13349140  有看吗

**Comment by ym13349140** [comment]
收到！

**Comment by xuelangZF** [comment]
有什么进展吗？ @ym13349140

**Comment by xuelangZF** [comment]
@ym13349140 最近还有看吗
