### ISSUE TITLE
前端 UI 看上去不要太粗糙

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#305]
编程题目编辑部分现在长这样子：

![image](https://cloud.githubusercontent.com/assets/2769831/22063052/bcd1251a-ddb7-11e6-8ef9-a9e2f40a5bce.png)

不知道其他人怎么看（ @ym13349140  @Zouzhp3 @wzl281158150 @luozhx  ），我觉得太粗糙，需要改进下。

@milanlanlan  学点基础 HTML、CSS，把页面改下。

参考 https://github.com/xuelangZF/ehpc/issues/157

**Comment by xuelangZF** [comment]
请问改好了吗？

**Comment by xuelangZF** [comment]
请问改好了吗？  @milanlanlan

**Comment by milanlanlan** [comment]
你好，寒假我没有去改，所以现在还没改好，然后昨天老师让我去整理mpi编程的知识点，我整理完后会尽快学习修改前端

**Comment by xuelangZF** [comment]
算了，我找别人改了。不是多难的东西，你整理 mpi 编程知识点吧。

**Comment by xuelangZF** [comment]
@ym13349140  你来修改一下下拉选项框的样式吧。

**Comment by milanlanlan** [comment]
惭愧，不好意思

**Comment by xuelangZF** [comment]
提交 13ac5e7de45c941e303c8e1dea173cb7ea4db140 初步完成
