### ISSUE TITLE
虚拟实验室编程框和运行结果

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#310]
虚拟实验室部分，针对每个知识点，左边为内容展示，右边上边栏目为代码区域，下面栏目为代码运行结果区域，效果类似 http://www.hubwiz.com/class/570dce425fd193d76fcc723d 。

![image](https://cloud.githubusercontent.com/assets/2769831/23093005/7b1acd6a-f612-11e6-9207-a688dce6576e.png)

@Zouzhp3 

注意：

1. 目前虚拟实验室不用考虑选择题和问答题，只考虑并行编程题；
2. 并行编程题目的编译和执行是用超算的接口。
3. 每个知识点中，代码的编辑框可以预先设置默认的代码。（有时候只需要填部分核心代码即可）

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/pull/309 中为什么要对 `migrations/env.py` 进行更改， 并添加了 `migrations/versions/b3c47784b859_.py` 。你的代码中没有更改 model.py，不用重新migrate的啊。 @Zouzhp3

**Comment by Zouzhp3** [comment]
收到。

关于对 migrations 的更改，我下次会注意。

**Comment by xuelangZF** [comment]
👌。对了，文件管理和访问测试也不用的。

**Comment by xuelangZF** [comment]
你更改下，然后重新 pull 一个呗

**Comment by Zouzhp3** [comment]
OK~

**Comment by Zouzhp3** [comment]
![1487491792 1](https://cloud.githubusercontent.com/assets/22606175/23100506/eadff71e-f6bd-11e6-9b9b-f93b94262485.jpg)

目前做成了这个效果，还有什么要改进的地方吗？

**Comment by xuelangZF** [comment]
我明天看下哈。和超算的对接，可以参考目前题库的编程题部分。

**Comment by xuelangZF** [comment]
你提交一下哈。  @Zouzhp3

**Comment by Zouzhp3** [comment]
OK，刚刚上课回来，再过半小时就提交
