### ISSUE TITLE
轮播图以及登陆图层

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#315]
参考 https://www.okcoin.cn/  来设计首页的轮播图，以及登陆图层。

设计方法：图片大小为 2000px * 500px，显示时，图片高度为 100%。宽度超出屏幕宽度像素值时，裁剪中间核心部分的图片。登陆图层悬浮在轮播图上面，处于右侧位置（参考okcoin中位置样式）

所以，对于轮播图片，要求两边有足够的留白，能够适应小屏幕浏览器，并且不能使登陆框遮盖图片中的主要元素。（如下面的大小图所示效果）

![image](https://cloud.githubusercontent.com/assets/2769831/23112963/9c4a446c-f76f-11e6-870e-9cb2124ddb66.png)

![image](https://cloud.githubusercontent.com/assets/2769831/23112982/c634b08c-f76f-11e6-9479-da94f87ba40b.png)

目前的轮播图，加上登陆图层后，会遮盖部分内容。@ym13349140 请适当修改。

**Comment by ym13349140** [comment]
收到！

**Comment by ym13349140** [comment]
关于登录图层的位置，有一个问题就是OKCoin是没有可以左右翻页的箭头的，如果按照它那边的位置来放置我们的登录框会将向右翻页的箭头挡住，所以我才在它的基础上左移了一点距离

**Comment by xuelangZF** [comment]
嗯嗯，我们也把那个箭头去掉吧，加了登陆图层后，再有箭头显得太赘余了

**Comment by ym13349140** [comment]
好的~那我这边直接删除箭头部分的代码吗？

**Comment by xuelangZF** [comment]
嗯嗯，你直接删除吧

**Comment by xuelangZF** [comment]
提示信息有点错位

![image](https://cloud.githubusercontent.com/assets/2769831/23115032/587a210e-f77d-11e6-9954-6b2230532e9f.png)

**Comment by xuelangZF** [comment]
提交 930c6fe7cd7f566e6131e82b0d8a84d01123bcd1 修复提示信息错位
