### ISSUE TITLE
虚拟实验室编程题目后台处理

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#318]
https://github.com/xuelangZF/ehpc/issues/310 初步完成了虚拟实验室前端页面，现在需要后台对题目进行编译，运行，运行结果直接反馈到下面的状态栏。

注意：

* 目前虚拟实验室不用考虑选择题和问答题，只考虑并行编程题；
* 并行编程题目的编译和执行是用超算的接口。
* 每个知识点中，代码的编辑框可以预先设置默认的代码。（有时候只需要填部分核心代码即可）

@wzl281158150 来完成。尽量周三下午有个初步的版本。

@Zouzhp3   处理超算对接的部分，可以参考题库中题目的后台处理过程。[超算接口说明文档](https://github.com/xuelangZF/ehpc/wiki/%E8%B6%85%E7%AE%97%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3)

**Comment by xuelangZF** [comment]
1. 超算环境变量的读取。

code_process.py 文件里面读取环境变量的做法是不对的（创建ehpc_client时根本无法读取到 base_url之类的配置），我们需要在 config.py 里面读取，然后项目中其它地方都可以引用。

```
# code_process.py 
# 基本的请求地址
base_url = os.environ.get("EHPC_BASE_URL")
# 表示请求功能的地址
login_url = "/auth"
# 异步获取功能的地址
```

不要在 view 中通过 `myPath = os.environ.get("EHPC_PATH")` 来读取配置了。

2. 将提交代码、获取结果的过程进一步抽象。

![image](https://cloud.githubusercontent.com/assets/2769831/23165963/8ddb60c2-f879-11e6-9b56-b357c90c6a85.png)

一个函数，输入为代码，以及一些运行配置，输出为运行结果。这样可以和 view.py 分离开，并且可以同时用于虚拟实验室和题库中去。

@wzl281158150

**Comment by xuelangZF** [comment]
第1点在 https://github.com/xuelangZF/ehpc/issues/275#issuecomment-274233481 提到过，只不过 @milanlanlan  没注意到而已。

**Comment by Zouzhp3** [comment]
我有点不明白我和 @wzl281158150 各自分工哪部分，是我做后台提供接口吗

**Comment by xuelangZF** [comment]
嗯，你负责后台超算的接口部分。具体来说，目前你负责将上面 1，2 搞定，然后 @wzl281158150 就可以用你的函数来完成 view 的改写。

**Comment by milanlanlan** [comment]
我的错，我以为写在那里也可以读取到

**Comment by xuelangZF** [comment]
@Zouzhp3  你的代码本地没有问题，可以运行？

```
(ehpc)➜  ehpc git:(master) python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    app = create_app(os.getenv('EHPC_CONFIG') or 'default')
  File "/Users/feizhao/dropbox/ehpc/eHPC/__init__.py", line 42, in create_app
    from .problem import problem as problems_blueprint
  File "/Users/feizhao/dropbox/ehpc/eHPC/problem/__init__.py", line 8, in <module>
    from . import views
  File "/Users/feizhao/dropbox/ehpc/eHPC/problem/views.py", line 9, in <module>
    from ..problem.code_process import submit_code
  File "/Users/feizhao/dropbox/ehpc/eHPC/problem/code_process.py", line 36, in <module>
    class ehpc_client:
  File "/Users/feizhao/dropbox/ehpc/eHPC/problem/code_process.py", line 37, in ehpc_client
    def __init__(self, base_url=TH2_base_url, headers={}, login_cookie=None, login_data=TH2_login_data):
NameError: name 'TH2_base_url' is not defined
```

错的有点明显和低级了。我来改这一块吧。

**Comment by Zouzhp3** [comment]
收到，不好意思

**Comment by xuelangZF** [comment]
提交 8b9b6804160b2f14e8a50c81ce237d7294b36579 初步完成。。
