### ISSUE TITLE
虚拟实验室后台管理变更

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#321]
虚拟实验室的后台教师管理部分，需要做相应的更改。

不再需要选择题目，变为手动输入编程题目的默认代码（可以为空）和答案代码。

@wzl281158150  熟悉虚拟实验室，所以完成这块吧。

**Comment by xuelangZF** [comment]
今天可以搞定的吧？ @wzl281158150

**Comment by wzl281158150** [comment]
这部分代码之前并不是我写的，需要一点时间

**Comment by xuelangZF** [comment]
哦，对，之前是罗震霄的。尽快哈。

**Comment by wzl281158150** [comment]
我不能保证今天一定能，我尽力

**Comment by wzl281158150** [comment]
师兄，有问题这个应该不是这样的，对于新的这个表lab program应该单独有后台管理页面，这边与之前一样 仅仅是 引用就行了

**Comment by xuelangZF** [comment]
提交 a9d4a5b5b6f08064f8fc8e8d03b850446e1b5054 完成
