### ISSUE TITLE
自定义首页中，空白内容的处理

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#322]
用户没有活动时，如何显示好？

下面这样不合适吧。

![image](https://cloud.githubusercontent.com/assets/2769831/23166674/7f20c754-f87c-11e6-96e5-c903af4bbb12.png)

@wzl281158150

**Comment by wzl281158150** [comment]
没有活动应该不显示自定义首页

**Comment by xuelangZF** [comment]
嗯，阔以。但是上面还是有一个空白的 已加入课程。用户为 1@qq.com 密码 1，你可以看下

**Comment by wzl281158150** [comment]
哦哦，我去看一下

**Comment by wzl281158150** [comment]
师兄，我是这里少了 limit(8).all()这句，不加这句current_user.courses输出其实就是一句sql语句，但是在前端是能当成字典使用的，但是当没有课程的时候，正常user_courses应该是none，但这样写user_courses则还是sql语句，这里我已经修改，上面的groups和article也是缺了.all()的，不知道是谁写的，我一并修改了
![image](https://cloud.githubusercontent.com/assets/22830541/23167307/dacb8e8e-f87e-11e6-85a4-e0b670627d47.png)

**Comment by wzl281158150** [comment]
或者师兄你直接修改就好

**Comment by wzl281158150** [comment]
上面说错了，没有记录是，出来的是[] 不是 none

**Comment by xuelangZF** [comment]
好的，我下次顺便交了
