### ISSUE TITLE
老师只能管理自己的题目

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#323]
https://github.com/xuelangZF/ehpc/issues/274 中每个老师对题目的管理是独立的，目前我用 1@qq.com 这个新教室去管理题目的话，如下所示：

![image](https://cloud.githubusercontent.com/assets/2769831/23166830/1a837854-f87d-11e6-8066-bdb5f6aba7e6.png)

可见没有做好题目的分离。

@luozhx 修复

**Comment by luozhx** [comment]
已修复

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/23201097/e5e22d2a-f912-11e6-8fbe-690e617a1bc3.png)

点开题目是没有了，不过分类下面还显示有数字。

```
<div class="col-sm-6 col-md-4 ">
    <a style="text-decoration: none;" href="{{ url_for('admin.question_filter_by_classify', question_type='choice', question_classify=c.id) }}">
    <div class="admin-item">
        <div style="padding-top: 40px;font-size: 20px">{{ c.name }}</div>
        <div class="info">共有 {{ c.questions.count() }} 题</div>
    </div>
    </a>
</div>
```

`共有。。题` 这里没有过滤！
