### ISSUE TITLE
完善超算接口的封装

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#333]
虚拟实验室的程序中目前返回的内容中信息没有分类，全部堆在一起。

![image](https://cloud.githubusercontent.com/assets/2769831/23587689/d3dcabf4-01ec-11e7-8e68-5b47362516d7.png)

要对返回信息进行规格化输出，比如：

```
程序运行结果：
...
运行时间信息：
...
```

@Zouzhp3

**Comment by Zouzhp3** [comment]
OK~

**Comment by xuelangZF** [comment]
你做的如何了？明天下午前给我一个版本吧

**Comment by Zouzhp3** [comment]
发现目前超算接口的提交任务部分有了大改，返回值也可能改变了。可否等雨潇那边更新完后再提交此任务？

**Comment by xuelangZF** [comment]
嗯嗯，等雨潇更改完再完善吧

**Comment by xuelangZF** [comment]
@Zouzhp3  和 @milanlanlan  沟通下，解决这个问题

**Comment by Zouzhp3** [comment]
收到

**Comment by milanlanlan** [comment]
好的，其实那些多余信息是因为我加上了打印时间的函数，如果不需要的话直接删去即可，还有什么问题也可以来跟我讨论
