### ISSUE TITLE
注册流程 Bug

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#336]
首页注册新用户之后，会出现类似下面的界面：

![image](https://cloud.githubusercontent.com/assets/2769831/23694200/72b4bec4-0413-11e7-9209-b3b5e7eb534c.png)

刚注册的话，应该是没有浏览任何知识点的，不知道为什么会出现这种问题。

定制化首页：  https://github.com/xuelangZF/ehpc/issues/297  

PS：新注册用户头像应该是  /static/upload/avatar/none.jpg  ，现在的新注册头像地址错误。

@luozhx 修复。

**Comment by xuelangZF** [comment]
服务器上代码更新后，仍然存在这个问题。

![2017-03-08 5 33 25](https://cloud.githubusercontent.com/assets/2769831/23698149/6f1a012c-0425-11e7-893c-ad18868ed525.png)

**Comment by luozhx** [comment]
师兄你在本地测试会有这个问题吗？

**Comment by xuelangZF** [comment]
本地并不会。。。

**Comment by xuelangZF** [comment]
Fixed！

user_question = UserQuestion.query.order_by(UserQuestion.last_time.desc()).limit(5).all() 

没有过滤！

本地没有出问题是因为本地的 user_question 是空的。
