### ISSUE TITLE
邮箱服务器更改

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#337]
我们发送邮件的邮箱，改为使用学校的邮箱服务器。（考虑先用个人的邮箱地址）

之前一直用的 @milanlanlan  的 sina 邮箱。

同时调研下可否使用 https://github.com/mattupstate/flask-mail 模块来发送邮件。

@luozhx

**Comment by luozhx** [comment]
目前使用的就是flask-mail模块

**Comment by xuelangZF** [comment]
嗯嗯，新浪的邮箱服务挂掉了，怪不得一直发送不了邮件。换成 学校的邮箱吧。

**Comment by xuelangZF** [comment]
今天把这个问题解决吧。  晚上看下重置邮件的效果

**Comment by luozhx** [comment]
我在本地测试是正常的啊，新浪的邮箱服务没有问题
但是在服务器上就没法收到邮件

**Comment by xuelangZF** [comment]
那是怎么回事啊？

**Comment by luozhx** [comment]
我部署在阿里云上也是可以正常收到邮件的。
是不是服务器那边有什么限制？

**Comment by xuelangZF** [comment]
应该是云主机上SMTP端口没有开放。
