### ISSUE TITLE
虚拟实验室编程题目出错

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#342]
在线版本编程题目 post 提交时，会返回 503 错误。

本地测试时，并没有问题。

**Comment by lijiang2014** [comment]
昨天下午５点到现在，系统一直处于维护状态，给你们用的其中一个节点（172.16.23.19:8010）还尚未恢复。
针对这种问题，我考虑通过多一层代理来减少影响。　我过会儿会在其他的节点上先将服务恢复，虽然（172.16.23.19:8010）用不了，恢复完成后，代理ＩＰ　(10.133.100.40:8010) 应该是可以访问的。　

另外ＡＰＩ　的版本在本周会有一次升级　（升级完后会更稳定的提供服务，可降低单点故障的影响），其中有部分接口有变，你们那边谁来对接？

**Comment by lijiang2014** [comment]
@xuelangZF 你们今天的测试任务重吗？　如果可以的话，我今天再将新版本的测试多测试修改一些后就直接部署新的了　？

**Comment by xuelangZF** [comment]
OK。没问题，你搞好了再给我新的接口就行。

**Comment by lijiang2014** [comment]
现在还是用开发环境的后端ＡＰＩ吧，代理ＩＰ　还是原来那个　　　(10.133.100.40:8010)　。如果要直连，　就用　10.133.100.40:8000 . ＡＰＩ　接口有些更新，你们的代码可能也得更改，参考　：　https://github.com/JiangLiNSCC/eHPC/wiki/Update-List



如果需要使用生产环境的部署提前通知我一下吧。　另外关于ＡＰＩ　有哪些建议也请多提。

**Comment by xuelangZF** [comment]
@milanlanlan 根据 wiki： https://github.com/JiangLiNSCC/eHPC/wiki/Update-List 更新下我们的接口代码和我们的接口 wiki。

**Comment by milanlanlan** [comment]
你好，我对更新有一些地方不是很理解，为免引起错误希望先问一下：

首先，在auth登录后生成 .newt_cookies 文件的意思是在登录后还需要去获取.newt_cookies作为进一步操作的cookies吗？但是生成后去获取这个文件应该也需要cookies吧？是我哪里理解错了吗，这部分应该怎样修改呢？

其次，在我的理解上，api server应该是你们那边开的服务器，worker node应该是最后程序运行的节点吧，我不是很明白我们这边应该怎样控制这之间的文件传输呢？或者说，我们这边应该修改的地方是哪里？

最后，我的理解是可以通过直接配置jobconf参数来完成调用脚本，不需要自己手动编写对吗？然后返回值有两个id，但是我看两个id对应的内容大部分是一样的，不知道这又是什么意思呢？

打扰了，谢谢回答！

p.s. 所以我们需要使用10.133.100.40:8010这个ip而使用不了172.16.23.19:8010这个ip是吗？
@lijiang2014

**Comment by milanlanlan** [comment]
你好，我简单地测试了以下，以下是一些反馈：

首先我用以前的代码直接跑了一下，好像登录和上传、下载部分不需要做什么修改就可以正常返回了；

然后第一个出错的地方是编译的部分。出现了一个很奇怪的错误：
`error: expected a declaration...`
这个问题奇怪是奇怪在我分别使用了三个不同的mpi、openmp和c++程序，并且这三个程序都是用以前的接口可以正常编译运行的。
而且，三个程序都是出错在第一行，也就是` #include <stdio.h>` 这句。据我所知，一般来说，这个错误会出现在头文件包含顺序冲突或者声明错误的情况下，但是这次是以前可以正常编译的程序，并且我包含的头文件一般只有两个，<stdio.h>和<mpi.h>，应该不存在这种冲突才对。
不知道是不是我哪里操作错误了呢？

最后，由于之前应该有编译成功的文件留在那边，所以我跳过编译直接测试脚本运行的部分。
总的来说，问题不是很大，就是表示任务的"status"的结果之一好像从"Completed"变成了“Success”？所以我这边一直卡住了，不知道除了"Success"和"Pending"还有什么状态呢？
此外，还是会不时出现长久没有获取到文件后返回`async connection time out.`的情况。

谢谢！

**Comment by lijiang2014** [comment]
*  .newt_cookies , 文件传输 ， 等等这些更新和外部调用无关， 你们按之前的来用就行了。 
*  172.16.23.19:8010 是之前部署的IP ， 因为我这边有时候需要重新部署， 你们这个IP 要换比较麻烦，所以我额外配置了个代理的IP  10.133.100.40:8010 ， 你们现阶段用这个就好。 
* 编译通过不了你们能给我个完整的测试用例看下吗？  我自己测试没发现什么问题。
* 返回值为了方便只定义了这几种（SLURM  自身的状态标志太多了）： 
      * Running 
      * Success
      * Failed 
      * Pending   排队
      * Suspended  挂起（一般为运行中，管理员为了进行系统维护，将所有作业挂起（进程接受了SIGSTOP 信号，挂起恢复后，进程接受 SIGCONT , 返回 R 状态 ））

**Comment by lijiang2014** [comment]
所以前端在检测到状态变成 Success 或 Failed 后再去获取结果文件比较好。

**Comment by milanlanlan** [comment]
好的，我今晚回去试试！

**Comment by lijiang2014** [comment]
``` 
[2017-03-11 15:41:32,051: WARNING/Worker-161] command "cd /HOME/sysu_hpc_dwu_1/project/ehpc;mpicc -o ab.out mpicc_demo.c", exit
: 2 <br> b'mpicc_demo.c(1): error: expected a declaration\n  {"error": "", "status_code": 201, "status": "ACCEPT", "output": "4
b81630f-25d8-4380-a0bb-22e4d387642e"}\n  ^\n\ncompilation aborted for mpicc_demo.c (code 2)\n'
[2017-03-11 15:41:32,057: INFO/MainProcess] Task command.adapters.celery_adapter.execute_task[ebbd1284-23cf-41d3-88ba-7dcf4918731d] succeeded in 0.48252473771572113s: ['sysu_hpc_dwu_1', {'retcode': 2, 'error': 'mpicc_demo.c(1): error: expected a declaration\n  {"error": "", "status_code":...
```

**Comment by lijiang2014** [comment]
我看了一下，是上传 mpicc_demo.c 这部分出了问题。

**Comment by lijiang2014** [comment]
上传文件的这个是个BUG ， 刚刚修复……

**Comment by milanlanlan** [comment]
好的，我测试了一下，可以跑通，不过又出现了一点问题。

第一次是可以正常跑没有问题的，但是同样的代码第二次运行会出现
`keyerror: tmpdata["output"]["status"][jobid]...`
然后我就将整个tmpdata打印出来，发现返回的数据的key是 "State"，然后我再重复了几次，返回的数据会不断变化，有时候会出现很多数据，里面对应的key是State，有时候又是status。

总结起来就是，同样的代码和接口(根据jobid获取信息)，返回结果会不断改变。而在不同的返回结果中，有时候表示状态的值对应的key是State，有时候是status，不知道是什么原因呢？

**Comment by milanlanlan** [comment]
@lijiang2014

**Comment by lijiang2014** [comment]
@milanlanlan 我上午看一下怎么回事，按我设计的逻辑现在应该都是 status 才对。

**Comment by lijiang2014** [comment]
@milanlanlan 已经修复了， 是昨天下午错误的启动了旧版本的代码，你们再检查看看还有没有其他问题。

**Comment by milanlanlan** [comment]
@lijiang2014 好的，我简单测试了一下没有问题，下午我再测试mpi程序，麻烦了！

**Comment by milanlanlan** [comment]
@lijiang2014 
你好，似乎又出现了一些问题。
在今天凌晨我还可以正常运行，然后从下午开始我发现这边出现了request fail，然后我打印出错误信息，发现返回了django的错误：
```
Exception Type: RuntimeError at /api/command/ln3
Exception Value： You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data.
```
看起来是url中的斜线出错了，不知道是那边又改了哪些部分还是什么原因呢？

打扰了，谢谢！

**Comment by xuelangZF** [comment]
我感觉应该请求 `/api/command/ln3/` 这个地址就不会出这个错误了，你试下 @milanlanlan

**Comment by milanlanlan** [comment]
是的，这个错误应该是这个意思，但是我不确定是api以后都改成这样，还是又会改成以前的样子（因为以前一直都没有加\），希望可以确定一下。

**Comment by xuelangZF** [comment]
哦哦，一般Python的Web开发，后台路由会写成 `/api/.../`的样式，这样浏览器中不论是否输入最后的`/`，路由都能够正常分发。

**Comment by milanlanlan** [comment]
好的，我下次注意一下这个问题。
不过好像又无限jump to async了，可能那边系统比较忙吧。

**Comment by lijiang2014** [comment]
Django 默认会加上 / , 导致我在写 url 解析的时候没有特别注意这一点儿 ，结果对于 POST 方法， django 不会去默认加上 /  , 如果不注意就会出问题 。。 刚刚我已经修复了大部分这个问题 ， 一般情况下加不加 / 应该都可以正常解析了 。 
系统最近状态不稳定 ， 估计要到下下周才会好一些。
这几天一直在对API 进行些微调，主要在进行单元测试，不过已有接口不会变，但重设时会暂时无法访问。
