### ISSUE TITLE
dropzone 上传文件 post 请求没有通过CSRF验证

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#344]
dropzone 上传文件时，也是发送了 post 请求，这个请求中没有携带 CSRF Token，导致服务器返回 403.

请 @luozhx 修复。

包括课室部分上传和案例展示部分的上传。。

此外，在项目中删除 dropzone.js ，使用 CDN：http://www.bootcdn.cn/dropzone/  。

**Comment by xuelangZF** [comment]
请更新Wiki：   https://github.com/xuelangZF/ehpc/wiki/Dropzone-%E5%A4%9A%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0

@luozhx

**Comment by luozhx** [comment]
已更新
