### ISSUE TITLE
作业管理

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#348]
作业管理部分做的很棒，特此 Issue 表扬

你们可以测试一下，看看有没有 bug

**Comment by xuelangZF** [comment]
作业管理的 Bug：

1. 无法创建作业。

![image](https://cloud.githubusercontent.com/assets/2769831/23831674/6095dfce-0761-11e7-8c46-411dec564d27.png)

**Comment by xuelangZF** [comment]
2. 没有选中内容，仍然可以下载和删除（http://127.0.0.1:5000/admin/course/1/homework/3）：

![image](https://cloud.githubusercontent.com/assets/2769831/23831781/d4396a6c-0762-11e7-8f22-fbea3f04426f.png)

**Comment by xuelangZF** [comment]
3. 文件上传部分，请采用 dropzone，显示文件上传进度，如果文件上传失败，请反馈具体原因。

Dropzone wiki：  https://github.com/xuelangZF/ehpc/wiki/Dropzone-%E5%A4%9A%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0

**Comment by xuelangZF** [comment]
3. 文件上传部分，请采用 dropzone，显示文件上传进度，如果文件上传失败，请反馈具体原因。

Dropzone wiki：  https://github.com/xuelangZF/ehpc/wiki/Dropzone-%E5%A4%9A%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0

**Comment by xuelangZF** [comment]
问题：

1. 没有选择删除的内容时，还是会弹出删除确认的框；
2. 后台作业附件上传时，并没有显示进度。（虽然弹出了进度条，但是没有显示进度）

![image](https://cloud.githubusercontent.com/assets/2769831/23881258/634be626-0894-11e7-9b20-c13fa500d7b3.png)

3. 学生提交作业时，也需要用 dropzone 做进度显示。（所有的上传文件地方都需要进度显示）
4. 所有的上传文件地方，要说明支持什么类型的文件，并且说明文件最大为多少。

@ym13349140

**Comment by ym13349140** [comment]
关于问题2，选择文件后不是马上上传的，是等点击保存之后才开始上传。其他几个问题我在改了。

**Comment by ym13349140** [comment]
师兄，还有一个关于上传进度条位置的问题，我们现在的上传进度框是用的position：absolute，对于下面这种内容比较长的页面，需要滚动向上才能看到进度条，容易被误以为没有了进度条；
![image](https://cloud.githubusercontent.com/assets/17507937/23884474/cffcb166-08a7-11e7-93c2-5a7718c9301a.png)
![image](https://cloud.githubusercontent.com/assets/17507937/23884483/d9e323f4-08a7-11e7-95ca-1bc9b065f500.png)
我昨天试了position设置为fixed，相对显示器固定，但是因为它的z-index比较大，有时候会挡住保存按钮，我们要把它放在哪比较合适呢？

**Comment by xuelangZF** [comment]
这里点了上传的话，就直接上传吧，不用等点击保存。

可以将上面的标题，时间和内容作为一小块，编辑完需要保存。然后下面的附件上传直接就上传，不然显的怪怪的。

**Comment by xuelangZF** [comment]
放的位置的话，最好放在页面最右下角落，像百度云盘一样。

至于遮挡保存按钮的话，如果将保存和上传文件分开的话，遮挡了也无所谓。

**Comment by ym13349140** [comment]
但是有个问题就是在创建作业的时候，如果信息都还没保存就点了上传文件，这时候都还没在数据库新建作业，上传的文件就没有对应的作业了呀。如果是创建完成之后再上传文件的话，不就跟直接到编辑里面上传一样了吗，那就没有必要再创建的界面增加一个上传文件了吧。

**Comment by xuelangZF** [comment]
下面两种方案：

1. 像课时管理一样，在作业列表管理页面提供上传附件的按钮（像课时管理那样）：

![image](https://cloud.githubusercontent.com/assets/2769831/23885958/03a23568-08b2-11e7-9c89-5edd27fcaa05.png)

2. 按照你现在的方案，点击保存之后再开始上传。不过需要稍微改动下，选中文件后，只是在页面列出选择的文件名，点了保存按钮之后，才弹出上传的那个框，并开始上传。

你看哪个方案合适？

**Comment by ym13349140** [comment]
我用第二种吧，好像比较符合老师的要求

**Comment by xuelangZF** [comment]
OK，那就第二种的做法来做吧。

**Comment by xuelangZF** [comment]
学生上传作业的话，不用再提供一个开始上传的按钮了。选中文件之后，直接就开始上传。上传完作业，进度条直接关闭就行。

这里也不用提供移除功能， 因为你的提交列表里已经有了移除的功能了。

![image](https://cloud.githubusercontent.com/assets/2769831/23951371/d579e0ba-09c8-11e7-80a9-820bd00f92d2.png)
