### ISSUE TITLE
无内容时的提示

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#376]
有时候，某个区域因为数据库还没有记录，因此没有内容显示，这时候空白的话，会很别扭。

![image](https://cloud.githubusercontent.com/assets/2769831/23951537/4e7a0508-09c9-11e7-944d-bdcbfb117348.png)

最好是能够提供一些信息。比如上面的例子，最好是显示，`当前还没有作业` 之类的信息。

对于系统中的 `{% for .. in .. %}` 循环语句做一个排查，找出对应前端的div区域，然后提供没有内容时的显示内容。

@ym13349140  完善

**Comment by ym13349140** [comment]
收到！
