### ISSUE TITLE
评论内容长度验证

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#382]
![image](https://cloud.githubusercontent.com/assets/2769831/23997518/99150cca-0a8c-11e7-9221-3548ac0053c4.png)

@wzl281158150

**Comment by wzl281158150** [comment]
师兄，这个不是我写的啊……

**Comment by wzl281158150** [comment]
这是啥地方的啊

**Comment by wzl281158150** [comment]
![image](https://cloud.githubusercontent.com/assets/22830541/23997954/6ae46204-0a8e-11e7-9135-1268c2c71408.png)
师兄这是谁写的。。。.val() 后面的 .length呢

**Comment by xuelangZF** [comment]
😢  不知道谁写的这个长度限制。。。。

**Comment by xuelangZF** [comment]
Github 的好处是，知道每一行代码是谁写的！

https://github.com/xuelangZF/ehpc/commit/733b0ec969cd47b78f4ff2e8a2222915616c8531#diff-9a0b43c2ec590fc44f938c4f4cdb0eff

哈哈，是 @ym13349140

**Comment by ym13349140** [comment]
( ⊙ o ⊙ )啊！我的锅！写漏了。。。。

**Comment by xuelangZF** [comment]
为啥 @wzl281158150 不修复一下呢？
