### ISSUE TITLE
上传作业弹出文件选择框有延迟

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#389]
上传作业时，弹出的选择文件框有时候会有几秒的延迟。

@ym13349140 看下是什么原因，尽快修复。

@luozhx 帮忙修复。

**Comment by xuelangZF** [comment]
@ym13349140 这个找到原因了吗

**Comment by ym13349140** [comment]
这个我测试了好几次的时候又没出现问题，都没法看是哪里出了问题。我查了一下，也没看到关于dropzone的解释，目前找到的一个感觉比较有道理的解释是Chrome的文件上传设置了accept文件类型，所以打开文件选择框的时候会先筛选出文件夹里符合类型的文件，所以有时候会有延迟，我也不确定我们这里是不是这个原因。

**Comment by xuelangZF** [comment]
其他地方的上传好像也有过滤文件类型的，你看下其他地方和上交作业这里有什么不同吗？

**Comment by ym13349140** [comment]
我之前也看过，JS里的dropzone部分没什么区别，主要的不同就是dropzone.js的引入位置问题，之前我跟罗震霄也讨论过，其他地方的dropzone.js都是在相应的HTML文件里引入的，但是上传作业这里不是，因为课程主页的作业部分只是一个tab，它的内容是ajax加载的，我之前把dropzone直接放在widget_detail_homework.html里面加载，dropzone会报错失效，最后把dropzone.js的引入移动到了最外层的course/detail.html里面，dropzone才能成功定义，不知道是不是这个原因

**Comment by xuelangZF** [comment]
感觉现在 widget_detail_homework.html 有错的吧，它没有继承自模板，不能用 {%block ..%}  {% endblock %} 包裹。

另外，感觉detail 这个页面也写的好复杂啊，应该可以重构下。

**Comment by ym13349140** [comment]
detail页面里面的JS确实有点多。 widget_detail_homework.html 里的那些block扩展是我之前没有注意到，那要把JS文件全部放在外层的detail.html里面去引入吗

**Comment by xuelangZF** [comment]
这个是因为改了下面的文件类型就可以了吗？

@ym13349140 

```
acceptedFiles: "video/mp4,video/mkv,application/pdf,.zip,.rar",
```

**Comment by ym13349140** [comment]
我也不确定现在是不是可以了，因为老师提出这个问题之后我就没有在碰到过延迟了，不知道改了这里是不是有效

**Comment by xuelangZF** [comment]
我这里还有延迟的
