### ISSUE TITLE
重置密码邮件以及提示信息的完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#393]
![image](https://cloud.githubusercontent.com/assets/2769831/24178198/9c249098-0ee2-11e7-8a3d-bdf430a01903.png)

完善意见：

> ”赋值“--》”复制“，”eHPC“改为”EasyHPC“，删掉”注意：“
> easyHPC Reset Your Password --》EasyHPC Reset Your Password

此外，邮件发送成功后，浏览器的提示信息样式也需要改一下（还有更改密码成功后浏览器的提示）。目前是这样子的：

![image](https://cloud.githubusercontent.com/assets/2769831/24178308/5213d44a-0ee3-11e7-889f-59d6006f7462.png)

参考下面的提示信息样式：

![image](https://cloud.githubusercontent.com/assets/2769831/24178268/155ac0f4-0ee3-11e7-8663-88e3c7062cbc.png)

@milanlanlan

**Comment by milanlanlan** [comment]
easyHPC Reset Your Password --》EasyHPC Reset Your Password
不好意思，我没有找到这句话在哪里？

**Comment by xuelangZF** [comment]
稍微改了下，希望你明白你代码每一行的作用吧。
