### ISSUE TITLE
超算网络问题？

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#397]
目前无论是使用公网映射后的域名地址还是使用之前的内网地址，在服务器上均无法连接后台 API。

之前使用的是 节点地址：  172.16.23.19:8010 
上次加了一层代理，地址改为：10.133.100.40:8010
或者是公网的映射域名地址： http://a002.nscc-gz.cn:10218

在服务器上均无法连接。

推测原因：

1. 超算内部网络不支持对自身域名地址的解析。（这点在 VNC 上也得了验证）
2. 一层代理地址无法访问是由于 **网络故障**。（VNC的一层代理之前可以访问，现在也不行）
3. 节点直接地址现在应该是改变了。

@lijiang2014

**Comment by lijiang2014** [comment]
你们用的还是云虚拟机吧？ 可能是做了网络安全隔离。你们的虚拟机的内外IP 都发给我一下 ，我找云的同事确认一下。
你们现在 10.127.48.5 这个IP 可以ping 通的话可以暂时用 这个IP 的 8000 端口来访问。

**Comment by xuelangZF** [comment]
内部地址：10.174.5.19
外部地址：10.133.100.168

**Comment by xuelangZF** [comment]
10.127.48.5  这个地址可以访问，我先切换下。

**Comment by lijiang2014** [comment]
我这里可以PING 通 你的10.133.100.168 , 10.133.100.40 这个IP 是禁PING 了 ， 但 http://10.133.100.40:8010/api 应该是可以在你的  10.133.100.168 的虚拟机上访问的吧？ 
云那边的同事说是10.133段是可以访问的。

**Comment by xuelangZF** [comment]
刚试了下，http://10.133.100.40:8010/api 可以访问了。

```
$ curl http://10.133.100.40:8010/api
{"output": {"text": "Welcome to eHPC ", "version": "0.0.2"}, "status_code": 200, "status": "OK", "error": ""}(ehpc) netlab513@ubuntu:~/ehpc$
```
