### ISSUE TITLE
Ajax使用 以及结果的适当反馈

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#40]
提交 78c156dd666461b0c5c6ff0249ec2ff270f7d195 中对用户的设置页面采用了 Ajax，并且每次设置完之后都会给出提示信息。

![2016-10-22 8 13 31](https://cloud.githubusercontent.com/assets/2769831/19619214/0dc50a0e-9894-11e6-87b0-22e907580ff9.png)
![2016-10-22 8 13 18](https://cloud.githubusercontent.com/assets/2769831/19619215/0dc6ac38-9894-11e6-8b44-6bec763e7e93.png)

可以看下代码，不明白的地方可以在下面回复。

重写了 @milanlanlan 你的代码，希望你可以理解 Ajax 了

**Comment by xuelangZF** [comment]
案例展示中编辑完案例信息，点击 `提交` 之后没有给出适当的“反馈提示”。

可以添加一个 modal 或者像上面例子一样，给出一个 info 信息。

@ym13349140

**Comment by ym13349140** [comment]
收到
