### ISSUE TITLE
导出名单功能完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#404]
目前导出名单存在的Bug：`attachment_filename＝学生名单.xlxs` 后缀名出错。

需要完善的地方：

1. 导出字段中添加学生邮箱地址，因为邮箱地址具有唯一性，其他的都不确定有没有重复。

    ![image](https://cloud.githubusercontent.com/assets/2769831/24319224/8fc4a44e-1150-11e7-835c-1cf56c02e273.png)

2. 对于待定批准的学生，不要在导出的表格中显示。 表格导出的是当前已经批准的学生。

@luozhx

**Comment by luozhx** [comment]
测试时没加attachment_filename这个参数，最后命名时拼错了
现在导出的学生名单是在course的users里面读取的，导出的都是已经被批准的学生。
