### ISSUE TITLE
作业相关问题

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#409]
# 打包下载

老师打包下载作业时，带上`时间戳`。这个时间戳是给老师看的，搞成 `云计算概论_HW1_1490528028635` 这样都看不出是什么时间下载的。应该是  `云计算概论_HW1_20170326`这样的时间。

# 增加外链PDF

外链PDF 添加后，打开相应的作业页面，直接就下载了文件，不能浏览 PDF。

![image](https://cloud.githubusercontent.com/assets/2769831/24330965/1a527f16-125d-11e7-9f44-9ed3d5541f1d.png)

@ym13349140

**Comment by ym13349140** [comment]
之前老师说怕设计版权问题，我以为是直接链接到外链接的页面去播放PDF。所以是要直接在我们的插件里面播放外链接的PDF吗？

**Comment by xuelangZF** [comment]
哦哦，也是，那我估计理解错误了。我再问下老师确认下吧。

不过现在是直接下载 PDF，最好是能够跳转链接？。

**Comment by ym13349140** [comment]
这个可能是跟浏览器设置有关，我的浏览器是直接在浏览器播放PDF，有点浏览器可能是关联到PDF的链接就默认下载了。

**Comment by xuelangZF** [comment]
嗯嗯，有可能。

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/24344893/2171bba6-1300-11e7-84d5-80441632411b.png)

这里删除作业时，没有点确认，后面列表中的作业已经不见了。

还有，当后台没有要删除的文件时，目前是返回了删除失败。但是前端也会弹出modal提示删除失败，实际上数据库的删除操作已经成功了。（这时候其实可以认为已经正确删除了，不用弹窗的）

**Comment by ym13349140** [comment]
收到！

**Comment by xuelangZF** [comment]
这个地方确认了，是在我们的显示框直接显示外链的 PDF。也就是说外链PDF 添加后，直接浏览 PDF。  @ym13349140

**Comment by xuelangZF** [comment]
作业类型不支持时，会弹出两个框。外层的modal：文件上传失败，请稍后重试，不必显示。

![image](https://cloud.githubusercontent.com/assets/2769831/24384929/b1306d52-1399-11e7-90d7-796f838e16b9.png)

此外，**上传文件状态**里面，会累计显示之前上传的不符合要求的文件。（第一次传docx，显示一条记录；关掉之后，第二次再上传docx，第一次的记录还是存在。）

@ym13349140

**Comment by xuelangZF** [comment]
时间戳部分，201731 这种日期看着不舒服，我已经把它改为 20170301  这种日期格式了。 具体见 https://github.com/xuelangZF/ehpc/commit/36fe95acd7768ba3d07527f96d481e4b0effb29e

**Comment by ym13349140** [comment]
师兄，关于外链PDF文件的显示这属于跨域请求吧，应该不能直接在我们的显示框显示外链接的PDF文件。所以还是只能跳转到原链接去显示，或者我们自己先下载下来再在我们的显示框里显示（这样的话跟本地文件就没区别了）

**Comment by xuelangZF** [comment]
跨域请求只要原来的域允许的话，是可以请求到。不然我们怎么从 CDN 拿到所需要的 JS 文件呢。
