### ISSUE TITLE
服务器数据备份方案

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#417]
对线上服务器的文件进行备份。

# 文件备份

[lsyncd](https://github.com/axkibe/lsyncd) 配置简单，能够实现简单高效的本地目录同步备份。

参考资料：

[Lsyncd | 使用lsyncd同步文件目录](http://clavinli.github.io/2013/11/12/linux-server-lsyncd/)    
[lsyncd实时同步搭建指南——取代rsync+inotify](http://seanlook.com/2015/05/06/lsyncd-synchronize-realtime/)

**Comment by xuelangZF** [comment]
备份操作是从 主服务器到备份服务器。

WIKI 中 远程服务器是说 `主服务器`，本地是指 `备份服务器` ？

**Comment by luozhx** [comment]
本地是主服务器，远程是指备份服务器。
我去改一下说法吧。

**Comment by xuelangZF** [comment]
👌，改的容易理解点吧。

**Comment by xuelangZF** [comment]
@Zouzhp3  根据文档 https://github.com/xuelangZF/ehpc/wiki/%E6%95%B0%E6%8D%AE%E5%A4%87%E4%BB%BD 在服务器上做 static 目录的备份

**Comment by Zouzhp3** [comment]
收到

**Comment by Zouzhp3** [comment]
做 static 目录的备份，是备份到本机还是另外一台服务器？

**Comment by Zouzhp3** [comment]
已经在服务器上 /home/zhao/backup 目录中使用 lsyncd 完成 static 目录的备份

**Comment by xuelangZF** [comment]
备份到另一台主机，你那里有主机吗？

**Comment by Zouzhp3** [comment]
只有放实验室网站的那台主机，要放在那上面吗？

**Comment by xuelangZF** [comment]
那就先放那台机器吧。

**Comment by Zouzhp3** [comment]
忘了说了，已经成功备份到实验室网站的那台主机了
