### ISSUE TITLE
提交程序弹窗显示正在上传的图片

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#422]
点击提交程序后，之前是在程序运行结果部分显示 正在上传的 图片，需要改为弹出一个 modal，里面显示这张图片。直到超时或者超算返回错误，才取消modal的显示。

![image](https://cloud.githubusercontent.com/assets/2769831/24456206/e228dc2e-14c4-11e7-8540-61f8493f3282.png)

@wzl281158150 实现

**Comment by wzl281158150** [comment]
这个有点丑吧 师兄/....

**Comment by wzl281158150** [comment]
现在是要提交时，弹出modal来提示正在上传？

**Comment by xuelangZF** [comment]
对啊，之前懒得弄，直接放这里了。改为弹出 modal 把，这个确实太丑了
