### ISSUE TITLE
完善虚拟实验室小任务

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#425]
后台已经增加了对虚拟实验室任务的参数配置，如下：

![image](https://cloud.githubusercontent.com/assets/2769831/24483654/292439b8-152c-11e7-9157-5ebe38295f86.png)

请 @milanlanlan  @luozhx 补充之前实验任务中的参数配置。

**Comment by milanlanlan** [comment]
请问补充参数配置是指在实验说明中说明默认参数吗？具体是补充什么呢？

**Comment by xuelangZF** [comment]
不是在实验中说明默认参数。

虚拟实验室的程序不是需要指定 编译选项，任务数，CPU/任务，结点数 这几个参数才能运行嘛，之前这些都是后台写死，所有实验用的一套参数。

现在都每个任务中的程序都需要指定这4个参数。（上面图片就是后台看到的样子啊！）

**Comment by milanlanlan** [comment]
可是现在应该是由用户来指定参数吧？我不是很明白的是我们需要补充的部分是？

**Comment by xuelangZF** [comment]
你看了我们的后台和前端了吗？  
虚拟实验室部分的代码提交部分你见到有用户可以设置参数的地方吗？  

虚拟实验室不是在线编程！！！  虚拟实验室的每个任务都需要教师用户在后台添加默认的参数配置，用户直接使用这些配置去运行！

还不明白吗？
