### ISSUE TITLE
进一步完善课程的成员管理

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#427]
目前成员管理部分不是很方便操作，具体体现在：

1. 一次只能批准或者拒绝一个学生加入课程，
2. 误拒绝同学不能再一次同意其加入。

![image](https://cloud.githubusercontent.com/assets/2769831/24708639/0cec3700-1a4a-11e7-9a75-78d7d6b550da.png)

 @luozhx  完善这部分，解决上面这两个问题。  

对分易这部分的操作也不是很完善，可以参考一下：

![image](https://cloud.githubusercontent.com/assets/2769831/24708729/5af5addc-1a4a-11e7-868d-03ded5dd95c3.png)

我的建议：

1. 加一个多选框，可以一次选择多个人，然后批量进行操作
2. 只要学生申请了加入课程，在成员管理这里就一直显示该记录。状态直有两种：待批准和已加入。待批准状态经过老师的“同意”操作后，变为已加入，待批准时不设置老师“拒绝”的操作。已加入状态时，老师可以进行“踢出”的操作，剔出后学生状态变为待批准。
3. 学生一旦提交过一次加入课程的申请，之后就不能再次提交该申请。前端课程页面上，直有加入成功和等待批准两个状态。

PS：这里的表格样式好像有问题，和试题中心在线编程部分不太一样，请顺便修复下。

**Comment by xuelangZF** [comment]
这一块你开始做了吗？

**Comment by luozhx** [comment]
还没有，可能要过一两天，这几天在写论文

**Comment by xuelangZF** [comment]
不知道你现在的处理逻辑是什么？目前主要有5个需求：

1. 增加批量同意审核的功能，当很多学生加入一个课程时，审核起来很麻烦，要一个一个同意。
2. 用户排序后的学生名单（如按状态排序），如果对其中一个学生操作后（如同意申请），整个排序又改为初始未排序的状态，请修改为保持用户之前的排序状态。
3. 如果拒绝一个学生，导出的学生列表不应该还包括他；
4. 对于由于老师误操作导致“已拒绝”的学生， 老师无法修改决定，建议提供老师修改为同意的选项，（如对于该类同学，“操作”处不用写“已处理”，改为“同意”）；
5. 增加删除某个同学的功能；

其中第五个删除同学的需求暂时不做。因为这个删除的逻辑不好处理。现在的代码逻辑中，删除学生后，会发现：

![image](https://cloud.githubusercontent.com/assets/2769831/24842455/5f699bf2-1dca-11e7-8920-e3bc0cd97a78.png)

但是，在课程的页面中，发现其实还是有同学在这门课程的（这时候完全没有办法对这些同学进行管理）。

![image](https://cloud.githubusercontent.com/assets/2769831/24842460/78e34790-1dca-11e7-99f9-c08a9c42609b.png)

成员管理的实现要保证后台管理和前端展示有一致性，也就是说：

1. 所有后台同意的学生在前台都是会显示已经加入课程（数据库中课程成员记录中有这个学生的记录）；
2. 所有拒绝的同学，不能出现在导出的学生名单中；
3. 对于课程中所有提交了加入申请的同学，在后台的成员管理中都应该显示到。

以上，有什么意见，请沟通。先搞清楚处理逻辑，再去写具体实现。

**Comment by luozhx** [comment]
现在的处理逻辑就是申请状态是有0和1两种，0是审核中，1已经加入。
学生申请后状态就是0，加入后就是1。
1.批量操作已经实现。
2.原来是使用重定向刷新，现在是使用ajax提交，所以可以保持排序状态。
3.导出出学生的列表是直接从course.users里面拿，不会有拒绝的同学。
4.状态只有0和1，就是同意和踢出
5.只能删除没有同意的申请，下面的问题其实是测试数据库的问题
在apply中只有用户1 2 3是提交申请的，而7 9是直接写入数据库的，肯定会无法操作。
![image](https://cloud.githubusercontent.com/assets/22886929/24847828/214fcd4c-1df6-11e7-98e9-e29ae1ee0cc4.png)
![qq 20170410140149](https://cloud.githubusercontent.com/assets/22886929/24847844/4a1421ba-1df6-11e7-9ef2-ca53ae39b647.png)

**Comment by xuelangZF** [comment]
删除没有同意的申请之后，如果学生再申请，会怎么处理？

**Comment by luozhx** [comment]
删除申请就是删除了这条记录。
如果学生再申请，和之前的申请也是一样的。

**Comment by xuelangZF** [comment]
OK。明白你的意思了，我重新merge下你的代码再看看。

**Comment by xuelangZF** [comment]
你需要重新提交一下 pull request，我这里revert之后不能再merge了。  @luozhx

**Comment by luozhx** [comment]
已提交

**Comment by xuelangZF** [comment]
还是有问题的。你之前的逻辑说 `目前只能删除没有同意的申请`。现在批量删除时，直接就能删除所有的记录。

![image](https://cloud.githubusercontent.com/assets/2769831/25033455/63e9d8ba-2110-11e7-8eec-9b9646d4ceb3.png)

@luozhx

**Comment by luozhx** [comment]
批量操作我设计时会判断一样是否满足要求的，不满足要求的就会忽略。
我看看这个错误是怎么造成的

**Comment by xuelangZF** [comment]
成员管理这里还有两个问题：

1. 导出名单时，这些字段改为默认都是勾选。

![image](https://cloud.githubusercontent.com/assets/2769831/25080547/99e6bb7c-2377-11e7-9486-07793f94bb2d.png)

2. 对于已经同意的学生，选中后点击删除时，改为弹窗提示。“该记录不可被删除。如要删除，请先将学生踢出课程。” 目前是刷新了页面却什么也没有，感觉怪怪的。

@luozhx

**Comment by luozhx** [comment]
就是批量删除的时候给出提示，然后阻止操作？

**Comment by xuelangZF** [comment]
对，就这个意思

**Comment by xuelangZF** [comment]
这里的批量同意、批量踢出、批量删除操作之前，没有验证是否有选中某一项。目前什么都没有选，点击批量操作也会刷新页面。

![image](https://cloud.githubusercontent.com/assets/2769831/25210183/8423d694-25b1-11e7-8c03-8d1f04c2d29a.png)

改进：先判断有没有选中内容，没有的话，点批量操作，弹出modal，给出相应提示内容。

@luozhx
