### ISSUE TITLE
题库样式适配

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#428]
题库的题目部分，如果屏幕像素高度不够，就会遮挡 “提交” 的按钮。

![image](https://cloud.githubusercontent.com/assets/2769831/24733571/237e1266-1aab-11e7-97c0-5c292e7d8491.png)

这部分的样式之前通过 style 写死在页面的，最好是能够重构下，将页面分为不同的 div，然后设置各个 div class 的属性。

PS: 页面的导航屑和题目没有左对齐， 顺便修复下。（在线编程题目列表的导航屑也是同样问题。）

@wzl281158150 修复

**Comment by wzl281158150** [comment]
这个问题其实页面顶部导航栏与页脚栏写法问题，原写法中间主体部分有效区域是整个屏幕，而使用margin-bottm=负数，强行将页脚上拉，以实现内容长度不足时仍可以占满屏幕，这个做法会导致页脚将主体部分下部的内容遮挡，之前VNC页面使用原base.html亦有相同问题

**Comment by xuelangZF** [comment]
嗯嗯，这样写主要是为了在页面内容很少时，还是能够撑满整个页面，使得头部导航栏和底部确实在顶部和尾部。

解决办法，可以设置中间主体部分的 margin-bottom，避免太往下了。

**Comment by xuelangZF** [comment]
这个目前在解决吗？  @wzl281158150

**Comment by xuelangZF** [comment]
这个问题如何了？  @wzl281158150

**Comment by wzl281158150** [comment]
还没弄
