### ISSUE TITLE
虚拟桌面的实验部分需要支持拆分知识点

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#429]
虚拟实验室中虚拟桌面部分的实验，也需要像编程实验一样分为不同的知识点。然后可以记录学习进度，不过这里不判断是否完成了一个知识点。

前端页面中，跳转到下一个知识点时，用 Ajax 更新左边的知识内容即可，不要刷新页面。（**避免重新载入右侧的桌面**）

@wzl281158150 实现

**Comment by xuelangZF** [comment]
目前实现的还是很粗糙，主要有以下问题：

1. 每次进行下一个任务时，会重新加载整个页面。虚拟桌面部分也会重新加载。这里最好使用 Ajax，只加载左侧知识内容；
2. 后台管理对输入字段没有验证。小任务只有标题也可以成功保存。

前端界面的意见：

不要再保留**顶部**和**底部**的黑条（这个黑条太难看）了，`返回虚拟实验室`的按钮放在知识点的头部。右侧虚拟桌面默认最好能直接铺满高度。类似 实验楼的界面：

![image](https://cloud.githubusercontent.com/assets/2769831/24913182/ed2f4b7e-1f02-11e7-9483-d364f34de2c4.png)

**Comment by wzl281158150** [comment]
1 前端simplemde不知如何支持插件表单验证  后台现在允许空的content
2 由于分辨率切换需刷新页面，使用ajax传过来的内容会丢失，其次刷新页面不会对桌面连接不会有任何影响
3 由于支持分辨率改变  当宽大于高时 铺满右侧无法做到

**Comment by xuelangZF** [comment]
1. 后台允许空 content 本身就是不合理的，至于 simplemde 的表单验证，可以询问 @ym13349140 ，其他地方的simplemde是支持验证内容的。
2. 切换到下个任务时，用 ajax 传递的是左侧知识点内容，不用对虚拟桌面使用 ajax 重新请求。当然，如果要改分辨率的话，还是要重新加载虚拟桌面的
3. 铺满右侧做不到的话，最好使虚拟桌面靠右，左侧空的部分暂时不管。

**Comment by wzl281158150** [comment]
2 请问传过来下一个任务之后   改变分辨率，页面上的内容是什么

**Comment by xuelangZF** [comment]
明白你的意思了。  分辨率切换的话，必须要刷新整个页面吗？有没有办法只用刷新右侧虚拟桌面的内容？

**Comment by wzl281158150** [comment]
对

**Comment by xuelangZF** [comment]
我想不明白，为什么分辨率切换要刷新整个页面？ 能给我解释下必须刷新整个页面的技术限制在哪里吗？

**Comment by wzl281158150** [comment]
硬是要不刷新也可以，你开心就好

**Comment by xuelangZF** [comment]
不是开不开心的问题，只是这样刷新的体验很差。我没深入了解这块，所以不知道必须刷新的技术限制在哪里。
