### ISSUE TITLE
OpenMP 程序更改

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#431]
目前的OpenMP 程序不能通过编译，请修复

![wechatimg21](https://cloud.githubusercontent.com/assets/2769831/24735537/fcd56d98-1ab5-11e7-8809-1d7b9a6c3366.jpeg)

**Comment by xuelangZF** [comment]
@luozhx 完成了吗？

**Comment by luozhx** [comment]
上面这题改好了，其他题目因为天河服务器连接不上，还没测完

**Comment by luozhx** [comment]
测试完了，现在所有题目都可以在服务器上编译运行了。
