### ISSUE TITLE
4.8 情况反馈

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#433]
# 1. VNC 实验入口

> Linux入门课程的图标大小改为和MPI一样大，加入学习进度条。“阅览文档“可以删掉；

![image](https://cloud.githubusercontent.com/assets/2769831/24823961/efc56b8a-1c36-11e7-962c-4dc0f5b753e6.png)

@wzl281158150  负责

#  2. VNC 实验切分任务

> Linux入门的内容设置改为多个小知识点，类似MPI和OPENMP课程的设置，格式采用Markdown形式；可以参考实验楼里的实验设置；

https://github.com/xuelangZF/ehpc/issues/429 @wzl281158150 

# 3. VNC 分辨率设置

> VNC设置为最佳分辨率，会出现变形的问题，如下图：

![image](https://cloud.githubusercontent.com/assets/2769831/24823992/4069948a-1c37-11e7-9f29-68b7b0fb9786.png)

我的 chrome 浏览器没有这个问题，可能是浏览器兼容问题， @wzl281158150 排查修复

# 4. VNC 页面导航栏

> 请把VNC界面的“虚拟实验室”替换为和MPI课程界面一致的“返回虚拟实验室”按钮；另外，“剪切板”，“桌面全屏”，“浏览器全屏”，“更改分辨率“可缩回菜单可否放到页面的最右侧，不要放在页面上方；

![image](https://cloud.githubusercontent.com/assets/2769831/24824017/826a0e78-1c37-11e7-839c-ad12cbb913fb.png)

这样右面虚拟桌面部分可以铺满浏览器高度。   @wzl281158150 

# 5. 课程成员管理

> 课程管理中，如果一个同学加入后，退出，再加入这个课程，系统里会产生两个记录，这个有问题。请只保留一个最新记录。

![image](https://cloud.githubusercontent.com/assets/2769831/24824038/c0c13dc2-1c37-11e7-9020-8bed90a6f1dc.png)

@luozhx  完成

# 6. 成员管理记录

> 课程管理中，（1）请增加批量同意审核的功能，当很多学生加入一个课程时，审核起来很麻烦，要一个一个同意。（2）用户排序后的学生名单（如按状态排序），如果对其中一个学生操作后（如同意申请），整个排序又改为初始未排序的状态，请修改为保持用户之前的排序状态。（3）如果拒绝一个学生，导出的学生列表不应该还包括他；（4）对于由于老师误操作导致“已拒绝”的学生， 老师无法修改决定，建议提供老师修改为同意的选项，（如对于该类同学，“操作”处不用写“已处理”，改为“同意”）；（5）增加删除某个同学的功能；

![image](https://cloud.githubusercontent.com/assets/2769831/24824056/28b23fd0-1c38-11e7-85ca-1cd00e5578f8.png)

参照 https://github.com/xuelangZF/ehpc/issues/427 和上面的意见，对这部分整改。  @luozhx 

# 7. 导出成员时可选择字段

> 导出学生名单时，请弹出一个页面框，可以让用户选择需要导出的项目（如老师可以只选“姓名”，“学号”；也可以选择“姓名”，“学号”，“性别”），可以用checkbox的形式提供给用户选择；信息排序按照“姓名”，“学号”，“性别”，“电话”，“邮件”，“学校”来排列，参考注册界面上的信息；

![image](https://cloud.githubusercontent.com/assets/2769831/24824068/4ce1356e-1c38-11e7-9b99-d696b0cce61b.png)

@ym13349140 实现。

# 8. 作业管理排序功能

> 作业管理，请支持按照“学号”，“提交时间”等排序的功能；默认按照用户学号排序；

![image](https://cloud.githubusercontent.com/assets/2769831/24824087/7d4fb496-1c38-11e7-8604-d0bdfe95aea8.png)

@ym13349140  完成。

# 9. 作业批改任务

> 请支持作业批改功能，教师可以针对同学的作业在线打分，写评语，支持用户成绩的导出； 可以参考对分易的功能；

@ym13349140 参考对分易的操作流程完成这部分。

# 10. 虚拟实验室后台管理

> 1）“编程虚拟实验室“和”VNC虚拟实验室“合并为一项，（2）在”新建实验室“的界面上提供两个选项”在线编程“，”VNC实验“； “知识点管理”改为“实验管理”；（3）在”实验列表“处，增加一列，标明是”在线编程“，还是”VNC实验“；（4）VNC实验的任务编辑参考编程虚拟实验室的设置；

![image](https://cloud.githubusercontent.com/assets/2769831/24824117/f4944ed6-1c38-11e7-8a26-f45c9516250c.png)

@wzl281158150 完成。

# 11. 实验课封面设置

> 实验课设置的封面图片为何在界面上没有显示？请增加。

![image](https://cloud.githubusercontent.com/assets/2769831/24824129/15da3312-1c39-11e7-81af-3c6a096c62e9.png)

@Zouzhp3 完成。

# 12. 课程管理支持课程排序

> 课程管理处，（1）请支持对于所列课程的顺序调整功能。（2）请支持直接点击课程图片，进入课程管理界面的功能；

![image](https://cloud.githubusercontent.com/assets/2769831/24824156/494f6eba-1c39-11e7-9456-dbf7bfaf42e6.png)

@ym13349140 实现。要排序的话，可能还要针对课程添加一个序号字段。

# 13. OPENMP的编译存在错误

> OPENMP的编译存在错误，请修改。

![image](https://cloud.githubusercontent.com/assets/2769831/24824172/771ac8b2-1c39-11e7-99d6-bcb37c97b846.png)

@luozhx  修复。

# 14. 增加超时设置。

> 增加超时设置的选项，用户可以修改超时设置；可以在“查看答案”和“提交运行”中间，增加一个按钮”环境设置“，里面可以做些设置。【优先级低】

![image](https://cloud.githubusercontent.com/assets/2769831/24824183/9f012a06-1c39-11e7-8d0f-e0ecd7364189.png)

@ym13349140 实现。

# 15. 备份功能

> 请对之前录入的试题，课程内容、编程题等增加备份功能，可以方便导入和导出。

包括系统的文件备份和数据库备份， https://github.com/xuelangZF/ehpc/issues/417。 @luozhx  实现。

# 16. 下载代码文件命名

> 下载代码时，请提供用户命名文件的机会，不要直接命名为code.txt. 

![image](https://cloud.githubusercontent.com/assets/2769831/24824210/ec9ada96-1c39-11e7-872b-1d81c75154a6.png)

@Zouzhp3  实现。

# 17. 参考代码的引入。

> 请增加“参考答案”的选项，点击后在代码框load参考答案；

![image](https://cloud.githubusercontent.com/assets/2769831/24824219/17a4f758-1c3a-11e7-9802-6bec63f7b286.png)

需要对题库中题目增加参考代码字段，后台也相应的添加答案代码。  @Zouzhp3 实现。

**Comment by ym13349140** [comment]
师兄，问题14中的超时设置是指自己选择超时的时间吗？括号里的优先级低指的是什么优先级呀？

**Comment by xuelangZF** [comment]
对，给几个超时的时间选项吧，比如20s, 30s,  50s 之类的。优先级是说这个 任务的优先级，可以慢点做。

**Comment by ym13349140** [comment]
任务的优先级目前是在哪里有体现出来吗？我好像没看到，然后优先级需要设置哪些选项呀？

**Comment by xuelangZF** [comment]
😅😅   任务是指：  咱们的开发任务。。

好尴尬。。。。

**Comment by ym13349140** [comment]
噢噢，好的(⊙o⊙)理解错了......

**Comment by xuelangZF** [comment]
11, 16 已完成 https://github.com/xuelangZF/ehpc/pull/435

**Comment by xuelangZF** [comment]
疑问汇总：

1. 课程管理支持课程排序。

**Comment by Zouzhp3** [comment]
我发现我前几天给编程题增加参考代码的 pull request  和现在的代码有了冲突，该怎么处理比较好？

**Comment by xuelangZF** [comment]
我来处理。
