### ISSUE TITLE
课程管理排序功能

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#439]
目前的管理有点不知所措。

![image](https://cloud.githubusercontent.com/assets/2769831/24843027/40f90822-1dd1-11e7-817a-0c43e73def5a.png)

有时候下移的话，一下子跑很远，并且这样调整太不方便了。

可以参考虚拟实验室中任务顺序的调整部分。

**Comment by xuelangZF** [comment]
还有一个很重要的问题：这里每个老师只能调整自己部分的课程。但是前台显示的话，是显示所有老师的课程，对于不同老师的课程来说，如何调整顺序？

**Comment by ym13349140** [comment]
按照目前我们的设置的话，老师是只能看到自己的课程的，所以对于不同的老师的课程，我们可以给所有的课程设置成同一套序号，但是不同老师的课程顺序还是没法调整的。

**Comment by xuelangZF** [comment]
> 支持系统管理员可以进行课程排序，老师的课程排序功能用处不大，主要在主界面上我们能调整课程顺序；

@ym13349140

**Comment by ym13349140** [comment]
这个是要在管理员后台界面增加一个调整课程顺序的功能是吗？

**Comment by xuelangZF** [comment]
对的，管理员后台添加课程顺序调整的功能。

**Comment by ym13349140** [comment]
嗯嗯，已经添加了

**Comment by xuelangZF** [comment]
OK，实现的不错
