### ISSUE TITLE
作业批改功能

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#444]
作业批改部分我想的是直接在查看提交的作业界面增加一个批改功能，可以打分和写评语，但问题就是一个人可能提交了多次，也可能有多个不同的文件类型，这个打分是针对一次提交还是整个这次作业，目前的话我只想到了两个方案：
1. 批改某个学生的任意一次提交并将分数同步到所有提交（一般都是只看最后一次提交），这个分数作为最终这次作业的成绩，这种的话就在homework_upload表格增加一个score字段，还要增加一个学生作业得分表；
![image](https://cloud.githubusercontent.com/assets/17507937/24844300/449c2cd8-1ddc-11e7-97b9-4e5bc40c8ce0.png)

2. 直接新建一个页面，不显示学生具体提交的文件信息，只显示哪些人交了，哪些是迟交，哪些人没交，类似对分易的界面，然后直接在这个界面对每个学生的本次作业打分，这种的话就只需要增加一个学生作业得分表；

![image](https://cloud.githubusercontent.com/assets/17507937/24844280/0ce1562e-1ddc-11e7-9d7b-02e70e7a97be.png)

**Comment by xuelangZF** [comment]
> 作业批改，建议采用方案2，只用给老师填写分数和评语的地方。同时最好也支持批量导入、导出成绩和评语的功能。(有的老师不喜欢一个一个在系统里填分数，而是在导出的Excel空表里填写，之后上传到系统上，发布给同学看到。)

**Comment by ym13349140** [comment]
这个我已经按照第二种方案在改了，之前提交的是第一种方案的实现。

**Comment by xuelangZF** [comment]
嗯嗯，好的

**Comment by xuelangZF** [comment]
model.py 里面是这样子的：

![image](https://cloud.githubusercontent.com/assets/2769831/25068081/f541d120-228a-11e7-93b8-4721163a6696.png)

给的数据库改动里是这样的：

![image](https://cloud.githubusercontent.com/assets/2769831/25068079/e80fdff6-228a-11e7-854f-3576e680dafb.png)

导致批改作业有明显的错误。

![image](https://cloud.githubusercontent.com/assets/2769831/25068085/2cb8e8e6-228b-11e7-8c9e-133cfa354e42.png)

@ym13349140

**Comment by ym13349140** [comment]
哦，我忘了更新sql文件了。

**Comment by xuelangZF** [comment]
你更新下 sql 文件，再提交一次吧

**Comment by ym13349140** [comment]
好的~

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/25080611/04af8b0a-2378-11e7-91e1-6a87c1d393d6.png)

每一个写好都填提交太麻烦了，只提供一个提交批改的按钮吧。点提交时，检查哪些部分有输入，然后更新其中的部分即可。

**Comment by ym13349140** [comment]
老师主要想的是直接导入成绩表，所以这个在线打分只是作为辅助，有时候修改个别成绩的时候可以直接提交，对分易也是这么实现的。批量提交一开始我也有考虑， 批量提交的话在前端需要把每一项都判断一遍选出有输入的项，然后后端也要把所有提交的项判断一遍区分首次提交和修改了的项，实现起来好像比这个要复杂，所以我最后还是选了单项直接提交。所以，我们还是要改成批量提交吗？

**Comment by xuelangZF** [comment]
哦哦哦，这样子啊，那先这样吧
