### ISSUE TITLE
增加邮件发送日志

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#451]
我们被警告发送了大量邮件， @luozhx 在系统中添加下邮件的发送日志记录。

![image](https://cloud.githubusercontent.com/assets/2769831/24987613/85275a1c-2033-11e7-89d4-ae803266bb8b.png)

然后看下是什么原因。

日志可以用 logging 模块，将邮件发送的所有请求记录在 app_logs 中的 email.log 文件中。

**Comment by luozhx** [comment]
明白

**Comment by xuelangZF** [comment]
在日志中不用记录 subject 和 template 等信息。要添加此邮件发送请求的 IP 地址信息。

> subject: Reset Your Password, template: user/passwd_reset_email

@luozhx

**Comment by luozhx** [comment]
好的

**Comment by xuelangZF** [comment]
[Flask request.remote_addr is wrong on webfaction and not showing real user IP](http://stackoverflow.com/questions/12770950/flask-request-remote-addr-is-wrong-on-webfaction-and-not-showing-real-user-ip)

and 

[Flask apps on Heroku susceptible to IP spoofing](http://esd.io/blog/flask-apps-heroku-real-ip-spoofing.html)

**Comment by xuelangZF** [comment]
```
$ cat app_logs/email.log
[2017-04-14 19:59:40,138] remote_ip: 127.0.0.1, to: 1291023320@qq.com
[2017-04-14 19:59:45,905] remote_ip: 127.0.0.1, to: xuezaigds@gmail.com
```
之前所有的 IP 都为 127.0.0.1 。

**Comment by luozhx** [comment]
在服务器上测试也都是127.0.0.1吗？

**Comment by xuelangZF** [comment]
对的，你可以看下上面的两个链接。 上面的测试就是在服务器上的。
