### ISSUE TITLE
虚拟桌面风格

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#454]
目前我们的虚拟桌面 UI 是下面这种：

![image](https://cloud.githubusercontent.com/assets/2769831/25037479/e4f207dc-212b-11e7-91e5-14b82fbe245e.png)

感觉没有shiyanlou的好看点：

![image](https://cloud.githubusercontent.com/assets/2769831/25037488/f2495962-212b-11e7-8b7c-8458c68394ec.png)

具体体现在：

1. 右侧列表文字竖排感觉很别扭，目前没有见到这样的 UI 设计；
2. 左侧的`返回虚拟实验室`，太长了，最好类似实验楼，上面是白色背景条，然后放 `返回虚拟实验室` 按钮。

此外，根据  https://github.com/xuelangZF/ehpc/issues/450 ，右侧边栏默认是展开的。

@wzl281158150 把这个再弄好看点把。

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
新版不错，没有大的问题。不过还是有两个小问题：

1. 进度这里不对，应该 +1。

![image](https://cloud.githubusercontent.com/assets/2769831/25067728/71b7b780-227f-11e7-9873-f40c77c083ba.png)

2. 侧边工具栏文字样式不太美观。

![image](https://cloud.githubusercontent.com/assets/2769831/25067744/b2870950-227f-11e7-945e-b007a249bc07.png)

侧边工具栏字体太大。改进方法：

- 缩小字体；
- 左对齐
- 加一个小 icon

审美还需要培养啊。

**Comment by wzl281158150** [comment]
我试过加图标 但是9有些按钮不知道应该配什么图标

**Comment by wzl281158150** [comment]
进度不是表示已完成多少吗？ 我还特意减一

**Comment by xuelangZF** [comment]
进度不是表示当前这个任务的编号吗？😭  
没关系，先陪一个，不行再改改。

**Comment by wzl281158150** [comment]
好
