### ISSUE TITLE
虚拟桌面样式问题

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#461]
忽然发现 VNC 这一块儿还是不太好，主要是知识点部分，没有边距，都到页面边缘了。

![image](https://cloud.githubusercontent.com/assets/2769831/25221260/11695008-25e7-11e7-8192-ee83a74bdf0b.png)

参考编程任务中的界面，留出一定的空白边距。

此外，鼠标悬浮 `返回虚拟实验室` 按钮的样式变化太难看，请参考编程任务的效果。  @wzl281158150

**Comment by wzl281158150** [comment]
编程任务的返回按钮没有悬停效果啊

**Comment by xuelangZF** [comment]
嗯嗯，vnc这里也不要效果了吧
