### ISSUE TITLE
代码编辑中文输入问题

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#474]
ACE 代码编辑框，当输入中文时有问题，具体参考： https://github.com/ajaxorg/ace/issues/3119 

Ace 的 1.2.6 版本修复了此问题，更新 Ace 版本即可。

**Comment by xuelangZF** [comment]
这次采用 CDN，不过之前为了使代码编辑框默认样式为黑色，@milanlanlan 将样式写死在本地的 ace.js 中。这是极不推荐的方法！采用开源库时，不要直接在里面改，不然很难升级，也无法使用CDN。

**Comment by xuelangZF** [comment]
升级后，在虚拟实验室部分，界面有点问题，如果像之前一样，将代码编辑部分的底色改为黑色，则加载编辑框时会出现闪动。不设底色的话，编辑框没有颜色闪动，不过会有白色横条在编辑框和代码运行结果中。

![image](https://cloud.githubusercontent.com/assets/2769831/25435762/b31c6d28-2ac3-11e7-9b8f-02cc7c0ba8fa.png)

**Comment by xuelangZF** [comment]
@ym13349140  看下如何解决这个样式问题。

**Comment by xuelangZF** [comment]
@ym13349140  解决了吗？

**Comment by ym13349140** [comment]
暂时还没解决这个，编辑框从白色变为黑色应该是ace加载的问题，它先加载了ace默认的主题，然后再执行了setOptions设置成我们要的主题，所以好像一开始是白色的背景然后变成黑色。但是你说的那个白色横条我没有遇到，你说的不设底色指的是在哪里不设底色呀？

**Comment by ym13349140** [comment]
然后还发现一个问题就是，左侧的gutter宽度应该是随着行号的位数变化的，当代码行数不超过10行的时候，左侧的gutter会窄一格导致上下对不齐；然后那个代码编辑框现在是没有滚动的吗，超过高度的代码部分好像看不到。
![image](https://cloud.githubusercontent.com/assets/17507937/25515097/bf3fdf8e-2c14-11e7-8a1a-bc35861c18b0.png)
![image](https://cloud.githubusercontent.com/assets/17507937/25515144/1bc1fd28-2c15-11e7-8bcd-fa49a2abe2da.png)

**Comment by xuelangZF** [comment]
确实先是加载ace默认的主题，然后再执行了setOptions设置成我们要的主题，不知道怎么更改他的默认主题设置。不设底色指的是代码编辑框部分，可以看 https://github.com/xuelangZF/ehpc/issues/400#issuecomment-288954835 讨论。

白色横条是说编辑框和结果框之间的横条，之前是没有横条的，我不知道这个横条怎么出来的。

现在代码有滚动的啊，右侧滚动条颜色比较深。
![image](https://cloud.githubusercontent.com/assets/2769831/25515940/15a91ae8-2c1a-11e7-9d22-5611df4c0594.png)

**Comment by ym13349140** [comment]
噢噢，我看到那个白条了，之前在较小的显示屏下是没有白条的，在较大的显示屏下就会有，应该是lab.css这里给#laboratory设置了高度为50%的缘故，在大屏幕下，#laboratory的高度为#challenge-right的50%，但是#laboratory里面的#editor的高度虽然设置的是min-height：400px，但是因为#editor的position：relative导致min-height失效，所以实际是editor的height一直固定为400px，当#challenge-right的50%超过400px的时候editor下方就会出现白条，直接把#editor的position：relative去掉，然后min-height：400px改成min-height：100%就没有白条了，高度还是自适应的。
![image](https://cloud.githubusercontent.com/assets/17507937/25517379/c4e1dac0-2c21-11e7-8c88-8112a9678610.png)

**Comment by xuelangZF** [comment]
我这里看了半天没找到原因！ 👏👏👏

**Comment by xuelangZF** [comment]
> 因为#editor的position：relative导致min-height失效，所以实际是editor的height一直固定为400px.

这里你是在文档中看到的吗？

**Comment by ym13349140** [comment]
噢，不是文档中看到的，可能我有点记混了，好像不是position导致的，是float会导致失效，现在的问题是editor的min-height：400px就是无效的，就会出现白条，但是设置为100%就是有效的，我也暂时还没看出来是为啥
