### ISSUE TITLE
虚拟实验室部分左右宽度可拖动

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#477]
VNC 部分，左右可拖动，宽度不固定死。

@wzl281158150

**Comment by xuelangZF** [comment]
能够将中间的分割线做的让人一看就知道可以拖动？

![image](https://cloud.githubusercontent.com/assets/2769831/25519878/36253a4c-2c2c-11e7-951b-1683e1034c3f.png)

**Comment by wzl281158150** [comment]
不知道怎么做好看啊

**Comment by xuelangZF** [comment]
刚才看了几个，没有看到好看的，我再找找哈

**Comment by xuelangZF** [comment]
左侧知识点部分边界留白仍然太少了，请增加留白（和虚拟实验室部分留白px一样）。

@wzl281158150 

![image](https://cloud.githubusercontent.com/assets/2769831/25741374/158797a8-31bd-11e7-9a8d-90a0ed40b75a.png)

**Comment by xuelangZF** [comment]
@wzl281158150  左边加多留白。

此外，分割线的样式请采用 [split.js ](https://nathancahill.github.io/Split.js/)的样式：

![image](https://cloud.githubusercontent.com/assets/2769831/26182682/54fa1d04-3bac-11e7-803f-f264e76e893e.png)

**Comment by wzl281158150** [comment]
除非换成这个插件，不然无法做到这个样式，但是换成这个插件，我之前的白写了

**Comment by wzl281158150** [comment]
这个插件 是在两个模块之间 放一个div，我的写法是直接使用  jquery ui 的resizable功能

**Comment by xuelangZF** [comment]
直接使用 resizable的话，不能改中间分界线的样式吗？

**Comment by wzl281158150** [comment]
他中间分界线就是一个border

**Comment by xuelangZF** [comment]
它的中间分割线是一个 dic 的。 `<div class="gutter gutter-horizontal" style="width: 10px;"></div>`

两种做法：

1. 采用 split.js  重写。
2. 修改 border 的样式。实现类似的效果，如下（https://www.w3schools.com/cssref/tryit.asp?filename=trycss_js_border-style ）：

![image](https://cloud.githubusercontent.com/assets/2769831/26188507/22ccfbfa-3bd2-11e7-8ae0-eb6a2584e51a.png)

**Comment by wzl281158150** [comment]
关键是咋们右边是黑色的，如果都是白色的其实很简单

**Comment by xuelangZF** [comment]
好问题。。。。无解了。。

**Comment by wzl281158150** [comment]
要不要弄成 白色.....

**Comment by xuelangZF** [comment]
试一下，看下效果吧
