### ISSUE TITLE
考虑加入登录、注册、发送邮件等人机验证模块

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#480]
> 人机验证（Captcha）是一种用于区分用户是计算机和人的计算机程序。人机识别有助于保护您免受垃圾信息、恶意注册的干扰，使网站运营更加安全。 

> 传统的人机验证方法是利用图形的视觉识别来进行验证，常用验证方案有：图片字符验证，图片含义验证（eg.12306），此类验证方法操作难度大，给正常用户带来很大的困扰。 
Luosimao 创新开发的人机验证，免去了复杂的输入过程，具有更加优秀的操作体验，更加美观的设计，可更好地融入到您的网站中。

有成熟的企业方案，比如 https://luosimao.com/service/captcha  。人机接口的验证文档在： https://luosimao.com/docs/api/56 。

后台处理时建议加一个 decorator，在需要验证的view部分加上 decorator。

@luozhx  实现。

**Comment by luozhx** [comment]
Luosimao的话修改部分基本都在前端，装饰器的话我觉得好像用处不大。
另外账号是我私人注册还是项目组提供一个？

**Comment by xuelangZF** [comment]
后台部分需要对前台传的数据验证的吧，后台验证写成一般函数也行。

账户你先私人注册吧，只是把那些key写在配置文件中，这样后面如果要改的话也很容易。

**Comment by luozhx** [comment]
因为有些请求还分get和post，不同的页面认证失败后的处理方式也不一样，所以我觉得装饰器不太适用。
我直接写了一个函数用于验证，直接在路由函数中使用。

**Comment by xuelangZF** [comment]
我看了下配置文件中出现的两个 key 确实可以公开，放config.py 中确实没问题。

**Comment by xuelangZF** [comment]
首页登录窗口那里，人机验证窗口过长，导致整个登录窗口变大，都遮住了页面中的图片。

![image](https://cloud.githubusercontent.com/assets/2769831/25731351/13f17d36-3178-11e7-8cb7-53901e2ad848.png)

将验证栏目宽度改为和登录输入框的宽度一致。

**Comment by xuelangZF** [comment]
此外，使用外部的人机验证模块服务时，考虑如果它们的服务挂掉，我们这边如何处理？  @luozhx 

（暂时停用人机验证？如果是暂时停用的话，最好是有一个配置开关写进环境变量，这样改了环境变量之后，可以临时关闭人机验证模块）

**Comment by luozhx** [comment]
登陆窗口在我这里是正确的显示的，我这里三个框的长度都是255px。
![qq 20170505143936](https://cloud.githubusercontent.com/assets/22886929/25735873/f0fb68b8-31a0-11e7-9a25-e638f39f0698.png)

我看了下他们的文档也没有提供判断服务是否可用的接口，估计只能暂停使用，我写一个配置开关吧。

**Comment by xuelangZF** [comment]
Chrome 58.0.3029.96 (64-bit) 和 Safari  下显示宽度不同的。你用的浏览器不是 chrome吗

**Comment by luozhx** [comment]
我在windows下的chrome和ubuntu下的firefox都试过了，都是正常的。

**Comment by xuelangZF** [comment]
修复了这个问题了。

现在整个 登陆框宽度仍然是 300px，你之前改的 315px，可能会覆盖图片。

此外， 密码输入部分和点击人机识别部分的宽度设置为了 240px（保证左右留白看上去一样多，同时不至于过短，因为过短人机验证的字会被覆盖掉）。

**Comment by luozhx** [comment]
显示正常，现在配置开关已经加上了

**Comment by xuelangZF** [comment]
还有，我想问下 https://github.com/xuelangZF/ehpc/pull/485/files#diff-fdf313ed2303059c44a9ebfffbef8eeb 在 Config 类中为什么不直接 `CAPTCHA = True` ，而要在全局先 `CAPTCHA = True`，然后在Config类中再 `CAPTCHA = CAPTCHA`。同样的还有  `CAPTCHA_VERIFY_URL`等字段。   @luozhx

**Comment by xuelangZF** [comment]
对了，我还是想把这些配置选项写进 `环境变量`，这样以后变更的话，不用改代码。类似下面这种：

```
VNC_INSIDE_SERVER_IP = os.environ.get('EHPC_VNC_PRIVATE_URL')
VNC_OUTSIDE_SERVER_IP = os.environ.get('EHPC_VNC_PUBLIC_URL')
```

**Comment by luozhx** [comment]
因为这两个字段在`verify_captcha`函数和模板中需要使用。如果写进config类的话，函数中无法读取，会出现out of context的错误，不写进config类的话模板中又无法使用，所以就在config类中再复制一次了。这样只改最前面的部分就可以，直接写Ture的话需要改两个地方。
环境变量的话直接改就行了。

**Comment by xuelangZF** [comment]
哦哦，忽略了函数中也用到这些变量了。
