### ISSUE TITLE
完善用户注册流程

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#483]
现在只有学生注册，对于教师用户，目前是手动用管理员授权。另外，学生注册时，开始时需要填写的信息过多。

完善地方：

1. 注册时，可以选择是否注册为教师用户。如果为教师用户注册，则需要给管理员发送一个邮件（邮件中提供链接），管理员可以通过点击链接进入页面，查看该用户注册时填写的信息，并选择同意或者拒绝该教师用户的注册。
2. 所有用户注册时，只需要填写邮箱和密码，密码确认字段（此外，提供一个单选卡，可以选择注册为既教师或者学生用户）。填写完毕后，再跳转到另一个表单，填写具体的信息。（注意，学生和老师填写的信息可能不同）。

@luozhx

**Comment by luozhx** [comment]
1. 我觉得注册教师账号可以参考课程的申请，然后在管理员界面加一个页面用于审核。
2. 注册表单的话不如将表单分成两部分，第一部分是邮箱密码，然后点下一步后隐藏，然后再显示剩下的具体信息，填完后再一起发送，这样后台就可以不作修改。

**Comment by xuelangZF** [comment]
1. 我感觉教师用户的注册还是和课程申请有区别的。教师用户数量不多，如果像课程申请那里一样的审核机制，需要重新添加表，感觉小题大作。并且不像课程申请，老师可以在某个限定日期前检查下有多少申请，并进行授权。这里教师账户的申请可能更随机点，管理员不可能经常去查看管理页面看又有谁申请了。很有可能是，教师注册后还需要再联系管理员，让管理员授权，这样增加了沟通成本。

如果每次教师申请就给管理员发送邮件的话，就可以避免上述问题了。

2. 注册表单确实是你说的步骤。不过，第一部分最好还提供一个 “教师用户”， “学生用户” 的选项，然后根据这个地方，第二部分给出相应的需要完善信息的地方。对于教师用户来说，不用像学生一样，提供学号、性别字段。

**Comment by xuelangZF** [comment]
还有，我想问下 https://github.com/xuelangZF/ehpc/pull/485/files#diff-fdf313ed2303059c44a9ebfffbef8eeb 在 Config 类中为什么不直接 `CAPTCHA = True` ，而要在全局先 `CAPTCHA = True`，然后在Config类中再 `CAPTCHA = CAPTCHA`。同样的还有  `CAPTCHA_VERIFY_URL`等字段。   @luozhx

**Comment by luozhx** [comment]
主要日邮件中提供的链接是点一下就确认，还是点了以后进去查看信息并且选择是否同意，这一步中注册信息还是要暂存吧。
另外教师用户注册成功后应该就直接是教师权限了，不需要再联系管理员了吧。

**Comment by xuelangZF** [comment]
其实教师用户和学生用户是一个数据表，目前有一个权限位置。

教师用户注册后先设定为一个普通学生用户，等管理员确认后才能提权限为教师用户。

**Comment by luozhx** [comment]
我是说可以在注册教师账号的同时可以设置权限，那么就不需要注册完再去改了。
管理员点同意后直接改权限就可以了。

**Comment by xuelangZF** [comment]
`注册教师账户的同时设置权限，不需要注册完再去改` 什么意思？

教师权限是必须要由管理员审批的啊

**Comment by luozhx** [comment]
就是注册教师用户时在后台用python代码直接修改。

**Comment by xuelangZF** [comment]
修改什么啊

**Comment by luozhx** [comment]
修改注册的教师用户的permission字段啊，在创建用户的时候直接写进去。

**Comment by xuelangZF** [comment]
你的意思是注册的时候直接将 permission 字段改为 “教师权限”？

**Comment by luozhx** [comment]
是的，因为注册教师账户需要管理员同意的话，那么就一起将教师权限也给了

**Comment by xuelangZF** [comment]
注册完直接是教师权限了，那管理员审核还有有什么用呢？

教师账户不是随便就能注册的，必须要管理员同意后才可以的。也就是说管理员审核通过才能给教师权限。

**Comment by luozhx** [comment]
我之前是说注册后先提交申请，管理员审核同意后才创建用户，不过这样用户管理用处就不大了。

那现在就是说注册的时候是不需要审核的，先创建用户，默认给学生权限。
然后发送邮件给管理员，然后邮件里面带有注册信息和用户管理的链接对吧？

**Comment by xuelangZF** [comment]
对，后面的就是想要实现的。

不过邮件里带有一个链接，打开后会看到用户注册信息，同时有一个授权或者拒绝的按钮，管理员可以直接操作。

**Comment by luozhx** [comment]
明白
