### ISSUE TITLE
课程资源部分的问题

### ISSUE THREAD

**Issue by ym13349140** [xuelangZF/ehpc#487]
1、materials部分上传的文件大小限制目前是50M，可能需要再增大一点，我在添加OpenMP课程的时候很多视频都是超过50M的，都无法上传；
2、课程视频播放的界面只有第一次点进去的时候能播放，点击 右侧目录的另一个视频就播放不了，下面报错如下：
![image](https://cloud.githubusercontent.com/assets/17507937/25791230/808fa7e4-33f1-11e7-9085-b70afd5dce00.png)

**Comment by xuelangZF** [comment]
你的这个是视频链接的吧？应该是跨域的问题？

**Comment by xuelangZF** [comment]
materials 部分上传的文件大小限制多少合适呢？

**Comment by ym13349140** [comment]
不是跨域的，我这里的视频都是本地上传的，直接右键在新标签页打开是正常播放的，但是直接在本页面切换另一个视频就不可以。

**Comment by xuelangZF** [comment]
@luozhx  看下问题原因，感觉是 CSRF 的问题。

**Comment by ym13349140** [comment]
materials部分的话，如果是普通课件其实50M是足够的，但是如果上传视频的话，可能至少得改到200M以上。

**Comment by xuelangZF** [comment]
视频大小限制貌似是前端代码写的限制，你看下把它改为500M的上限吧。  @ym13349140

**Comment by ym13349140** [comment]
好的~

**Comment by luozhx** [comment]
也有可能是重新加载clappr的问题，这个页面是动态更新的。

**Comment by xuelangZF** [comment]
也有可能，因为我看了并不缺少 csrf 字段，你debug下看看吧。

**Comment by luozhx** [comment]
ubuntu17.04下使用clappr播放视频是不是还需要安装一些东西？
我已经安装了`ubuntu-restricted-extras`，直接打开视频也可以播放。
但是上传到课时材料中就无法使用clappr播放，一直是显示这个错误：
`Your browser does not support the playback of this video. Please try using a different browser.`
直接访问部署到服务器的版本又可以正常播放视频。

**Comment by xuelangZF** [comment]
找到原因了：

![image](https://cloud.githubusercontent.com/assets/2769831/25831543/949a84a6-3497-11e7-8464-0443818bd24e.png)

第65行加上 alert，发现这里导出的视频链接是有问题的，带有了hash字段：

![image](https://cloud.githubusercontent.com/assets/2769831/25831573/b79eb828-3497-11e7-8ed5-2b8237729379.png)
