### ISSUE TITLE
虚拟实验室程序运行问题？

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#489]
虚拟实验室 MPI 学习部分，默认的程序直接运行，结果就是并行的。

![image](https://cloud.githubusercontent.com/assets/2769831/25850517/39682c24-34f5-11e7-9a6c-c2a82c930b50.png)

目前随便试了下，http://a002.nscc-gz.cn:10165/lab/knowledge/5/?progress=1 和 http://a002.nscc-gz.cn:10165/lab/knowledge/5/?progress=2 都存在这个问题。

@milanlanlan 把所有的 MPI 程序过一遍，避免这个问题。

试了下，OpenMP 并没有出现这个问题。

**Comment by milanlanlan** [comment]
这个问题是因为我们在后台默认设置了并行参数，例如第二个实验：

如果是默认的程序，输出：
```
Hello World! The number of processes is 0
Hello World! The number of processes is 0
Hello World! The number of processes is 0
Hello World! The number of processes is 0
```

如果是答案代码，输出：
```
Hello World! The number of processes is 4
Hello World! The number of processes is 4
Hello World! The number of processes is 4
Hello World! The number of processes is 4
```

可以看出中间的代码执行与否还是有效果的。

**Comment by xuelangZF** [comment]
是的，第一个 hello world 的看不出区别来，所以容易让人误解。

你把所有程序过一下，让答案代码和默认代码的运行结果不一样，不然容易让人误解。

**Comment by milanlanlan** [comment]
好的

**Comment by milanlanlan** [comment]
目前已经把25个知识点测试了一遍，其中输出没有变化的包括编号1、6、10、12和23的知识点。

最终做出的修改如下（以编号区分）：

- 1：第一个实验由于太过简单，不好修改，所以我直接把示例代码的输出语句删掉了，所以现在直接运行不会有输出；
- 6：这是一个过渡的知识点，所以最终输出是会相同的，所以我在输出结果说明中说明了这一点；
- 10、12：加入了对变量的赋值使示例代码和参考代码结果不同；
- 23：如果没有补充代码，（也就是示例代码）天河2号会在运行中卡住，导致超时而返回“长时间没有响应，请稍后再试”的提示信息。当时也考虑过要不要对这种情况进行处理，不过其实对于这种程序上的错误，在我们这里是很难具体判断的。（与串行程序不同）所以这里我没有改代码，而是在输出结果说明了这一点。

如果贴图的话会有5*2=10张图，所以在这里就没有贴了，直接去运行一下可能会更有说服力。
