### ISSUE TITLE
远程桌面服务系统架构问题

### ISSUE THREAD

**Issue by wzl281158150** [xuelangZF/ehpc#490]
目前已基本完成远程桌面服务后台的重写工作，但经测试发现存在重大结构问题。目前采用一台虚拟机做总机进行分配与连接工作，其他若干台虚拟机承载docker容器。但这种做法使得所有用户流量都必须通过总机。经测试一个用户占用服务器带宽的最大值为 3M左右，即若总机带宽为100M，在用户大于33人之后，用户的使用体验会随着使用人数的增加而迅速下降。
解决设想：
目前未利用的资源为docker容器承载机的外网带宽，需充分使用该资源，即将流量分摊到所有虚拟机，将分配工作放置总机，将连接工作分摊至所有虚拟机。
好处：

1. 平摊所有流量，大大提升服务所支持的同时在线人数，提高了用户体验。

**Comment by xuelangZF** [comment]
https://github.com/xuelangZF/ehpc/pull/494/files#diff-632b651e5579af0e928ed63482e9bc77 

这里 threading.Lock() 作用是啥？

**Comment by wzl281158150** [comment]
在create new image函数中有用到

**Comment by xuelangZF** [comment]
![image](https://cloud.githubusercontent.com/assets/2769831/25937420/2b0bdf1c-365e-11e7-81da-512b4b43fcdb.png)

这里加锁是为了防止同时创建多个镜像吗？

同时创建的话，也不是不可以啊？为什么一定要加锁？

**Comment by wzl281158150** [comment]
因为我要指定端口  如果你这里不同步一下 可能两个镜像会用同一个端口

**Comment by xuelangZF** [comment]
3个问题！

1. 只用在获取端口号那里加锁就行，不用对这么长语句全部加锁吧。
2. 加锁的话，还是用 with 语句吧。不然万一中间某个语句抛出异常的话，锁会一直在那里不能释放。

```
some_lock.acquire()
try:
    # do something...
finally:
    some_lock.release()
```

换成 python 风格，就是：

```
with some_lock:
    # do something...
is equivalent to:
```

3. 我们的服务器中，gunicorn 是开了好几个进程的，每个进程内有线程来处理请求。不同进程申请的端口号还是有可能冲突的。这个问题怎么解决。

**Comment by wzl281158150** [comment]
这里的端口指的是  容器端口，比如用户 1 2 3 的镜像都在  主机A上   主机A 的 5902给1  5903个2  5904给3     如何获得这些端口？首先从数据库中读取 同一台主机上 端口最大的那个镜像，这里必须加锁，如果不加 若同时两个人创建镜像，读取的最大端口数就会一样，最后会冲突。读取之后，无论创建成功与否，都要先插入数据库，等插入完了释放锁了，第二个人才能被允许读取数据库来获得最大端口号，这样就不会冲突。
假设只在获取端口号加锁，同时用户 1 2 同时创建镜像，1 读取的端口号为5902，1释放锁但未到达插入数据库的语句，此时2读取端口号，获得的端口还是 5902，这样就会冲突。如果将释放锁的操作放在 1插入数据库之后，则2读取最大端口号时就会是 5903（因为1的端口是使用最大端口号5902+1=5903来指定），就不会有冲突

**Comment by wzl281158150** [comment]
如果是多进程就只有一个办法了，用消息队列

**Comment by xuelangZF** [comment]
先别急着用消息队列吧。

考虑在 Flask 中用一个全局变量保存可用的端口号，其中如果一个线程（比如A）要用一个端口，就直接从全局变量中删除某个端口号（比如1，端口1就给了线程A）。这样下一个线程（比如B）再申请端口的话，端口1已经不在全局变量中，也就不会被拿出来。

**Comment by wzl281158150** [comment]
多进程 这样有用吗

**Comment by xuelangZF** [comment]
貌似也不行啊，多进程貌似只有消息队列了。

**Comment by wzl281158150** [comment]
Java 是单实例 多线程所以可以，如果Flask这个是 多进程 那么只能用消息队列

**Comment by xuelangZF** [comment]
Gunicorn 是用的多进程的。

```
gunicorn manage:app -b 0.0.0.0:5000 --error-logfile - -w 4 --log-level debug

...
[2017-05-11 17:57:40 +0800] [98033] [INFO] Booting worker with pid: 98033
[2017-05-11 17:57:40 +0800] [98034] [INFO] Booting worker with pid: 98034
[2017-05-11 17:57:40 +0800] [98035] [INFO] Booting worker with pid: 98035
[2017-05-11 17:57:41 +0800] [98036] [INFO] Booting worker with pid: 98036
...

[2017-05-11 17:58:11 +0800] [98033] [DEBUG] GET /static/upload/case/1.png
[2017-05-11 17:58:11 +0800] [98034] [DEBUG] GET /static/upload/case/2.png
[2017-05-11 17:58:11 +0800] [98033] [DEBUG] GET /static/upload/case/3.png
[2017-05-11 17:58:11 +0800] [98036] [DEBUG] GET /static/upload/case/4.png
```

那就用消息队列吧。

**Comment by wzl281158150** [comment]
那么问题来了，消费者写在哪里？  肯定不能写在Flask里，因为多进程就会有多个消费者，我们只需要一个就行了

**Comment by wzl281158150** [comment]
我觉得还有一个神器的东西 叫 触发器

**Comment by xuelangZF** [comment]
对，从数据库入手。

**Comment by xuelangZF** [comment]
触发器的问题搞定了吗？机器恢复正常后，可以部署了吗

**Comment by wzl281158150** [comment]
早就写完了……

**Comment by xuelangZF** [comment]
提交到 vnc 分支吧。（坐等机器回复正常吧）
