### ISSUE TITLE
后台题库编程题目默认代码编辑框丢失

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#491]
后台管理页面，比如 http://a002.nscc-gz.cn:10165/admin/problem/program/edit/?id=1

![image](https://cloud.githubusercontent.com/assets/2769831/25884905/02bf9840-3588-11e7-9e53-822e58aec448.png)

可能是 https://github.com/xuelangZF/ehpc/issues/474#issuecomment-297928161 中引入的问题。

**Comment by ym13349140** [comment]
收到
