### ISSUE TITLE
退出课程时需要进行确认

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#492]
目前对于已经加入的课程，点退出之后，会直接退出课程。请增加 modal ，进行确认。

Modal 提示信息为：`确定退选当前课程？（注意，这里不是注销登录）`

此外，点击退出课程之后，需要将红色的`推出课程`位置变为 `加入审批中`。
（目前学生直接退出课程的话，教师后台仍然能够看到申请记录中，所以学生端显示的是加入审批。除非老师在后台手动删除这条记录，否则学生的申请记录一直存在。老师删除之前的申请记录后，学生才可以重新发起`加入课程`的请求。）

@Zouzhp3 实现

**Comment by Zouzhp3** [comment]
收到

**Comment by xuelangZF** [comment]
提交信息只用写  `#492` 或者 `https://github.com/xuelangZF/ehpc/issues/492` 就行。不用 `[]()`的。Github 会自动添加 reference。
