### ISSUE TITLE
注册流程的完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#496]
（注册部分的介绍请先阅读 https://github.com/xuelangZF/ehpc/issues/483）

目前注册最新代码在分支 https://github.com/xuelangZF/ehpc/tree/reg_workflow 上，@Zouzhp3 pull下这个分支的内容，进行完善。

主要完善的地方：

1. 第一个表单部分，去掉用户名（将用户名改为`用户昵称`，放在第二个表单）。`下一步`改为`注册`。

![image](https://cloud.githubusercontent.com/assets/2769831/25930175/5351b450-3637-11e7-9fb6-927f116469d4.png)

这部分表单在点击~~下一步~~（`注册`）时候，先发送Ajax请求，验证下邮箱地址是否已经注册。同时用前端库验证其他字段是否合法（两个密码是否一致，用户类型是否选填）。这些都没问题的话，进入第二个表单填写其他必填信息。

2. 第二个表单添加`用户昵称`字段。取消`上一步`按钮，因为我们第一个表单的内容已经经过验证了，没必要回到上一步。并把`注册`换为 `提交信息`。

在所有字段的最前面，添加如下信息：

```
完善用户信息

就要大功告成了，请完善下面的信息并提交，然后就可以使用您的账户了。
```

类似Google下面的这种

![image](https://cloud.githubusercontent.com/assets/2769831/25930379/7801783e-3638-11e7-9a85-e52f01bc44de.png)

用户第二步提交之后，再在数据库创建用户记录。

注意，对于老师用户，注册完之后，不跳转到首页。而是跳转到一个信息提示页面（类似：重置密码的邮件已经发送提示信息页面），告诉如下信息：

```
我们已经收到你的教师注册请求，等管理员审核通过后，就会给您教师权限。
```

@Zouzhp3 完成。

**Comment by Zouzhp3** [comment]
收到

**Comment by xuelangZF** [comment]
对了，还有就是，如果信息填写失败，给出提示信息后，仍然在编辑框补充好已经填的内容。

**Comment by Zouzhp3** [comment]
此处需要进行邮件确认的步骤吗？

**Comment by xuelangZF** [comment]
暂时不用邮件确认。

**Comment by xuelangZF** [comment]
问题：

1. 注册教师账户之后，直接就是`教师权限`了（这里默认注册成功后是学生用户，管理员授权后才是教师用户）。并且邮件的链接，不是管理员用户都可以打开(需要管理员登录后才能打开进行授权)。
2. 第二个表单中，如果没有进行人机验证，直接提交时，会跳转到 注册的第一个表单中。

**Comment by xuelangZF** [comment]
注册教师账户第二个表单填写的内容变成和学生的一样了？

![image](https://cloud.githubusercontent.com/assets/2769831/26084939/b1971544-3a12-11e7-9ce4-b67fa1b5b103.png)

做好后好好自己测试，不要随随便便就提交了。

**Comment by xuelangZF** [comment]
邮件中点管理员链接之后，如果当前管理员没有登录，是一个登录页面。登录完成之后，页面没有跳转到授权的页面（而是直接跳到后台管理的首页： http://127.0.0.1:5000/admin/system/）。

管理员登录后应该跳转到下面的页面（地址改为： http://127.0.0.1:5000/admin/add/teacher/16/，应该属于 admin 蓝图下面的）：

![image](https://cloud.githubusercontent.com/assets/2769831/26085052/c64b8a5a-3a13-11e7-88d4-913d8cbd8dcb.png)

**Comment by Zouzhp3** [comment]
哦哦好的，原来教师学生填写的第二张表单不一样，我之前没注意。。。

**Comment by xuelangZF** [comment]
嗯嗯，可以回滚到 @luozhx 完成的那个版本，看下第二个表的区别。

**Comment by xuelangZF** [comment]
@Zouzhp3  怎么样了

**Comment by Zouzhp3** [comment]
今天在帮陈立老师写网站，快上线了，我明天再写完注册流程。

**Comment by xuelangZF** [comment]
....
