### ISSUE TITLE
机时申请前端完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#503]
1. 提示信息左对齐

![image](https://cloud.githubusercontent.com/assets/2769831/26040930/db6efab0-395b-11e7-9834-a223f80b551b.png)

2. 申请机时的首页

![image](https://cloud.githubusercontent.com/assets/2769831/26040971/2227bbcc-395c-11e7-82d9-0886c69b874b.png)

这里不用有列表，因为一个用户只有一个申请（https://github.com/xuelangZF/ehpc/issues/478#issuecomment-300703934）。

如果当前用户没有申请，这里就是一个“申请机时”的区域（不显示`申请说明`区域，将其作为一个链接放在编辑页面右下角），类似如下：

![image](https://cloud.githubusercontent.com/assets/2769831/26041247/ebd3ff34-395d-11e7-83c1-606fe84bafee.png)

如果用户之前创建过申请（保存草稿或者提交过），这个页面直接显示申请编辑页面（不显示申请说明区域，将其作为一个链接放在编辑页面右下角）。并在顶部显示目前状态。（进展包括 `已提交申请`，`等待审批`，`审批通过`）

3. 申请编辑页面

![image](https://cloud.githubusercontent.com/assets/2769831/26041014/8880260c-395c-11e7-9ed1-28689e64386f.png)

增加`保存草稿` 功能。

有什么疑问随时讨论。

**Comment by ym13349140** [comment]
师兄，关于当前申请的提交状态具体是有哪几种呀？你上面列出的“已提交申请”和“等待审批”是不是差不多的呀？已提交应该就是在等待审批了吧？

**Comment by xuelangZF** [comment]
嗯嗯，`已提交申请`改为`未提交申请`（就是正在编辑本地草稿）

**Comment by xuelangZF** [comment]
1. 无法提交申请？

![image](https://cloud.githubusercontent.com/assets/2769831/26055708/9cde1bc0-39a4-11e7-8a5e-67efec7e6f2a.png)

2. 保存草稿内容时，不需要检查没有填写的字段。（一种场景是：可能有一个地方不会填，此时保存草稿，等搞清楚后，可以再回来填写。）

![image](https://cloud.githubusercontent.com/assets/2769831/26055754/c25e028e-39a4-11e7-8ff5-d76386b102f0.png)

**Comment by ym13349140** [comment]
1、提交部分的后端我没有写，所以一直显示的都是默认的未提交状态；
2、关于保存草稿部分，我还有点疑问，保存草稿的话是要存到数据库的吧？如果要存的话数据库部分暂时被我设置的是所有字段都不能为空所以我都开启了表单验证。还有一个问题就是，草稿就是存到数据库的话，那保存的草稿和实际提交的申请在数据库中是同一条记录把？

**Comment by luozhx** [comment]
提交部分部分只需要使用我的model文件就可以，我在里面多加了一个字段。
```
 status = db.Column(db.Integer, default=1, nullable=False)  # 申请状态： 0-申请被拒绝 1-通过申请 2-正在处理
```

**Comment by xuelangZF** [comment]
保存的草稿和实际提交的申请在数据库中是同一条记录，**字段可以为空**。不过提交申请时，需要检查下各个字段是否为空。这样可以吧

**Comment by ym13349140** [comment]
师兄，关于机时申请提交部分，是否需要设置已提交但还未通过审批的申请暂时不能重新提交？不然的话用户一直提交申请审批的时候会不会有较多次申请。

**Comment by xuelangZF** [comment]
对，如果处于已提交状态，只有审批不通过，才能进行下次的申请。

**Comment by xuelangZF** [comment]
现在保存草稿之后，直接成为 `已提交` 状态了。

还有，**申请状态**放的不太明显。最好是能够做一个类似下面这种的效果，放在申请单的上面。

![image](https://cloud.githubusercontent.com/assets/2769831/26092662/c96f0ad2-3a44-11e7-8851-86b75ec73269.png)

完成的步骤用绿色显示，当前状态用浅绿色，后面的步骤用灰色显示。

**Comment by ym13349140** [comment]
好的~

**Comment by xuelangZF** [comment]
Safari 下，新建申请的 ➕  无法显示。

![image](https://cloud.githubusercontent.com/assets/2769831/26095611/c97658ee-3a50-11e7-8e4c-36fb907aa2e8.png)

**Comment by ym13349140** [comment]
这个是在后台管理的所有模块中都用到的加号，你看下后台界面的加号能正常显示吗？

**Comment by ym13349140** [comment]
还有个问题，如果是处于已提交状态，那还能修改保存草稿吗？

**Comment by xuelangZF** [comment]
已提交不可修改了，只有拒绝后才可以修改。

**Comment by ym13349140** [comment]
好的

**Comment by xuelangZF** [comment]
后台的➕ 可以显示。

![image](https://cloud.githubusercontent.com/assets/2769831/26096086/a08b71e2-3a52-11e7-982a-07155e2fac29.png)

**Comment by ym13349140** [comment]
这个问题我再看一下吧，不行就换一个icon

**Comment by ym13349140** [comment]
如果是被拒绝后重新修改并保存了草稿，此时的状态应该是保持“被拒绝”，还是重新修改为“未提交”呢？

**Comment by xuelangZF** [comment]
未提交吧，你觉的呢？

**Comment by ym13349140** [comment]
我觉得改回“未提交”吧。

**Comment by xuelangZF** [comment]
ok！

**Comment by ym13349140** [comment]
师兄，你看一下你那边浏览器后台的课程管理主页的创建课程的加号能正常显示吗？

**Comment by xuelangZF** [comment]
不能啊，

![image](https://cloud.githubusercontent.com/assets/2769831/26097112/051fe75c-3a56-11e7-933e-e787684d88b2.png)

**Comment by ym13349140** [comment]
那就是font-awsome的icon显示有问题了，我全部换一下吧

**Comment by xuelangZF** [comment]
👌

**Comment by ym13349140** [comment]
![image](https://cloud.githubusercontent.com/assets/17507937/26104445/7c1dba2c-3a70-11e7-98f1-8c4c8101fe68.png)
师兄，你那边再看一下这个作业界面的批改作业的图标能正常显示吗？我确认一下是不是font-awsome显示的问题，如果是的话就得把所有的fa类的图标全部换掉。

**Comment by xuelangZF** [comment]
正常显示了。
