### ISSUE TITLE
机时申请状态完善

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#515]
之前表述不太清晰。

申请状态进度显示这里类似进度条，只不过在其中显示了进度介绍。比如说已经提交了，那么前面的`未提交` 也是绿色的了，表示已经完成的步骤。

![image](https://cloud.githubusercontent.com/assets/2769831/26139752/6e1373dc-3b05-11e7-9c37-000f6b12151f.png)

还有，如果还在等待审批，那么最后一步显示 `开始使用`。如果审批通过，最后一步显示 `申请通过`，否则显示 `申请被拒绝`（红色显示）。

**Comment by ym13349140** [comment]
OK~

**Comment by ym13349140** [comment]
![image](https://cloud.githubusercontent.com/assets/17507937/26140646/89d8dac6-3b0a-11e7-9366-b15d0a7795dc.png)
![image](https://cloud.githubusercontent.com/assets/17507937/26140651/911537a8-3b0a-11e7-9298-3da92f9da0a6.png)
![image](https://cloud.githubusercontent.com/assets/17507937/26140663/9c828e38-3b0a-11e7-80bc-fdff0de4a52a.png)
是这样的效果吗？

**Comment by xuelangZF** [comment]
对的

**Comment by ym13349140** [comment]
OK ~
