### ISSUE TITLE
Git 使用规范

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#55]
为了高效协同工作，统一 Git 使用规范流程：

![bg2015080501](https://cloud.githubusercontent.com/assets/2769831/19793057/4d733d8e-9cfd-11e6-9aad-512a3f3e73f2.png)

特别注意要时常 **与主干同步**，不然我很难 merge。

详细阅读：

[Git 使用规范流程](http://www.ruanyifeng.com/blog/2015/08/git-use-process.html)
[3.6 Git 分支 - 分支的衍合](https://git-scm.com/book/zh/v1/Git-%E5%88%86%E6%94%AF-%E5%88%86%E6%94%AF%E7%9A%84%E8%A1%8D%E5%90%88)  
[How do I update a GitHub forked repository?](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by ym13349140** [comment]
收到！

**Comment by xuelangZF** [comment]
最好不用每次自己更改前，都要重新 fork 我的主仓库，然后再更改。为了保持和我主仓库的一致，特别注意上面**第5步、第6步**的操作。

关于第6步，还可以阅读  [How do I update a GitHub forked repository?](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)  

rebase以后，本地分支历史改变了，跟你的远程分支不一定兼容，有可能要强行推送 -f。

此外，强烈建议时不时系统学习下 Git 操作，熟悉 Git 的理念！ https://git-scm.com/book/zh/v2/  这是本不错的书！！！

**Comment by xuelangZF** [comment]
[Git 分支 - 变基](https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%8F%98%E5%9F%BA) 详细说了 rebase 的原理，以及第 5， 6 步的操作意义。

> 一般我们这样做的目的是为了确保在向远程分支推送时能保持提交历史的整洁——例如向某个别人维护的项目贡献代码时。 在这种情况下，你首先在自己的分支里进行开发，当开发完成时你需要先将你的代码变基到 origin/master 上，然后再向主项目提交修改。 这样的话，该项目的维护者就不再需要进行整合工作，只需要快进合并便可。

**Comment by xuelangZF** [comment]
关于 Git 提交的 commit 信息规范

> 有一个创建优质提交信息的习惯会使 Git 的使用与协作容易的多。 一般情况下，信息应当以少于 50 个字符（25个汉字）的单行开始且简要地描述变更，接着是一个空白行，再接着是一个更详细的解释。 Git 项目要求一个更详细的解释，包括做改动的动机和它的实现与之前行为的对比 - 这是一个值得遵循的好规则。 在这些信息中使用现在时态祈使语气也是一个好想法。 

阅读 [分布式 Git - 向一个项目贡献](https://git-scm.com/book/zh/v2/%E5%88%86%E5%B8%83%E5%BC%8F-Git-%E5%90%91%E4%B8%80%E4%B8%AA%E9%A1%B9%E7%9B%AE%E8%B4%A1%E7%8C%AE) 

@ym13349140  @milanlanlan @wzl281158150 @wzl281158150

**Comment by xuelangZF** [comment]
看到你们还在不断的删除自己仓库，然后clone master仓库，来保持和我的仓库的更新。当然，你可以继续这样，如果不嫌麻烦的话。（想象面试官问你团队中使用 Github 时，如何保持和master的同步的，你说不断的删除，fork，clone。面试官会怎么想？）

或者你可以按照上面的流程。首先，假设你刚 Fork 了我最新的代码，然后clone到本地（上图1，2步骤）。接下来你应该：

1、 新建一个 dev 分支，之后你本地所有的更改和提交都是在 dev 分支进行；

2、完成了你的功能， 准备提交代码了。这时候切换到master分支，然后 pull 我的仓库（trunk repository）最新的代码。这时候你本地的 master 和我仓库的 master 仓库完全一致。

3、然后切换到 dev 分支，执行 [rebase 变基](https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%8F%98%E5%9F%BA)。（可能需要手动合并冲突）

```shell
$ git checkout experiment
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: added staged command
```

![](https://git-scm.com/book/en/v2/book/03-git-branching/images/basic-rebase-3.png)

接着回到 master 分支，进行一次快进合并。

```shell
$ git checkout master
$ git merge experiment
```

![](https://git-scm.com/book/en/v2/book/03-git-branching/images/basic-rebase-4.png)

看懂这里的两个图特别重要！！！这样就相当于你在我的最新代码的基础上，把你所有的功能一次性完成了。

4、 push 你本地的 master 到你github 上的仓库。
5、 在github页面上发起 pull request。

**Comment by xuelangZF** [comment]
Git commit 信息，信息应当以少于 50 个字符（25个汉字）的单行开始且简要地描述变更，接着是一个空白行，再接着是一个更详细的解释。 Git 项目要求一个更详细的解释，包括做改动的动机和它的实现与之前行为的对比 - 这是一个值得遵循的好规则。

<img width="730" alt="2016-12-06 8 26 07" src="https://cloud.githubusercontent.com/assets/2769831/20925519/79672a4a-bbf2-11e6-8b3b-835ab515a91a.png">

希望大家遵守这个规则。

**Comment by xuelangZF** [comment]
你的 pull request 中这么多提交，还有之前的 commit。请按照上面给出的Git流程来操作，不要我行我素！

![2016-12-29 4 22 13](https://cloud.githubusercontent.com/assets/2769831/21539569/1141bda6-cde3-11e6-9180-d49e1c8a1430.png)

**Comment by xuelangZF** [comment]
还有 commit 信息，大家都在认真的写，你的呢？直接没有commit 信息？

![image](https://cloud.githubusercontent.com/assets/2769831/21539594/5bc7f89a-cde3-11e6-983f-e444640e094e.png)

**Comment by milanlanlan** [comment]
收到！

**Comment by milanlanlan** [comment]
在上次git rebase合并commit的时候我只看得到我本地的提交，但是这次我发现看得到这个项目仓库所有的提交，而我本地有些提交已经在很远了导致修改比较困难，我估计是给了我权限的问题，不知可否删除我对本仓库的权限？

**Comment by xuelangZF** [comment]
不是因为给你的权限的问题！

你把你 Github 上项目删了之后重新 fork，然后clone到你的本地，接着按照 https://github.com/xuelangZF/ehpc/issues/55#issuecomment-265134687 中的第一步开始就行了。

你可以问下 @ym13349140  @wzl281158150 @luozhx 中的任何一个，他们现在都是按照这个流程来的，都没有出问题了。

**Comment by milanlanlan** [comment]
我确实是这个流程，不然之前也不会正常rebase了

**Comment by xuelangZF** [comment]
可能我之前**强制**更改了线上 master 的提交记录，导致你仓库的提交记录和我的不一致了。我的错，看来以后不能随便 -f 推送了。

你重新 fork ，clone 然后按照这个流程来，应该不会出问题了。
