### ISSUE TITLE
关于模板中一些名字的规范

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#6]
在模板文件中，有时候需要写死一些名字， 比如[ 导航](https://github.com/xuelangZF/ehpc/blob/master/eHPC/templates/navbar.html)栏目的内容：

```
<ul class="nav navbar-nav clearfix hidden-xs">
    <li>
        <a href="{{ url_for('course.index') }}">{{ _('Online Courses') }}</a>
    </li>
    <li>
        <a href="{{ url_for('problem.index') }}">{{ _('Examination Center') }}</a>
    </li>
    <li>
        <a href="{{ url_for('group.index') }}">{{ _('Community') }}</a>
    </li>
</ul>
```

这里要写成 `{{ _('Community') }}`  的样式，因为这样才可以用 python_babel 生成相应的翻译文件，不要直接写成 `<a href="{{ url_for('group.index') }}">{{ Community }}</a>` 。括号里面是英文，最后会生成一个英文到其他语言的文件，在里面写好相应的中文编译就好。

当然，如果嫌麻烦，可以直接写中文：`<a href="{{ url_for('group.index') }}">动态社区</a>` ，但是这样后期改动的话可能比较麻烦。注意，这里的中文直接写内容，**不要用 `{{ _('动态社区') }}`**。

flask babel:  https://pythonhosted.org/Flask-Babel/ 

@milanlanlan @SYSU-Zouzhp @ym13349140

**Comment by milanlanlan** [comment]
get
