### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by yongyiyang** [xuelangZF/ehpc#64]
目前的Bug报告：

1. ~~课程一学习中，第二个pdf文件中只支持英文检索，不支持中文检索~~（可能是 PDF 本身问题）
2. 课程一学习中，课时1的下拉列表和课时2的下拉列表无法收回（列表这块需要完善功能）
3. ~~课程一学习中，久石让 音乐暂停不支持单击屏幕方式，播放支持~~（三方库的问题，我们没法修复）
4. 单项选择题，提交之后点击暂停再点击继续就又开始计时（提交逻辑确实有问题）
5. ~~在线编程，用c++编写，没有办法编译，找不到头文件~~（后台没有实现 G++ 编译，C的编译也只是 Demo，这块暂时不考虑）

**Comment by xuelangZF** [comment]
课时内容播放页面右侧的列表，需要完善功能如下（大多数列表都是这样的）：

1. 在课程主页，打开某个课时材料时，右侧列表蓝色背景定位到某材料；
2. 通过右侧列表切换播放内容时，更新蓝色背景对应的条目；
3. 点击一个课时时，取消其他课时的蓝色背景，高亮当前的课时。

@luozhx 来完成这块。

**Comment by xuelangZF** [comment]
选择题目提交之后，点击关闭之后，应该就跳转到 http://lancs.sysu.edu.cn:9999/problems/choice/ 页面。

@wzl281158150  来更新。
