### ISSUE TITLE
Markdown 编辑框组件切换

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#65]
我们目前使用 https://github.com/toopay/bootstrap-markdown 来作为 Markdown 文本编辑组件，但是有几个问题：

1. Markdown 格式支持不完整（比如不支持 ``` 表示代码块）；
2. 每次页面加载后，markdown 窗口会出现一个变化；
3. 不支持实时预览（左边编辑，右边预览）；
4. 文档不是很齐全，很难自定义一些内容。

https://github.com/NextStepWebs/simplemde-markdown-editor 是一个更好的Markdown 编辑框，解决了上面的几个问题，并且样式更加好看。

切换成本不高，只用更改相关的前端页面即可。

@all

**Comment by xuelangZF** [comment]
参考效果： http://127.0.0.1:5000/admin/article/create/   
上述效果修改的页面：https://github.com/xuelangZF/ehpc/blob/master/eHPC/templates/admin/article/create.html

接下来需要更改目前所有的 Markdown 编辑框！可以查找 'bootstrap-markdown.min.css' 来定位当前所有包含markdown 编辑框的页面，然后进行更改。注意更改时，只用添加新的js，css，同时添加如下的 js 代码即可：

```
    <script>
        var simplemde = new SimpleMDE({
            element: document.getElementById("target-editor"),
            autosave: true,
            showIcons: ["code", "table"],
            tabSize: 4,
        });

        function validateForm() {
            var x = simplemde.value();
            if (x == null || x == "") {
                alert("请输入资讯内容");
                return false;
            }
        }
    </script>
```

不要随意更改 form 中 textarea 的name，不然后台可能拿不到数据，

@ym13349140

**Comment by xuelangZF** [comment]
@ym13349140  后台添加题目的 Markdown 编辑已经完成。 （最新版）

**Comment by ym13349140** [comment]
好的！

**Comment by xuelangZF** [comment]
Fixed by @ym13349140  on commit 8e53970a709dca830443f553cb69d8ac9931e6a1 .

@ym13349140  更新 Wiki， https://github.com/xuelangZF/ehpc/wiki/%E5%89%8D%E7%AB%AF%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C
