### ISSUE TITLE
在线编程部分，支持个人提交记录

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#68]
我们目前的在线编程还是特别原始的一个版本，现在考虑增加以下功能：

1. 登录用户可以查看自己每个题目的提交记录；
2. 在题目列表中，已经提交过的题目要加以标示。（不像其他的 OJ，能有 Accept 状态，我们目前不知道会不会判断 Accept，所以先只考虑题目列表中有提交状态列表）

# 初步设计方法

数据库设计：增加一个 submit_problem 的实体，其中包含提交用户的 ID，编程题目的 ID，以及代码，代码语言，提交时间，运行结果状态（先预留）字段。  submit_problem 和 user ， problem 都是多对多的关系。

前端设计：

题目列表页面，增加`是否提交过`的状态栏：

![image](https://cloud.githubusercontent.com/assets/2769831/19888073/4b58bafc-a067-11e6-8a1c-9baf8a38ef01.png)

题目页面，要有链接到`我的提交`页面的按钮，我的提交可以参考：

![image](https://cloud.githubusercontent.com/assets/2769831/19888107/96001028-a067-11e6-8f99-d12f4bef312c.png)

**Comment by xuelangZF** [comment]
@wzl281158150  数据库设计，后端设计；
@ym13349140  提供前端template 页面，将需要的参数名写在页面底部，加以注释（这样 @wzl281158150 知道如何传参数）
@SYSU-Zouzhp 数据库设计完之后，及时更新数据库中 ER 部分。

**Comment by ym13349140** [comment]
收到！

**Comment by SYSU-Zouzhp** [comment]
收到

**Comment by xuelangZF** [comment]
Finished by 114b584273d62112e58b89d4d0d53049edecf370
