### ISSUE TITLE
课程播放页面前端修改任务

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#75]
右侧课程导航栏：

1. 不能滑动（为了固定左边播放页面不滑动，之前对整个页面用了overflow:hidden 导致右边不能滑动，需要进一步完善！）
2. 内容超出边界（缺少  word-break 属性）

@ym13349140

**Comment by ym13349140** [comment]
收到！

**Comment by xuelangZF** [comment]
右侧导航栏还是不能滑动：

![2016-11-08 11 30 43](https://cloud.githubusercontent.com/assets/2769831/20085906/2978dca6-a5a7-11e6-989a-41d2fc8aa0f1.png)

![2016-11-08 11 33 11](https://cloud.githubusercontent.com/assets/2769831/20085909/2f62c74e-a5a7-11e6-8a9c-f601025790a1.png)

课时材料过多时，目录栏目需要可以滑动！

明白我的意思了吗？

**Comment by ym13349140** [comment]
我这边是可以滑动的呀，是这样的效果吧？
![image](https://cloud.githubusercontent.com/assets/17507937/20087046/18a96400-a5b0-11e6-893c-03d04abc9dc4.png)
