### ISSUE TITLE
课程试卷功能用户页面

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#81]
新增加课程试卷功能（主要参考 http://demo.edusoho.com/test/5855/show ）

功能入口在： http://127.0.0.1:5000/course/1/ 页面中，（课程概览，课时列表，**课堂试卷** 选项卡）

试卷支持的题目：单选题，多选题，不定项选择，填空，判断，问答题。（需要设置这些题型的数据库model）。注意，每道题目除了题目描述外，还有答案、分数等字段（尽可能使字段齐全）。

试卷答题页面可以参考 http://demo.edusoho.com/test/5855/show   
交卷后的页面可以参考 http://demo.edusoho.com/test/5855/result

**Comment by xuelangZF** [comment]
@wzl281158150  完成

**Comment by xuelangZF** [comment]
finish on commit b4f5dca386bef811ba59d29ac845fe4ea07754a2

**Comment by xuelangZF** [comment]
仍然需要完善的地方：

1. 交卷后对题目正确答案的显示。

    ![image](https://cloud.githubusercontent.com/assets/2769831/20244643/ee8f7600-a9c4-11e6-8fc1-0e56dee28bd7.png)

2. 答题时页面上端的条目去掉。（或者想 edusoho 那样可以滑动跟随，并且高亮显示当前题目类型）
    ![image](https://cloud.githubusercontent.com/assets/2769831/20244631/9bca7cda-a9c4-11e6-8d66-06b2e349c04d.png)

**Comment by xuelangZF** [comment]
做的怎么样了？什么进度呢

**Comment by wzl281158150** [comment]
pull request已提交 @xuelangZF
