### ISSUE TITLE
Bug Report(11.08 )

### ISSUE THREAD

**Issue by yongyiyang** [xuelangZF/ehpc#83]
1、在意见反馈话题讨论组中，新建话题之后，在话题详细内容界面显示是一分钟前，但是在讨论组界面当中显示8小时之前发布。（Bug！）

2、在发布新的讨论话题的时候，预览功能可以显示正确界面，但是发布成功之后，显示的并不是预览时候的正确界面。（Bug！主要是表格不能正常显示）

3、网站不支持话题搜索，是因为还没做这个功能吗？（还没有支持搜索）

4、课程学习中，没有页面的滚动条，个人认为可能加一个滚动条比较好。现在的页面感觉有点奇怪，和网站其他页面相比有些不协调（已经在修复..）

**Comment by xuelangZF** [comment]
Fix 1,2 on commit 12142ac1ba5cb759665b041105b15be38099e243

**Comment by xuelangZF** [comment]
第四个问题 @ym13349140  今天修复！

**Comment by xuelangZF** [comment]
Fix 4 on commit 630a3c7d7f6ab206177b68359d1f1b4c083c54ca
