### ISSUE TITLE
题库前端模块化重构任务

### ISSUE THREAD

**Issue by xuelangZF** [xuelangZF/ehpc#98]
主要任务如下：

1. 重构目前题库相关的前端页面，将之前大的页面用模板继承切分成小的模板文件，方便集成进虚拟实验室部分。
2. 题库页面支持其他题型（目前只是选择题目）的在线练习(http://a002.nscc-gz.cn:10165/problems/ 中专项练习部分知识点下面可以包含其他题型)。

模板继承相关内容参考： 

http://docs.jinkan.org/docs/jinja2/templates.html#template-inheritance
[include 使用](http://docs.jinkan.org/docs/jinja2/templates.html#id25)  

# 模板复用

模板文件复用规则：

1. 小的模板块负责内容的展示；
2. 大的模版可以include 多个小的base模板块，并且负责具体的布局展示。

示例：

topic_detail.html 里面引用了 widget_topic_detail.html 这个小模板文件：

```
<div class="col-md-9 group-main">  # 大模板文件指定布局
    {% include 'group/widget_topic_detail.html' %}    # 这里只负责显示内容
</div>
```

在 widget_topic_detail 里面还可以继续引用其他小模块，比如 

```
{% if topic.postNum %}
    <ul class="list-group" id="post-area">
        {% for p in topic.posts %}
            {% with index=loop.index, p=p %}
                {% include 'group/widget_post_detail.html' %}
            {% endwith %}
        {% endfor %}
    </ul>
{% else %}
```

这样，前端很好的模块化，方便修改代码，进行重用！

# JS结构化

将同一逻辑任务的 js 尽量写进一个文件，页面里面不要有太多的 js 代码。对 js 进行**重构，加注释**，方便其他小伙伴理解。（毕竟大家 js 都是刚入门）

关于 JS 的模块化，可以参考

[JavaScript 模块化编程](http://yangfch3.com/2016/05/12/js-modularity/)

**强烈推荐 JavaScript Dom编程艺术（第2版）**

@wzl281158150 看到后请在下面回复是否 Get！

**Comment by wzl281158150** [comment]
收到

**Comment by xuelangZF** [comment]
关于 https://github.com/xuelangZF/ehpc/pull/103 的反馈：

**代码冗余度还是很高，没有很好的复用。**

比如你的 `problem/choice_detail.html`, `problem/essay_detail.html`，`problem/fill_detail.html`这三个文件，有很高的相似度。可以考虑进一步进行整合。一个建议：

<img width="605" alt="2016-11-20 10 17 37" src="https://cloud.githubusercontent.com/assets/2769831/20459817/92eac2d2-af0a-11e6-89de-51c9ee617d74.png">

此外，关于答题逻辑，不建议使用“**确定按钮**”，直接用 “下一题” 进入下一道题目。（不过可以判断下当前题目是否没有作答，没有作答的话，右边题目作答表单中相应题目不要标示已作答）。 可以参考 牛客网 的题目作答逻辑。

http://www.nowcoder.com/question/next?pid=1701810&qid=44795&tid=6023436

@wzl281158150

**Comment by xuelangZF** [comment]
有空余时间的话要尝试把 js 脚本放进 js 文件，方便使用！

强烈推荐 JavaScript Dom编程艺术（第2版）
@wzl281158150

**Comment by wzl281158150** [comment]
若不使用确定按钮，则填空题只能实时判断 正确与否  选择题在点击每个选项后判断   对于选择题非常不好，可以乱点出答案

**Comment by wzl281158150** [comment]
js部分，大部分使用的是jquery写法，不知道如何将其类化。。

**Comment by xuelangZF** [comment]
不太明白你的意思，不过一种变通方法是：你可以把原来属于 确定按钮 的功能，放进**下一题**按钮的事件里面。

**Comment by xuelangZF** [comment]
js 部分也不用类化，可以看下 JavaScript Dom编程艺术（第2版） 第5章的内容，将 html 与 js 分离就行！

**Comment by wzl281158150** [comment]
好的，我修改一下

**Comment by wzl281158150** [comment]
请问，除了回复中的几个页面外，还有哪些页面比较重复？ 因为很多管理页面不是我写的，所以不是很了解

**Comment by xuelangZF** [comment]
主要是你要看如果两个页面的布局差不多，除了其中一两部分有区别，那么就可以将其抽象为一个模板，然后不同的部分 include 不同的子模板。

**Comment by wzl281158150** [comment]
请问 如果是  内部标签不同  外部标签相同 该如何建立模版   类似与extends这样的效果  但是 extends 必须在页面第一行  如果想在中间使用，该怎么办

**Comment by xuelangZF** [comment]
extends 类似于面向对象中继承的概念（页面 A is a 页面B，而不是 A has a B），不能在页面的中间使用！

如果想 “内部标签不同 外部标签相同”， 你就先建立一个 base 页面，把相同的标签写进去，然后用 block 来标记那些不同的外部标签。这样不同页面填充不同的block就行。类似于我们站点的 base 页面。

**Comment by wzl281158150** [comment]
我已经这样做了，但是页面本身首先需要extends base.html  那如何 include我的这个base文件

**Comment by wzl281158150** [comment]
因为choice_detail.html等几个文件 都是 内部块不同，同时，外部标签长度明显大于内部标签，如果使用include则需要新建4个文件  而若是可以将外部相同的标签写成模版，则只需要新建1个文件，关键是如何在  使用了extends base.html 的提前下   在中间 使用我创建的question_base.html页面    使其具有block的功能  在不同页面填充block

**Comment by wzl281158150** [comment]
还是说，直接在question_base.html中使用if语句。。。然后在detail文件中include..

**Comment by xuelangZF** [comment]
include是需要4个模板文件的，每个模板代表一个题型的个性化展示。

然后只用一个 problem_detail.html 文件，在该文件根据文件类型，include 不同的子模板文件

**Comment by wzl281158150** [comment]
还有一个问题，有些数据必须使用flask模版将参数传递给js，如果写成js文件，请问如何传递参数。使用标签的话，不能解决 参数是一个类的情况

**Comment by wzl281158150** [comment]
@xuelangZF

**Comment by xuelangZF** [comment]
“使用标签的话，不能解决 参数是一个类的情况 ”    ？？？ 不懂什么意思。

个别的情况，可以在页面使用 js 啊。将其分离主要是为了在不同页面共用一些js代码，并且让页面结构清晰一点。

**Comment by xuelangZF** [comment]
还有一个问题：我在题库练习时，为什么要选择题型呢。一个知识点下面本来就可以有多种题型的啊，直接进行练习，然后可以进行多种题型的练习不好吗？

**Comment by xuelangZF** [comment]
试了下功能，重构后提交试卷不成功。 @wzl281158150

**Comment by wzl281158150** [comment]
是直接显示所有题型吗？

**Comment by wzl281158150** [comment]
试卷提交问题已解决，在线练习方面，是要直接吧所有题型混在一起吗？这样会不会乱？
